  monster_id: 100014
  levels {
    level: 4
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        group {
          condition {
            trigger_turn: 1
          }
          children {
            behavior {
              enemy_skill_id: 10421
            }
          }
        }
      }
      children {
        group {
          children {
            behavior {
              condition {
                use_chance: 50
              }
              enemy_skill_id: 10421
            }
          }
          children {
            behavior {
              enemy_skill_id: 10422
            }
          }
        }
      }
    }
    groups {
      group_type: REMAINING
      condition {
        hp_threshold: 100
        trigger_enemies_remaining: 2
      }
      children {
        group {
          condition {
            trigger_turn: 1
          }
          children {
            behavior {
              enemy_skill_id: 10421
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 2
          }
          children {
            behavior {
              enemy_skill_id: 10423
            }
          }
        }
      }
    }
    groups {
      group_type: REMAINING
      condition {
        hp_threshold: 100
        trigger_enemies_remaining: 1
      }
      children {
        group {
          condition {
            trigger_turn: 1
          }
          children {
            behavior {
              enemy_skill_id: 10421
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 2
          }
          children {
            behavior {
              enemy_skill_id: 10424
            }
          }
        }
      }
      children {
        group {
          children {
            behavior {
              enemy_skill_id: 10425
            }
          }
        }
      }
    }
  }
