  monster_id: 100207
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 14259
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            behavior {
              enemy_skill_id: 14260
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 50
            trigger_turn: 1
          }
          children {
            behavior {
              enemy_skill_id: 14258
            }
          }
        }
      }
    }
    groups {
      group_type: REMAINING
      condition {
        hp_threshold: 50
        trigger_enemies_remaining: 1
        trigger_turn: 1
      }
      children {
        behavior {
          enemy_skill_id: 14257
        }
      }
    }
  }
