  monster_id: 100264
  levels {
    level: 1
    groups {
      group_type: STANDARD
      children {
        group {
          condition {
            trigger_turn: 1
            always_trigger_above: 1
          }
          children {
            behavior {
              enemy_skill_id: 4775
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 74
          }
          children {
            behavior {
              condition {
                use_chance: 10
              }
              enemy_skill_id: 4774
            }
          }
        }
      }
    }
  }
  levels {
    level: 5
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 4775
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 74
      }
      children {
        behavior {
          condition {
            use_chance: 10
          }
          enemy_skill_id: 4774
        }
      }
    }
  }
