  monster_id: 100346
  levels {
    level: 1
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        behavior {
          condition {
            use_chance: 25
          }
          enemy_skill_id: 31
        }
      }
    }
  }
