  monster_id: 100411
  levels {
    level: 1
    groups {
      group_type: PASSIVE
      children {
        behavior {
          enemy_skill_id: 10853
        }
      }
    }
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 10798
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            group {
              condition {
                trigger_turn: 1
                trigger_turn_end: 4
                always_trigger_above: 29
              }
              children {
                behavior {
                  enemy_skill_id: 10857
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 5
                always_trigger_above: 29
              }
              children {
                behavior {
                  enemy_skill_id: 10858
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  enemy_skill_id: 10859
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 29
            trigger_turn: 1
          }
          children {
            behavior {
              enemy_skill_id: 10858
            }
          }
        }
      }
    }
  }
  levels {
    level: 6
    groups {
      group_type: PASSIVE
      children {
        behavior {
          enemy_skill_id: 10853
        }
      }
    }
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 10856
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            group {
              condition {
                trigger_turn: 1
                trigger_turn_end: 4
                always_trigger_above: 29
              }
              children {
                behavior {
                  enemy_skill_id: 10857
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 5
                always_trigger_above: 29
              }
              children {
                behavior {
                  enemy_skill_id: 10858
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  enemy_skill_id: 10859
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 29
            trigger_turn: 1
          }
          children {
            behavior {
              enemy_skill_id: 10858
            }
          }
        }
      }
    }
  }
