  monster_id: 100475
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 5562
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            behavior {
              condition {
                use_chance: 30
              }
              enemy_skill_id: 5563
            }
          }
          children {
            behavior {
              enemy_skill_id: 5565
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 34
          }
          children {
            behavior {
              condition {
                use_chance: 40
              }
              enemy_skill_id: 5564
            }
          }
          children {
            behavior {
              condition {
                use_chance: 30
              }
              enemy_skill_id: 5563
            }
          }
          children {
            behavior {
              enemy_skill_id: 5565
            }
          }
        }
      }
    }
  }
