  monster_id: 100409
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 5113
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          condition {
            trigger_turn: 1
            always_trigger_above: 1
          }
          children {
            behavior {
              enemy_skill_id: 5119
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 4
            always_trigger_above: 1
          }
          children {
            behavior {
              enemy_skill_id: 5120
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 7
            always_trigger_above: 1
          }
          children {
            behavior {
              enemy_skill_id: 5121
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            group {
              condition {
                trigger_turn: 2
                trigger_turn_end: 3
                always_trigger_above: 69
              }
              children {
                behavior {
                  enemy_skill_id: 5114
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 5
                trigger_turn_end: 6
                always_trigger_above: 69
              }
              children {
                behavior {
                  enemy_skill_id: 5114
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  enemy_skill_id: 5114
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 69
          }
          children {
            group {
              condition {
                trigger_turn: 2
                trigger_turn_end: 3
                always_trigger_above: 49
              }
              children {
                behavior {
                  enemy_skill_id: 5115
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 5
                trigger_turn_end: 6
                always_trigger_above: 49
              }
              children {
                behavior {
                  enemy_skill_id: 5115
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  enemy_skill_id: 5115
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 49
          }
          children {
            group {
              condition {
                trigger_turn: 2
                trigger_turn_end: 3
                always_trigger_above: 29
              }
              children {
                behavior {
                  enemy_skill_id: 5116
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 5
                trigger_turn_end: 6
                always_trigger_above: 29
              }
              children {
                behavior {
                  enemy_skill_id: 5116
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  enemy_skill_id: 5116
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 29
          }
          children {
            group {
              condition {
                trigger_turn: 2
                trigger_turn_end: 3
                always_trigger_above: 14
              }
              children {
                behavior {
                  enemy_skill_id: 5117
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 5
                trigger_turn_end: 6
                always_trigger_above: 14
              }
              children {
                behavior {
                  enemy_skill_id: 5117
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  enemy_skill_id: 5117
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 14
          }
          children {
            group {
              condition {
                trigger_turn: 2
                trigger_turn_end: 3
              }
              children {
                behavior {
                  enemy_skill_id: 5118
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 5
                trigger_turn_end: 6
              }
              children {
                behavior {
                  enemy_skill_id: 5118
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  enemy_skill_id: 5118
                }
              }
            }
          }
        }
      }
    }
  }
