  monster_id: 100414
  levels {
    level: 1
    groups {
      group_type: PASSIVE
      children {
        behavior {
          enemy_skill_id: 25705
        }
      }
    }
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 25700
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            group {
              condition {
                trigger_turn: 1
              }
              children {
                behavior {
                  enemy_skill_id: 25701
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 2
              }
              children {
                behavior {
                  enemy_skill_id: 25702
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 3
                trigger_turn_end: 4
              }
              children {
                behavior {
                  enemy_skill_id: 25703
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  enemy_skill_id: 25704
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 1
            trigger_turn: 1
            trigger_turn_end: 4
          }
          children {
            behavior {
              enemy_skill_id: 25711
            }
          }
        }
      }
    }
  }
