  monster_id: 100597
  levels {
    level: 1
    groups {
      group_type: STANDARD
      children {
        group {
          condition {
            trigger_turn: 1
            always_trigger_above: 1
          }
          children {
            behavior {
              enemy_skill_id: 88
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 74
          }
          children {
            behavior {
              condition {
                use_chance: 75
              }
              enemy_skill_id: 89
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 54
          }
          children {
            behavior {
              condition {
                use_chance: 20
                global_one_time: true
              }
              enemy_skill_id: 100
            }
          }
          children {
            behavior {
              condition {
                use_chance: 75
              }
              enemy_skill_id: 89
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 39
            trigger_turn: 2
          }
          children {
            behavior {
              enemy_skill_id: 99
            }
          }
        }
      }
    }
  }
