  monster_id: 100663
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 10703
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 49
      }
      children {
        behavior {
          enemy_skill_id: 1349
        }
      }
    }
  }
