  monster_id: 100814
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 744
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          condition {
            trigger_turn: 2
            always_trigger_above: 1
          }
          children {
            behavior {
              enemy_skill_id: 747
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 3
            always_trigger_above: 1
          }
          children {
            behavior {
              enemy_skill_id: 748
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 4
            always_trigger_above: 1
          }
          children {
            behavior {
              enemy_skill_id: 745
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 5
            always_trigger_above: 1
          }
          children {
            behavior {
              enemy_skill_id: 747
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 6
            always_trigger_above: 1
          }
          children {
            behavior {
              enemy_skill_id: 748
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 7
            always_trigger_above: 1
          }
          children {
            behavior {
              enemy_skill_id: 745
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 8
            always_trigger_above: 1
          }
          children {
            behavior {
              enemy_skill_id: 747
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 9
            always_trigger_above: 1
          }
          children {
            behavior {
              enemy_skill_id: 748
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 10
            always_trigger_above: 1
          }
          children {
            behavior {
              enemy_skill_id: 745
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 11
            always_trigger_above: 1
          }
          children {
            behavior {
              enemy_skill_id: 747
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 12
            always_trigger_above: 1
          }
          children {
            behavior {
              enemy_skill_id: 744
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 13
            always_trigger_above: 1
          }
          children {
            behavior {
              enemy_skill_id: 748
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 14
            always_trigger_above: 1
          }
          children {
            behavior {
              enemy_skill_id: 745
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 15
            always_trigger_above: 1
          }
          children {
            behavior {
              enemy_skill_id: 747
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 16
            always_trigger_above: 1
          }
          children {
            behavior {
              enemy_skill_id: 748
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 17
            always_trigger_above: 1
          }
          children {
            behavior {
              enemy_skill_id: 745
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 18
            always_trigger_above: 1
          }
          children {
            behavior {
              enemy_skill_id: 747
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 19
            always_trigger_above: 1
          }
          children {
            behavior {
              enemy_skill_id: 748
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 20
            always_trigger_above: 1
          }
          children {
            behavior {
              enemy_skill_id: 745
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 21
            always_trigger_above: 1
          }
          children {
            behavior {
              enemy_skill_id: 747
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 22
            always_trigger_above: 1
          }
          children {
            behavior {
              enemy_skill_id: 748
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 23
            always_trigger_above: 1
          }
          children {
            behavior {
              enemy_skill_id: 744
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 24
            always_trigger_above: 1
          }
          children {
            behavior {
              enemy_skill_id: 745
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 25
            always_trigger_above: 1
          }
          children {
            behavior {
              enemy_skill_id: 747
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 26
            always_trigger_above: 1
          }
          children {
            behavior {
              enemy_skill_id: 748
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 27
            always_trigger_above: 1
          }
          children {
            behavior {
              enemy_skill_id: 745
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 28
            always_trigger_above: 1
          }
          children {
            behavior {
              enemy_skill_id: 747
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 29
            always_trigger_above: 1
          }
          children {
            behavior {
              enemy_skill_id: 748
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 30
            always_trigger_above: 1
          }
          children {
            behavior {
              enemy_skill_id: 745
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 31
            always_trigger_above: 1
          }
          children {
            behavior {
              enemy_skill_id: 747
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 32
            always_trigger_above: 1
          }
          children {
            behavior {
              enemy_skill_id: 748
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 33
            always_trigger_above: 1
          }
          children {
            behavior {
              enemy_skill_id: 745
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 34
            always_trigger_above: 1
          }
          children {
            behavior {
              enemy_skill_id: 744
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            group {
              condition {
                trigger_turn: 1
                always_trigger_above: 49
              }
              children {
                behavior {
                  enemy_skill_id: 745
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 3
                trigger_turn: 1
              }
              children {
                behavior {
                  enemy_skill_id: 747
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 3
                trigger_turn: 2
              }
              children {
                behavior {
                  enemy_skill_id: 748
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 3
                trigger_turn: 3
              }
              children {
                behavior {
                  enemy_skill_id: 745
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 49
            trigger_turn: 1
          }
          children {
            behavior {
              enemy_skill_id: 746
            }
          }
          children {
            behavior {
              enemy_skill_id: 745
            }
          }
        }
      }
    }
  }
