  monster_id: 101098
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 9544
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        group {
          condition {
            trigger_turn: 1
          }
          children {
            behavior {
              enemy_skill_id: 866
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 2
          }
          children {
            behavior {
              enemy_skill_id: 9547
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 3
          }
          children {
            behavior {
              enemy_skill_id: 9548
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 4
          }
          children {
            behavior {
              enemy_skill_id: 9549
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 5
          }
          children {
            behavior {
              enemy_skill_id: 9550
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 6
          }
          children {
            behavior {
              enemy_skill_id: 9551
            }
          }
        }
      }
      children {
        group {
          children {
            behavior {
              enemy_skill_id: 872
            }
          }
        }
      }
    }
  }
