  monster_id: 101063
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 16090
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        behavior {
          enemy_skill_id: 16092
        }
      }
    }
  }
  levels {
    level: 6
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 16091
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        behavior {
          enemy_skill_id: 16092
        }
      }
    }
  }
  levels {
    level: 7
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 16090
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        behavior {
          enemy_skill_id: 16092
        }
      }
    }
  }
  levels {
    level: 8
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 16091
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        behavior {
          enemy_skill_id: 16092
        }
      }
    }
  }
  levels {
    level: 9
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 16090
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        behavior {
          enemy_skill_id: 16092
        }
      }
    }
  }
  levels {
    level: 10
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 16091
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        behavior {
          enemy_skill_id: 16092
        }
      }
    }
  }
