  monster_id: 101461
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          condition {
            use_chance: 10
          }
          enemy_skill_id: 5532
        }
      }
      children {
        behavior {
          condition {
            use_chance: 10
          }
          enemy_skill_id: 5533
        }
      }
      children {
        behavior {
          condition {
            use_chance: 10
          }
          enemy_skill_id: 5534
        }
      }
      children {
        behavior {
          condition {
            use_chance: 10
          }
          enemy_skill_id: 5535
        }
      }
      children {
        behavior {
          condition {
            use_chance: 10
          }
          enemy_skill_id: 5536
        }
      }
      children {
        behavior {
          condition {
            use_chance: 10
          }
          enemy_skill_id: 5537
        }
      }
      children {
        behavior {
          condition {
            use_chance: 10
          }
          enemy_skill_id: 5538
        }
      }
      children {
        behavior {
          condition {
            use_chance: 10
          }
          enemy_skill_id: 5539
        }
      }
      children {
        behavior {
          condition {
            use_chance: 10
          }
          enemy_skill_id: 5540
        }
      }
      children {
        behavior {
          condition {
            use_chance: 10
          }
          enemy_skill_id: 5541
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            group {
              condition {
                repeats_every: 2
                trigger_turn: 1
              }
              children {
                behavior {
                  condition {
                    use_chance: 30
                  }
                  enemy_skill_id: 5516
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 50
                  }
                  enemy_skill_id: 5517
                }
              }
              children {
                behavior {
                  enemy_skill_id: 5518
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 2
                trigger_turn: 2
              }
              children {
                behavior {
                  condition {
                    use_chance: 10
                  }
                  enemy_skill_id: 5542
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 10
                  }
                  enemy_skill_id: 5543
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 10
                  }
                  enemy_skill_id: 5544
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 10
                  }
                  enemy_skill_id: 5545
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 10
                  }
                  enemy_skill_id: 5546
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 10
                  }
                  enemy_skill_id: 5547
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 10
                  }
                  enemy_skill_id: 5548
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 10
                  }
                  enemy_skill_id: 5549
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 10
                  }
                  enemy_skill_id: 5550
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 10
                  }
                  enemy_skill_id: 5551
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 19
          }
          children {
            behavior {
              enemy_skill_id: 5520
            }
          }
        }
      }
    }
  }
