  monster_id: 101527
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          condition {
            use_chance: 20
          }
          enemy_skill_id: 8192
        }
      }
      children {
        behavior {
          condition {
            use_chance: 20
          }
          enemy_skill_id: 8193
        }
      }
      children {
        behavior {
          condition {
            use_chance: 20
          }
          enemy_skill_id: 8194
        }
      }
      children {
        behavior {
          condition {
            use_chance: 20
          }
          enemy_skill_id: 8195
        }
      }
      children {
        behavior {
          condition {
            use_chance: 20
          }
          enemy_skill_id: 8196
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 74
        repeats_every: 2
        trigger_turn: 1
      }
      children {
        behavior {
          enemy_skill_id: 8196
        }
      }
    }
  }
