  monster_id: 101602
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 8010
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 101
          }
          children {
            behavior {
              enemy_skill_id: 3106
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 99
          }
          children {
            behavior {
              condition {
                use_chance: 20
              }
              enemy_skill_id: 3105
            }
          }
          children {
            behavior {
              condition {
                use_chance: 70
              }
              enemy_skill_id: 3104
            }
          }
          children {
            behavior {
              enemy_skill_id: 3103
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 19
          }
          children {
            behavior {
              enemy_skill_id: 3106
            }
          }
        }
      }
    }
  }
