  monster_id: 101644
  levels {
    level: 1
    groups {
      group_type: PASSIVE
      children {
        behavior {
          enemy_skill_id: 6842
        }
      }
      children {
        behavior {
          enemy_skill_id: 8256
        }
      }
    }
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 6827
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            behavior {
              enemy_skill_id: 6828
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 70
          }
          children {
            behavior {
              condition {
                use_chance: 11
              }
              enemy_skill_id: 6829
            }
          }
          children {
            behavior {
              condition {
                use_chance: 11
              }
              enemy_skill_id: 6830
            }
          }
          children {
            behavior {
              condition {
                use_chance: 11
              }
              enemy_skill_id: 6831
            }
          }
          children {
            behavior {
              condition {
                use_chance: 11
              }
              enemy_skill_id: 6832
            }
          }
          children {
            behavior {
              condition {
                use_chance: 11
              }
              enemy_skill_id: 6833
            }
          }
          children {
            behavior {
              condition {
                use_chance: 11
              }
              enemy_skill_id: 6834
            }
          }
          children {
            behavior {
              condition {
                use_chance: 11
              }
              enemy_skill_id: 6835
            }
          }
          children {
            behavior {
              condition {
                use_chance: 11
              }
              enemy_skill_id: 6836
            }
          }
          children {
            behavior {
              condition {
                use_chance: 11
              }
              enemy_skill_id: 6837
            }
          }
          children {
            behavior {
              condition {
                use_chance: 11
              }
              enemy_skill_id: 6838
            }
          }
          children {
            behavior {
              condition {
                use_chance: 12
              }
              enemy_skill_id: 6839
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 49
            trigger_turn: 1
            always_trigger_above: 9
          }
          children {
            behavior {
              enemy_skill_id: 6841
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 9
          }
          children {
            behavior {
              enemy_skill_id: 6843
            }
          }
        }
      }
    }
  }
