  monster_id: 101847
  levels {
    level: 1
    groups {
      group_type: PASSIVE
      children {
        behavior {
          enemy_skill_id: 8794
        }
      }
    }
  }
  levels {
    level: 5
    groups {
      group_type: PASSIVE
      children {
        behavior {
          enemy_skill_id: 8794
        }
      }
    }
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 2347
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          condition {
            trigger_turn: 1
            always_trigger_above: 1
          }
          children {
            behavior {
              enemy_skill_id: 2333
            }
          }
          children {
            behavior {
              enemy_skill_id: 2334
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            behavior {
              enemy_skill_id: 2338
            }
          }
          children {
            behavior {
              condition {
                use_chance: 33
              }
              enemy_skill_id: 2337
            }
          }
          children {
            behavior {
              condition {
                use_chance: 33
              }
              enemy_skill_id: 2339
            }
          }
          children {
            behavior {
              condition {
                use_chance: 33
              }
              enemy_skill_id: 2340
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 49
            trigger_turn: 2
            always_trigger_above: 1
          }
          children {
            behavior {
              enemy_skill_id: 2343
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 29
          }
          children {
            group {
              condition {
                trigger_turn: 3
              }
              children {
                behavior {
                  enemy_skill_id: 2344
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  enemy_skill_id: 2345
                }
              }
            }
          }
        }
      }
    }
  }
