  monster_id: 101857
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 1861
        }
      }
    }
  }
  levels {
    level: 5
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 1861
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            behavior {
              condition {
                use_chance: 50
              }
              enemy_skill_id: 1863
            }
          }
          children {
            behavior {
              condition {
                use_chance: 60
                global_one_time: true
              }
              enemy_skill_id: 1862
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 29
          }
          children {
            group {
              condition {
                trigger_turn: 1
              }
              children {
                behavior {
                  enemy_skill_id: 1864
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  enemy_skill_id: 1865
                }
              }
            }
          }
        }
      }
    }
  }
