  monster_id: 101956
  levels {
    level: 1
    groups {
      group_type: PASSIVE
      children {
        behavior {
          enemy_skill_id: 2214
        }
      }
    }
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 2215
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            group {
              condition {
                repeats_every: 2
                trigger_turn: 1
              }
              children {
                behavior {
                  enemy_skill_id: 2217
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 2
                trigger_turn: 2
              }
              children {
                behavior {
                  condition {
                    use_chance: 50
                  }
                  enemy_skill_id: 2218
                }
              }
              children {
                behavior {
                  enemy_skill_id: 2216
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 29
          }
          children {
            behavior {
              enemy_skill_id: 2219
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 1
          }
          children {
            behavior {
              enemy_skill_id: 8236
            }
          }
        }
      }
    }
  }
