  monster_id: 102130
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 8004
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            group {
              condition {
                repeats_every: 6
                trigger_turn: 1
                trigger_turn_end: 5
              }
              children {
                behavior {
                  condition {
                    use_chance: 34
                  }
                  enemy_skill_id: 5752
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 33
                  }
                  enemy_skill_id: 5753
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 33
                  }
                  enemy_skill_id: 5754
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 6
                trigger_turn: 6
              }
              children {
                behavior {
                  enemy_skill_id: 5755
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 49
          }
          children {
            group {
              condition {
                trigger_turn: 1
              }
              children {
                behavior {
                  enemy_skill_id: 5756
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 6
                trigger_turn: 1
                trigger_turn_end: 4
              }
              children {
                behavior {
                  condition {
                    use_chance: 34
                  }
                  enemy_skill_id: 5752
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 33
                  }
                  enemy_skill_id: 5753
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 33
                  }
                  enemy_skill_id: 5754
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 6
                trigger_turn: 5
              }
              children {
                behavior {
                  enemy_skill_id: 5755
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 6
                trigger_turn: 6
              }
              children {
                behavior {
                  condition {
                    use_chance: 34
                  }
                  enemy_skill_id: 5752
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 33
                  }
                  enemy_skill_id: 5753
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 33
                  }
                  enemy_skill_id: 5754
                }
              }
            }
          }
        }
      }
    }
  }
