  monster_id: 102481
  levels {
    level: 4
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 3484
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            behavior {
              condition {
                use_chance: 70
              }
              enemy_skill_id: 3485
            }
          }
          children {
            behavior {
              condition {
                use_chance: 70
              }
              enemy_skill_id: 3488
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 49
            trigger_turn: 1
            always_trigger_above: 1
          }
          children {
            behavior {
              condition {
                trigger_monsters: 2468
                trigger_monsters: 2469
              }
              enemy_skill_id: 3491
            }
          }
          children {
            behavior {
              enemy_skill_id: 3486
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 19
          }
          children {
            group {
              condition {
                trigger_turn: 2
              }
              children {
                behavior {
                  enemy_skill_id: 3487
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  enemy_skill_id: 3489
                }
              }
            }
          }
        }
      }
    }
  }
