  monster_id: 102664
  levels {
    level: 1
    groups {
      group_type: PASSIVE
      children {
        behavior {
          enemy_skill_id: 8261
        }
      }
    }
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 6439
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          condition {
            trigger_turn: 1
            always_trigger_above: 1
          }
          children {
            behavior {
              enemy_skill_id: 6443
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            group {
              condition {
                repeats_every: 3
                trigger_turn: 1
              }
              children {
                behavior {
                  enemy_skill_id: 6452
                }
              }
              children {
                behavior {
                  enemy_skill_id: 6453
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 3
                trigger_turn: 2
              }
              children {
                behavior {
                  enemy_skill_id: 6452
                }
              }
              children {
                behavior {
                  enemy_skill_id: 6473
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 3
                trigger_turn: 3
              }
              children {
                behavior {
                  enemy_skill_id: 6452
                }
              }
              children {
                behavior {
                  enemy_skill_id: 6474
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 49
          }
          children {
            group {
              condition {
                trigger_turn: 2
                always_trigger_above: 1
              }
              children {
                behavior {
                  enemy_skill_id: 6446
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 3
                always_trigger_above: 1
              }
              children {
                behavior {
                  enemy_skill_id: 6448
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 29
          }
          children {
            behavior {
              enemy_skill_id: 6451
            }
          }
        }
      }
    }
    groups {
      group_type: UNKNOWN_USE
      children {
        behavior {
          condition {
            limited_execution: 3
          }
          enemy_skill_id: 6449
        }
      }
    }
  }
