  monster_id: 102741
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 8219
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: MONSTER_STATUS
          children {
            behavior {
              enemy_skill_id: 4821
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            behavior {
              condition {
                if_attributes_available: true
              }
              enemy_skill_id: 4822
            }
          }
          children {
            behavior {
              condition {
                if_attributes_available: true
              }
              enemy_skill_id: 4823
            }
          }
          children {
            behavior {
              condition {
                if_attributes_available: true
              }
              enemy_skill_id: 4822
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 9
          }
          children {
            behavior {
              condition {
                if_attributes_available: true
              }
              enemy_skill_id: 4822
            }
          }
          children {
            behavior {
              condition {
                if_attributes_available: true
              }
              enemy_skill_id: 4824
            }
          }
          children {
            behavior {
              condition {
                if_attributes_available: true
              }
              enemy_skill_id: 4823
            }
          }
          children {
            behavior {
              condition {
                if_attributes_available: true
              }
              enemy_skill_id: 4822
            }
          }
        }
      }
    }
  }
