  monster_id: 102805
  levels {
    level: 1
    groups {
      group_type: PASSIVE
      children {
        behavior {
          enemy_skill_id: 3868
        }
      }
    }
    groups {
      group_type: PREEMPT
      children {
        behavior {
          condition {
            use_chance: 5
          }
          enemy_skill_id: 3855
        }
      }
      children {
        behavior {
          condition {
            use_chance: 5
          }
          enemy_skill_id: 3856
        }
      }
      children {
        behavior {
          condition {
            use_chance: 5
          }
          enemy_skill_id: 3857
        }
      }
      children {
        behavior {
          condition {
            use_chance: 5
          }
          enemy_skill_id: 3858
        }
      }
      children {
        behavior {
          condition {
            use_chance: 5
          }
          enemy_skill_id: 3859
        }
      }
      children {
        behavior {
          condition {
            use_chance: 25
          }
          enemy_skill_id: 3860
        }
      }
      children {
        behavior {
          condition {
            use_chance: 25
          }
          enemy_skill_id: 3861
        }
      }
      children {
        behavior {
          condition {
            use_chance: 25
          }
          enemy_skill_id: 3862
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            group {
              condition {
                repeats_every: 2
                trigger_turn: 1
              }
              children {
                behavior {
                  condition {
                    use_chance: 20
                  }
                  enemy_skill_id: 3863
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 20
                  }
                  enemy_skill_id: 3864
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 20
                  }
                  enemy_skill_id: 3865
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 20
                  }
                  enemy_skill_id: 3866
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 20
                  }
                  enemy_skill_id: 3867
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 2
                trigger_turn: 2
              }
              children {
                behavior {
                  condition {
                    use_chance: 5
                  }
                  enemy_skill_id: 3847
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 5
                  }
                  enemy_skill_id: 3848
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 5
                  }
                  enemy_skill_id: 3849
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 5
                  }
                  enemy_skill_id: 3850
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 5
                  }
                  enemy_skill_id: 3851
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 25
                  }
                  enemy_skill_id: 3852
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 25
                  }
                  enemy_skill_id: 3853
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 25
                  }
                  enemy_skill_id: 3854
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 19
          }
          children {
            behavior {
              enemy_skill_id: 3869
            }
          }
        }
      }
    }
  }
