  monster_id: 102996
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 17107
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            behavior {
              enemy_skill_id: 16628
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 50
            trigger_turn: 1
            always_trigger_above: 9
          }
          children {
            behavior {
              enemy_skill_id: 16631
            }
          }
          children {
            behavior {
              enemy_skill_id: 16628
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 9
          }
          children {
            behavior {
              enemy_skill_id: 16632
            }
          }
        }
      }
    }
  }
