  monster_id: 102965
  levels {
    level: 4
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        group {
          condition {
            repeats_every: 4
            trigger_turn: 1
          }
          children {
            behavior {
              enemy_skill_id: 4710
            }
          }
        }
      }
      children {
        group {
          condition {
            repeats_every: 4
            trigger_turn: 2
            trigger_turn_end: 4
          }
          children {
            behavior {
              enemy_skill_id: 4711
            }
          }
        }
      }
    }
  }
