  monster_id: 102941
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 8233
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 101
          }
          children {
            behavior {
              enemy_skill_id: 5191
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 99
          }
          children {
            behavior {
              condition {
                use_chance: 50
              }
              enemy_skill_id: 5197
            }
          }
          children {
            behavior {
              enemy_skill_id: 5198
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 79
            trigger_turn: 1
            always_trigger_above: 59
          }
          children {
            behavior {
              enemy_skill_id: 5193
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 59
            trigger_turn: 1
            always_trigger_above: 49
          }
          children {
            behavior {
              enemy_skill_id: 5202
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 49
          }
          children {
            group {
              condition {
                trigger_turn: 1
                always_trigger_above: 19
              }
              children {
                behavior {
                  enemy_skill_id: 5206
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 2
                always_trigger_above: 39
              }
              children {
                behavior {
                  enemy_skill_id: 5202
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 39
            trigger_turn: 2
            always_trigger_above: 19
          }
          children {
            behavior {
              enemy_skill_id: 5203
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 19
          }
          children {
            behavior {
              enemy_skill_id: 5196
            }
          }
        }
      }
    }
    groups {
      group_type: UNKNOWN_USE
      children {
        behavior {
          condition {
            limited_execution: 5
          }
          enemy_skill_id: 5204
        }
      }
      children {
        behavior {
          condition {
            limited_execution: 7
          }
          enemy_skill_id: 5194
        }
      }
      children {
        behavior {
          condition {
            limited_execution: 15
          }
          enemy_skill_id: 5195
        }
      }
    }
  }
