  monster_id: 103575
  levels {
    level: 1
    groups {
      group_type: PASSIVE
      children {
        behavior {
          enemy_skill_id: 6786
        }
      }
      children {
        behavior {
          enemy_skill_id: 12175
        }
      }
    }
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 6766
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            behavior {
              condition {
                use_chance: 40
              }
              enemy_skill_id: 6780
            }
          }
          children {
            behavior {
              condition {
                use_chance: 20
              }
              enemy_skill_id: 6781
            }
          }
          children {
            behavior {
              condition {
                use_chance: 40
              }
              enemy_skill_id: 6782
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 79
            trigger_turn: 1
            always_trigger_above: 19
          }
          children {
            behavior {
              condition {
                use_chance: 34
              }
              enemy_skill_id: 6771
            }
          }
          children {
            behavior {
              condition {
                use_chance: 33
              }
              enemy_skill_id: 6772
            }
          }
          children {
            behavior {
              condition {
                use_chance: 33
              }
              enemy_skill_id: 6773
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 49
            trigger_turn: 2
            always_trigger_above: 19
          }
          children {
            behavior {
              enemy_skill_id: 6775
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 29
            trigger_turn: 3
            always_trigger_above: 19
          }
          children {
            behavior {
              enemy_skill_id: 6778
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 19
          }
          children {
            behavior {
              enemy_skill_id: 6785
            }
          }
        }
      }
    }
    groups {
      group_type: UNKNOWN_USE
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 6776
        }
      }
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 6774
        }
      }
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 6779
        }
      }
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 6777
        }
      }
    }
  }
