  monster_id: 103576
  levels {
    level: 1
    groups {
      group_type: PASSIVE
      children {
        behavior {
          enemy_skill_id: 6922
        }
      }
      children {
        behavior {
          enemy_skill_id: 12175
        }
      }
    }
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 6889
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            group {
              condition {
                trigger_turn: 1
                always_trigger_above: 14
              }
              children {
                behavior {
                  enemy_skill_id: 6892
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 2
                always_trigger_above: 14
              }
              children {
                behavior {
                  enemy_skill_id: 6895
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 3
                always_trigger_above: 14
              }
              children {
                behavior {
                  enemy_skill_id: 6898
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 4
                always_trigger_above: 14
              }
              children {
                behavior {
                  enemy_skill_id: 6901
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 5
                always_trigger_above: 14
              }
              children {
                behavior {
                  enemy_skill_id: 6904
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 6
                always_trigger_above: 14
              }
              children {
                behavior {
                  enemy_skill_id: 6905
                }
              }
              children {
                behavior {
                  enemy_skill_id: 6906
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 7
                always_trigger_above: 14
              }
              children {
                behavior {
                  enemy_skill_id: 6910
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 8
                always_trigger_above: 14
              }
              children {
                behavior {
                  enemy_skill_id: 6913
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 9
                always_trigger_above: 14
              }
              children {
                behavior {
                  enemy_skill_id: 6916
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  condition {
                    use_chance: 45
                  }
                  enemy_skill_id: 6917
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 40
                  }
                  enemy_skill_id: 6918
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 15
                  }
                  enemy_skill_id: 6919
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 14
          }
          children {
            behavior {
              enemy_skill_id: 6921
            }
          }
        }
      }
    }
  }
