  monster_id: 103722
  levels {
    level: 1
    groups {
      group_type: PASSIVE
      children {
        behavior {
          enemy_skill_id: 8208
        }
      }
    }
  }
  levels {
    level: 4
    groups {
      group_type: PASSIVE
      children {
        behavior {
          enemy_skill_id: 8208
        }
      }
    }
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 7487
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            group {
              condition {
                trigger_turn: 1
                always_trigger_above: 19
              }
              children {
                behavior {
                  enemy_skill_id: 7492
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 2
                always_trigger_above: 19
              }
              children {
                behavior {
                  enemy_skill_id: 7495
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 3
                always_trigger_above: 19
              }
              children {
                behavior {
                  enemy_skill_id: 7496
                }
              }
              children {
                behavior {
                  enemy_skill_id: 7497
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 4
                always_trigger_above: 19
              }
              children {
                behavior {
                  enemy_skill_id: 7495
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 5
                always_trigger_above: 19
              }
              children {
                behavior {
                  enemy_skill_id: 7493
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 8
                trigger_turn: 1
              }
              children {
                behavior {
                  enemy_skill_id: 7496
                }
              }
              children {
                behavior {
                  enemy_skill_id: 7497
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 8
                trigger_turn: 2
              }
              children {
                behavior {
                  enemy_skill_id: 7495
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 8
                trigger_turn: 3
              }
              children {
                behavior {
                  enemy_skill_id: 7496
                }
              }
              children {
                behavior {
                  enemy_skill_id: 7497
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 8
                trigger_turn: 4
              }
              children {
                behavior {
                  enemy_skill_id: 7494
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 8
                trigger_turn: 5
              }
              children {
                behavior {
                  enemy_skill_id: 7495
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 8
                trigger_turn: 6
              }
              children {
                behavior {
                  enemy_skill_id: 7496
                }
              }
              children {
                behavior {
                  enemy_skill_id: 7497
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 8
                trigger_turn: 7
              }
              children {
                behavior {
                  enemy_skill_id: 7495
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 8
                trigger_turn: 8
              }
              children {
                behavior {
                  enemy_skill_id: 7494
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 19
          }
          children {
            group {
              condition {
                trigger_turn: 1
              }
              children {
                behavior {
                  enemy_skill_id: 7498
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  enemy_skill_id: 7499
                }
              }
            }
          }
        }
      }
    }
  }
