  monster_id: 103723
  levels {
    level: 1
    groups {
      group_type: PASSIVE
      children {
        behavior {
          enemy_skill_id: 8209
        }
      }
    }
  }
  levels {
    level: 4
    groups {
      group_type: PASSIVE
      children {
        behavior {
          enemy_skill_id: 8209
        }
      }
    }
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 7545
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 101
          }
          children {
            group {
              condition {
                trigger_turn: 1
              }
              children {
                behavior {
                  enemy_skill_id: 7548
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 2
                always_trigger_above: 19
              }
              children {
                behavior {
                  enemy_skill_id: 7553
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 3
                always_trigger_above: 19
              }
              children {
                behavior {
                  enemy_skill_id: 7554
                }
              }
              children {
                behavior {
                  enemy_skill_id: 7555
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 4
                always_trigger_above: 19
              }
              children {
                behavior {
                  enemy_skill_id: 7553
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 5
                always_trigger_above: 19
              }
              children {
                behavior {
                  enemy_skill_id: 7551
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 8
                trigger_turn: 1
              }
              children {
                behavior {
                  enemy_skill_id: 7554
                }
              }
              children {
                behavior {
                  enemy_skill_id: 7555
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 8
                trigger_turn: 2
              }
              children {
                behavior {
                  enemy_skill_id: 7553
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 8
                trigger_turn: 3
              }
              children {
                behavior {
                  enemy_skill_id: 7554
                }
              }
              children {
                behavior {
                  enemy_skill_id: 7555
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 8
                trigger_turn: 4
              }
              children {
                behavior {
                  enemy_skill_id: 7552
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 8
                trigger_turn: 5
              }
              children {
                behavior {
                  enemy_skill_id: 7553
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 8
                trigger_turn: 6
              }
              children {
                behavior {
                  enemy_skill_id: 7554
                }
              }
              children {
                behavior {
                  enemy_skill_id: 7555
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 8
                trigger_turn: 7
              }
              children {
                behavior {
                  enemy_skill_id: 7553
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 8
                trigger_turn: 8
              }
              children {
                behavior {
                  enemy_skill_id: 7552
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 99
            trigger_turn: 1
            always_trigger_above: 19
          }
          children {
            behavior {
              enemy_skill_id: 7550
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 19
          }
          children {
            group {
              condition {
                trigger_turn: 1
              }
              children {
                behavior {
                  enemy_skill_id: 7556
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  enemy_skill_id: 7557
                }
              }
            }
          }
        }
      }
    }
  }
