  monster_id: 103881
  levels {
    level: 1
    groups {
      group_type: PASSIVE
      children {
        behavior {
          enemy_skill_id: 8241
        }
      }
    }
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 8038
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: MONSTER_STATUS
          children {
            behavior {
              enemy_skill_id: 8042
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            group {
              condition {
                trigger_turn: 1
                trigger_turn_end: 4
                always_trigger_above: 4
              }
              children {
                behavior {
                  condition {
                    use_chance: 33
                  }
                  enemy_skill_id: 8043
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 50
                  }
                  enemy_skill_id: 8044
                }
              }
              children {
                behavior {
                  enemy_skill_id: 8045
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 5
                always_trigger_above: 4
              }
              children {
                behavior {
                  enemy_skill_id: 8041
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 6
                trigger_turn_end: 11
                always_trigger_above: 4
              }
              children {
                behavior {
                  condition {
                    use_chance: 33
                  }
                  enemy_skill_id: 8043
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 50
                  }
                  enemy_skill_id: 8044
                }
              }
              children {
                behavior {
                  enemy_skill_id: 8045
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 12
                always_trigger_above: 4
              }
              children {
                behavior {
                  enemy_skill_id: 8049
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  condition {
                    use_chance: 33
                  }
                  enemy_skill_id: 8043
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 50
                  }
                  enemy_skill_id: 8044
                }
              }
              children {
                behavior {
                  enemy_skill_id: 8045
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 4
          }
          children {
            behavior {
              enemy_skill_id: 8046
            }
          }
        }
      }
    }
  }
