  monster_id: 103973
  levels {
    level: 9
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        behavior {
          enemy_skill_id: 9388
        }
      }
    }
  }
