  monster_id: 104211
  levels {
    level: 4
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 9207
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        group {
          condition {
            repeats_every: 3
            trigger_turn: 1
            trigger_turn_end: 2
          }
          children {
            behavior {
              enemy_skill_id: 8995
            }
          }
        }
      }
      children {
        group {
          condition {
            repeats_every: 3
            trigger_turn: 3
          }
          children {
            behavior {
              enemy_skill_id: 9208
            }
          }
        }
      }
    }
  }
