  monster_id: 104724
  levels {
    level: 4
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 10693
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        behavior {
          condition {
            use_chance: 10
          }
          enemy_skill_id: 10644
        }
      }
      children {
        behavior {
          condition {
            use_chance: 10
          }
          enemy_skill_id: 10645
        }
      }
      children {
        behavior {
          enemy_skill_id: 10693
        }
      }
    }
  }
