  monster_id: 104833
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 17195
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
            repeats_every: 7
            trigger_turn: 1
            trigger_turn_end: 7
          }
          children {
            behavior {
              enemy_skill_id: 11316
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 95
            repeats_every: 7
            trigger_turn: 1
            trigger_turn_end: 7
          }
          children {
            behavior {
              condition {
                use_chance: 17
              }
              enemy_skill_id: 11321
            }
          }
          children {
            behavior {
              condition {
                use_chance: 20
              }
              enemy_skill_id: 11320
            }
          }
          children {
            behavior {
              condition {
                use_chance: 25
              }
              enemy_skill_id: 11319
            }
          }
          children {
            behavior {
              condition {
                use_chance: 33
              }
              enemy_skill_id: 11318
            }
          }
          children {
            behavior {
              condition {
                use_chance: 50
              }
              enemy_skill_id: 11317
            }
          }
          children {
            behavior {
              enemy_skill_id: 11316
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 94
            repeats_every: 7
            trigger_turn: 1
            trigger_turn_end: 7
          }
          children {
            behavior {
              condition {
                use_chance: 50
              }
              enemy_skill_id: 11317
            }
          }
          children {
            behavior {
              enemy_skill_id: 11316
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 89
            repeats_every: 7
            trigger_turn: 1
            trigger_turn_end: 7
          }
          children {
            behavior {
              condition {
                use_chance: 33
              }
              enemy_skill_id: 11318
            }
          }
          children {
            behavior {
              condition {
                use_chance: 50
              }
              enemy_skill_id: 11317
            }
          }
          children {
            behavior {
              enemy_skill_id: 11316
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 84
            repeats_every: 7
            trigger_turn: 1
            trigger_turn_end: 7
          }
          children {
            behavior {
              condition {
                use_chance: 25
              }
              enemy_skill_id: 11319
            }
          }
          children {
            behavior {
              condition {
                use_chance: 33
              }
              enemy_skill_id: 11318
            }
          }
          children {
            behavior {
              condition {
                use_chance: 50
              }
              enemy_skill_id: 11317
            }
          }
          children {
            behavior {
              enemy_skill_id: 11316
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 79
            repeats_every: 7
            trigger_turn: 1
            trigger_turn_end: 7
          }
          children {
            behavior {
              condition {
                use_chance: 20
              }
              enemy_skill_id: 11320
            }
          }
          children {
            behavior {
              condition {
                use_chance: 25
              }
              enemy_skill_id: 11319
            }
          }
          children {
            behavior {
              condition {
                use_chance: 33
              }
              enemy_skill_id: 11318
            }
          }
          children {
            behavior {
              condition {
                use_chance: 50
              }
              enemy_skill_id: 11317
            }
          }
          children {
            behavior {
              enemy_skill_id: 11316
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 74
            repeats_every: 7
            trigger_turn: 1
            trigger_turn_end: 7
          }
          children {
            behavior {
              condition {
                use_chance: 17
              }
              enemy_skill_id: 11321
            }
          }
          children {
            behavior {
              condition {
                use_chance: 20
              }
              enemy_skill_id: 11320
            }
          }
          children {
            behavior {
              condition {
                use_chance: 25
              }
              enemy_skill_id: 11319
            }
          }
          children {
            behavior {
              condition {
                use_chance: 33
              }
              enemy_skill_id: 11318
            }
          }
          children {
            behavior {
              condition {
                use_chance: 50
              }
              enemy_skill_id: 11317
            }
          }
          children {
            behavior {
              enemy_skill_id: 11316
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 49
          }
          children {
            group {
              condition {
                trigger_turn: 1
                always_trigger_above: 19
              }
              children {
                behavior {
                  enemy_skill_id: 11329
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 2
                trigger_turn_end: 14
                always_trigger_above: 19
              }
              children {
                behavior {
                  condition {
                    use_chance: 17
                  }
                  enemy_skill_id: 11321
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 20
                  }
                  enemy_skill_id: 11320
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 25
                  }
                  enemy_skill_id: 11319
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 33
                  }
                  enemy_skill_id: 11318
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 50
                  }
                  enemy_skill_id: 11317
                }
              }
              children {
                behavior {
                  enemy_skill_id: 11316
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 15
                always_trigger_above: 19
              }
              children {
                behavior {
                  enemy_skill_id: 11403
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  condition {
                    use_chance: 17
                  }
                  enemy_skill_id: 11321
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 20
                  }
                  enemy_skill_id: 11320
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 25
                  }
                  enemy_skill_id: 11319
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 33
                  }
                  enemy_skill_id: 11318
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 50
                  }
                  enemy_skill_id: 11317
                }
              }
              children {
                behavior {
                  enemy_skill_id: 11316
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 19
          }
          children {
            group {
              condition {
                trigger_turn: 1
              }
              children {
                behavior {
                  enemy_skill_id: 11332
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  enemy_skill_id: 11335
                }
              }
            }
          }
        }
      }
    }
  }
