  monster_id: 104895
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 15545
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            behavior {
              condition {
                use_chance: 20
              }
              enemy_skill_id: 15549
            }
          }
          children {
            behavior {
              condition {
                use_chance: 20
              }
              enemy_skill_id: 15550
            }
          }
          children {
            behavior {
              condition {
                use_chance: 20
              }
              enemy_skill_id: 15551
            }
          }
          children {
            behavior {
              condition {
                use_chance: 20
              }
              enemy_skill_id: 15552
            }
          }
          children {
            behavior {
              condition {
                use_chance: 20
              }
              enemy_skill_id: 15553
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 50
            trigger_turn: 1
          }
          children {
            behavior {
              condition {
                use_chance: 20
              }
              enemy_skill_id: 15554
            }
          }
          children {
            behavior {
              condition {
                use_chance: 25
              }
              enemy_skill_id: 15555
            }
          }
          children {
            behavior {
              condition {
                use_chance: 33
              }
              enemy_skill_id: 15556
            }
          }
          children {
            behavior {
              condition {
                use_chance: 50
              }
              enemy_skill_id: 15557
            }
          }
          children {
            behavior {
              enemy_skill_id: 15558
            }
          }
        }
      }
    }
  }
