  monster_id: 104963
  levels {
    level: 4
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 12060
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            behavior {
              condition {
                use_chance: 40
              }
              enemy_skill_id: 11891
            }
          }
          children {
            behavior {
              condition {
                use_chance: 40
              }
              enemy_skill_id: 11892
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 14
          }
          children {
            behavior {
              enemy_skill_id: 11894
            }
          }
        }
      }
    }
    groups {
      group_type: REMAINING
      condition {
        hp_threshold: 100
        trigger_enemies_remaining: 1
        trigger_turn: 1
        always_trigger_above: 14
      }
      children {
        behavior {
          enemy_skill_id: 12061
        }
      }
    }
  }
