  monster_id: 105016
  levels {
    level: 4
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 12234
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        group {
          condition {
            repeats_every: 7
            trigger_turn: 1
            trigger_turn_end: 6
          }
          children {
            behavior {
              condition {
                use_chance: 50
              }
              enemy_skill_id: 12235
            }
          }
          children {
            behavior {
              condition {
                use_chance: 50
              }
              enemy_skill_id: 12196
            }
          }
        }
      }
      children {
        group {
          condition {
            repeats_every: 7
            trigger_turn: 7
          }
          children {
            behavior {
              enemy_skill_id: 12197
            }
          }
        }
      }
    }
  }
