  monster_id: 105471
  levels {
    level: 2
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 14111
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            behavior {
              condition {
                use_chance: 33
              }
              enemy_skill_id: 14115
            }
          }
          children {
            behavior {
              condition {
                use_chance: 33
              }
              enemy_skill_id: 14116
            }
          }
          children {
            behavior {
              condition {
                use_chance: 34
              }
              enemy_skill_id: 14117
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 50
            trigger_turn: 1
          }
          children {
            behavior {
              enemy_skill_id: 14112
            }
          }
        }
      }
    }
  }
  levels {
    level: 4
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 14153
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            behavior {
              condition {
                use_chance: 33
              }
              enemy_skill_id: 14132
            }
          }
          children {
            behavior {
              condition {
                use_chance: 33
              }
              enemy_skill_id: 14133
            }
          }
          children {
            behavior {
              condition {
                use_chance: 34
              }
              enemy_skill_id: 14134
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 50
            trigger_turn: 1
            always_trigger_above: 1
          }
          children {
            behavior {
              enemy_skill_id: 14135
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 20
          }
          children {
            behavior {
              enemy_skill_id: 14136
            }
          }
        }
      }
    }
  }
