  monster_id: 105605
  levels {
    level: 4
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 14716
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            group {
              condition {
                repeats_every: 5
                trigger_turn: 1
              }
              children {
                behavior {
                  enemy_skill_id: 14695
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 5
                trigger_turn: 2
              }
              children {
                behavior {
                  enemy_skill_id: 14696
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 5
                trigger_turn: 3
              }
              children {
                behavior {
                  enemy_skill_id: 14697
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 5
                trigger_turn: 4
              }
              children {
                behavior {
                  enemy_skill_id: 14698
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 5
                trigger_turn: 5
              }
              children {
                behavior {
                  enemy_skill_id: 14699
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 19
          }
          children {
            behavior {
              condition {
                use_chance: 50
                limited_execution: 3
              }
              enemy_skill_id: 14706
            }
          }
          children {
            behavior {
              enemy_skill_id: 14705
            }
          }
        }
      }
    }
  }
