  monster_id: 1074
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 11646
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        behavior {
          condition {
            trigger_combos: 9
          }
          enemy_skill_id: 11883
        }
      }
      children {
        behavior {
          enemy_skill_id: 11886
        }
      }
    }
  }
  levels {
    level: 6
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 11879
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        behavior {
          condition {
            trigger_combos: 10
          }
          enemy_skill_id: 11883
        }
      }
      children {
        behavior {
          enemy_skill_id: 11886
        }
      }
    }
  }
