  monster_id: 1084
  levels {
    level: 5
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 907
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        behavior {
          enemy_skill_id: 47
        }
      }
      children {
        behavior {
          enemy_skill_id: 46
        }
      }
    }
  }
