  monster_id: 109
  levels {
    level: 1
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 74
      }
      children {
        behavior {
          condition {
            use_chance: 30
          }
          enemy_skill_id: 75
        }
      }
    }
  }
