  monster_id: 1116
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 7826
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        group {
          condition {
            repeats_every: 6
            trigger_turn: 1
          }
          children {
            behavior {
              enemy_skill_id: 7827
            }
          }
          children {
            behavior {
              enemy_skill_id: 7828
            }
          }
        }
      }
      children {
        group {
          condition {
            repeats_every: 6
            trigger_turn: 2
          }
          children {
            behavior {
              enemy_skill_id: 7827
            }
          }
        }
      }
      children {
        group {
          condition {
            repeats_every: 6
            trigger_turn: 3
          }
          children {
            behavior {
              enemy_skill_id: 7827
            }
          }
          children {
            behavior {
              enemy_skill_id: 7828
            }
          }
        }
      }
      children {
        group {
          condition {
            repeats_every: 6
            trigger_turn: 4
          }
          children {
            behavior {
              enemy_skill_id: 7827
            }
          }
        }
      }
      children {
        group {
          condition {
            repeats_every: 6
            trigger_turn: 5
          }
          children {
            behavior {
              enemy_skill_id: 7827
            }
          }
          children {
            behavior {
              enemy_skill_id: 7828
            }
          }
        }
      }
      children {
        group {
          condition {
            repeats_every: 6
            trigger_turn: 6
          }
          children {
            behavior {
              enemy_skill_id: 7831
            }
          }
        }
      }
    }
  }
