  monster_id: 1149
  levels {
    level: 5
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 895
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
            repeats_every: 2
            trigger_turn: 1
          }
          children {
            behavior {
              condition {
                use_chance: 30
              }
              enemy_skill_id: 897
            }
          }
          children {
            behavior {
              condition {
                use_chance: 40
              }
              enemy_skill_id: 898
            }
          }
          children {
            behavior {
              condition {
                use_chance: 30
              }
              enemy_skill_id: 900
            }
          }
          children {
            behavior {
              condition {
                use_chance: 30
              }
              enemy_skill_id: 901
            }
          }
          children {
            behavior {
              enemy_skill_id: 896
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 49
            repeats_every: 2
            trigger_turn: 1
          }
          children {
            behavior {
              condition {
                use_chance: 30
              }
              enemy_skill_id: 897
            }
          }
          children {
            behavior {
              condition {
                use_chance: 40
              }
              enemy_skill_id: 898
            }
          }
          children {
            behavior {
              condition {
                use_chance: 10
              }
              enemy_skill_id: 899
            }
          }
          children {
            behavior {
              condition {
                use_chance: 30
              }
              enemy_skill_id: 900
            }
          }
          children {
            behavior {
              condition {
                use_chance: 30
              }
              enemy_skill_id: 901
            }
          }
          children {
            behavior {
              enemy_skill_id: 896
            }
          }
        }
      }
    }
  }
