  monster_id: 1166
  levels {
    level: 5
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 205
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            group {
              condition {
                repeats_every: 2
                trigger_turn: 1
              }
              children {
                behavior {
                  enemy_skill_id: 902
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 2
                trigger_turn: 2
              }
              children {
                behavior {
                  enemy_skill_id: 914
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 49
          }
          children {
            group {
              condition {
                repeats_every: 5
                trigger_turn: 1
              }
              children {
                behavior {
                  enemy_skill_id: 915
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 5
                trigger_turn: 2
              }
              children {
                behavior {
                  enemy_skill_id: 916
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 5
                trigger_turn: 3
              }
              children {
                behavior {
                  enemy_skill_id: 917
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 5
                trigger_turn: 4
              }
              children {
                behavior {
                  enemy_skill_id: 918
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 5
                trigger_turn: 5
              }
              children {
                behavior {
                  enemy_skill_id: 919
                }
              }
            }
          }
        }
      }
    }
  }
