  monster_id: 1185
  levels {
    level: 5
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 903
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            behavior {
              condition {
                use_chance: 50
              }
              enemy_skill_id: 961
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 49
          }
          children {
            group {
              condition {
                repeats_every: 2
                trigger_turn: 1
              }
              children {
                behavior {
                  enemy_skill_id: 948
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 2
                trigger_turn: 2
              }
              children {
                behavior {
                  enemy_skill_id: 960
                }
              }
            }
          }
        }
      }
    }
  }
