  monster_id: 1189
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 934
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            group {
              condition {
                repeats_every: 2
                trigger_turn: 1
              }
              children {
                behavior {
                  condition {
                    use_chance: 70
                  }
                  enemy_skill_id: 933
                }
              }
              children {
                behavior {
                  enemy_skill_id: 932
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 2
                trigger_turn: 2
              }
              children {
                behavior {
                  condition {
                    use_chance: 70
                  }
                  enemy_skill_id: 933
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 49
          }
          children {
            group {
              condition {
                repeats_every: 2
                trigger_turn: 1
              }
              children {
                behavior {
                  condition {
                    use_chance: 70
                  }
                  enemy_skill_id: 935
                }
              }
              children {
                behavior {
                  enemy_skill_id: 932
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 2
                trigger_turn: 2
              }
              children {
                behavior {
                  condition {
                    use_chance: 70
                  }
                  enemy_skill_id: 935
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 29
          }
          children {
            behavior {
              enemy_skill_id: 327
            }
          }
        }
      }
    }
  }
