  monster_id: 1200
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 18295
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            group {
              condition {
                repeats_every: 3
                trigger_turn: 1
                trigger_turn_end: 2
              }
              children {
                behavior {
                  enemy_skill_id: 18297
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 3
                trigger_turn: 3
              }
              children {
                behavior {
                  enemy_skill_id: 18298
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 49
            trigger_turn: 1
          }
          children {
            behavior {
              enemy_skill_id: 18296
            }
          }
        }
      }
    }
  }
