  monster_id: 1225
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 1410
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        group {
          condition {
            repeats_every: 5
            trigger_turn: 1
          }
          children {
            behavior {
              enemy_skill_id: 1411
            }
          }
        }
      }
      children {
        group {
          condition {
            repeats_every: 5
            trigger_turn: 2
          }
          children {
            behavior {
              enemy_skill_id: 1412
            }
          }
        }
      }
      children {
        group {
          condition {
            repeats_every: 5
            trigger_turn: 3
          }
          children {
            behavior {
              enemy_skill_id: 1413
            }
          }
        }
      }
      children {
        group {
          condition {
            repeats_every: 5
            trigger_turn: 4
          }
          children {
            behavior {
              enemy_skill_id: 1414
            }
          }
        }
      }
      children {
        group {
          condition {
            repeats_every: 5
            trigger_turn: 5
          }
          children {
            behavior {
              enemy_skill_id: 1415
            }
          }
        }
      }
    }
  }
