  monster_id: 1267
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 2524
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        group {
          condition {
            repeats_every: 4
            trigger_turn: 1
          }
          children {
            behavior {
              enemy_skill_id: 2520
            }
          }
        }
      }
      children {
        group {
          condition {
            repeats_every: 4
            trigger_turn: 2
          }
          children {
            behavior {
              enemy_skill_id: 2521
            }
          }
        }
      }
      children {
        group {
          condition {
            repeats_every: 4
            trigger_turn: 3
          }
          children {
            behavior {
              enemy_skill_id: 2522
            }
          }
        }
      }
      children {
        group {
          condition {
            repeats_every: 4
            trigger_turn: 4
          }
          children {
            behavior {
              enemy_skill_id: 2523
            }
          }
        }
      }
    }
  }
