  monster_id: 1269
  levels {
    level: 4
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 9035
        }
      }
      children {
        behavior {
          enemy_skill_id: 9027
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        group {
          condition {
            repeats_every: 5
            trigger_turn: 1
            trigger_turn_end: 3
          }
          children {
            behavior {
              condition {
                use_chance: 33
              }
              enemy_skill_id: 9028
            }
          }
          children {
            behavior {
              condition {
                use_chance: 50
              }
              enemy_skill_id: 9029
            }
          }
          children {
            behavior {
              enemy_skill_id: 9030
            }
          }
        }
      }
      children {
        group {
          condition {
            repeats_every: 5
            trigger_turn: 4
          }
          children {
            behavior {
              enemy_skill_id: 9031
            }
          }
        }
      }
      children {
        group {
          condition {
            repeats_every: 5
            trigger_turn: 5
          }
          children {
            behavior {
              enemy_skill_id: 9034
            }
          }
        }
      }
    }
  }
