  monster_id: 1299
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 20226
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        group {
          condition {
            trigger_turn: 1
          }
          children {
            behavior {
              condition {
                use_chance: 50
              }
              enemy_skill_id: 20229
            }
          }
          children {
            behavior {
              enemy_skill_id: 20230
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 2
          }
          children {
            behavior {
              enemy_skill_id: 20231
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 3
          }
          children {
            behavior {
              condition {
                use_chance: 50
              }
              enemy_skill_id: 20229
            }
          }
          children {
            behavior {
              enemy_skill_id: 20230
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 4
          }
          children {
            behavior {
              enemy_skill_id: 20231
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 5
          }
          children {
            behavior {
              condition {
                use_chance: 50
              }
              enemy_skill_id: 20229
            }
          }
          children {
            behavior {
              enemy_skill_id: 20230
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 6
          }
          children {
            behavior {
              enemy_skill_id: 20231
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 7
          }
          children {
            behavior {
              condition {
                use_chance: 50
              }
              enemy_skill_id: 20229
            }
          }
          children {
            behavior {
              enemy_skill_id: 20230
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 8
          }
          children {
            behavior {
              enemy_skill_id: 20231
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 9
          }
          children {
            behavior {
              condition {
                use_chance: 50
              }
              enemy_skill_id: 20229
            }
          }
          children {
            behavior {
              enemy_skill_id: 20230
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 10
          }
          children {
            behavior {
              enemy_skill_id: 20232
            }
          }
        }
      }
      children {
        group {
          condition {
            repeats_every: 2
            trigger_turn: 1
          }
          children {
            behavior {
              condition {
                use_chance: 50
              }
              enemy_skill_id: 20229
            }
          }
          children {
            behavior {
              enemy_skill_id: 20230
            }
          }
        }
      }
      children {
        group {
          condition {
            repeats_every: 2
            trigger_turn: 2
          }
          children {
            behavior {
              enemy_skill_id: 20231
            }
          }
        }
      }
    }
  }
