  monster_id: 1327
  levels {
    level: 1
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        behavior {
          condition {
            use_chance: 20
          }
          enemy_skill_id: 1790
        }
      }
      children {
        behavior {
          condition {
            use_chance: 20
          }
          enemy_skill_id: 1835
        }
      }
    }
    groups {
      group_type: UNKNOWN_USE
      children {
        behavior {
          condition {
            use_chance: 20
          }
          enemy_skill_id: 1786
        }
      }
    }
  }
