  monster_id: 1333
  levels {
    level: 1
    groups {
      group_type: PASSIVE
      children {
        behavior {
          enemy_skill_id: 11862
        }
      }
    }
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 11863
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            group {
              condition {
                trigger_turn: 1
                always_trigger_above: 29
              }
              children {
                behavior {
                  enemy_skill_id: 11866
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  condition {
                    use_chance: 25
                  }
                  enemy_skill_id: 11869
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 25
                  }
                  enemy_skill_id: 11870
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 25
                  }
                  enemy_skill_id: 11871
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 25
                  }
                  enemy_skill_id: 11872
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 29
          }
          children {
            group {
              condition {
                trigger_turn: 1
              }
              children {
                behavior {
                  enemy_skill_id: 11873
                }
              }
              children {
                behavior {
                  enemy_skill_id: 11874
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  enemy_skill_id: 11875
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 1
          }
          children {
            behavior {
              enemy_skill_id: 11876
            }
          }
        }
      }
    }
  }
