  monster_id: 1402
  levels {
    level: 1
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 29
      }
      children {
        behavior {
          enemy_skill_id: 64
        }
      }
    }
  }
