  monster_id: 1421
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 10891
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        group {
          condition {
            trigger_turn: 1
            trigger_turn_end: 4
          }
          children {
            behavior {
              enemy_skill_id: 10892
            }
          }
        }
      }
      children {
        group {
          children {
            behavior {
              enemy_skill_id: 10893
            }
          }
        }
      }
    }
  }
