  monster_id: 1443
  levels {
    level: 5
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 1209
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          condition {
            trigger_turn: 1
            always_trigger_above: 1
          }
          children {
            behavior {
              enemy_skill_id: 1210
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
            repeats_every: 3
            trigger_turn: 1
          }
          children {
            behavior {
              enemy_skill_id: 1211
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 29
          }
          children {
            group {
              condition {
                trigger_turn: 2
              }
              children {
                behavior {
                  enemy_skill_id: 1212
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  enemy_skill_id: 1213
                }
              }
            }
          }
        }
      }
    }
  }
