  monster_id: 1451
  levels {
    level: 1
    groups {
      group_type: STANDARD
      children {
        group {
          condition {
            trigger_turn: 1
            always_trigger_above: 1
          }
          children {
            behavior {
              enemy_skill_id: 1194
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            behavior {
              enemy_skill_id: 1195
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 74
            trigger_turn: 2
            always_trigger_above: 29
          }
          children {
            behavior {
              enemy_skill_id: 1193
            }
          }
          children {
            behavior {
              enemy_skill_id: 1195
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 29
          }
          children {
            group {
              condition {
                trigger_turn: 2
              }
              children {
                behavior {
                  enemy_skill_id: 1193
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  enemy_skill_id: 1196
                }
              }
            }
          }
        }
      }
    }
  }
  levels {
    level: 5
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 1194
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            behavior {
              enemy_skill_id: 1195
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 74
            trigger_turn: 1
            always_trigger_above: 29
          }
          children {
            behavior {
              enemy_skill_id: 1193
            }
          }
          children {
            behavior {
              enemy_skill_id: 1195
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 29
          }
          children {
            group {
              condition {
                trigger_turn: 1
              }
              children {
                behavior {
                  enemy_skill_id: 1193
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  enemy_skill_id: 1196
                }
              }
            }
          }
        }
      }
    }
  }
