  monster_id: 1470
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 4437
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        group {
          condition {
            trigger_turn: 1
          }
          children {
            behavior {
              enemy_skill_id: 4436
            }
          }
        }
      }
      children {
        group {
          children {
            behavior {
              enemy_skill_id: 4439
            }
          }
        }
      }
    }
  }
