  monster_id: 153
  levels {
    level: 5
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        group {
          condition {
            trigger_turn: 1
          }
          children {
            behavior {
              enemy_skill_id: 802
            }
          }
        }
      }
      children {
        group {
          children {
            behavior {
              enemy_skill_id: 801
            }
          }
        }
      }
    }
  }
