  monster_id: 1595
  levels {
    level: 5
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 1503
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        group {
          condition {
            trigger_turn: 1
          }
          children {
            behavior {
              enemy_skill_id: 1675
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 2
          }
          children {
            behavior {
              enemy_skill_id: 1676
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 3
          }
          children {
            behavior {
              enemy_skill_id: 1675
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 4
          }
          children {
            behavior {
              enemy_skill_id: 1677
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 5
          }
          children {
            behavior {
              enemy_skill_id: 1675
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 6
          }
          children {
            behavior {
              enemy_skill_id: 1678
            }
          }
        }
      }
      children {
        group {
          children {
            behavior {
              enemy_skill_id: 1679
            }
          }
        }
      }
    }
  }
  levels {
    level: 10
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 1504
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        group {
          condition {
            trigger_turn: 1
          }
          children {
            behavior {
              enemy_skill_id: 1675
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 2
          }
          children {
            behavior {
              enemy_skill_id: 1676
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 3
          }
          children {
            behavior {
              enemy_skill_id: 1675
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 4
          }
          children {
            behavior {
              enemy_skill_id: 1677
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 5
          }
          children {
            behavior {
              enemy_skill_id: 1675
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 6
          }
          children {
            behavior {
              enemy_skill_id: 1678
            }
          }
        }
      }
      children {
        group {
          children {
            behavior {
              enemy_skill_id: 1679
            }
          }
        }
      }
    }
  }
