  monster_id: 1604
  levels {
    level: 5
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            behavior {
              enemy_skill_id: 1498
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 79
          }
          children {
            group {
              condition {
                repeats_every: 3
                trigger_turn: 1
              }
              children {
                behavior {
                  enemy_skill_id: 1499
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 3
                trigger_turn: 2
                trigger_turn_end: 3
              }
              children {
                behavior {
                  enemy_skill_id: 1498
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 74
            trigger_turn: 1
            always_trigger_above: 1
          }
          children {
            behavior {
              enemy_skill_id: 1500
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 49
          }
          children {
            group {
              condition {
                repeats_every: 3
                trigger_turn: 1
              }
              children {
                behavior {
                  condition {
                    use_chance: 75
                  }
                  enemy_skill_id: 1501
                }
              }
              children {
                behavior {
                  enemy_skill_id: 1499
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 3
                trigger_turn: 2
                trigger_turn_end: 3
              }
              children {
                behavior {
                  condition {
                    use_chance: 75
                  }
                  enemy_skill_id: 1501
                }
              }
              children {
                behavior {
                  enemy_skill_id: 1498
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 29
          }
          children {
            group {
              condition {
                repeats_every: 3
                trigger_turn: 1
              }
              children {
                behavior {
                  condition {
                    use_chance: 75
                  }
                  enemy_skill_id: 1501
                }
              }
              children {
                behavior {
                  enemy_skill_id: 1499
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 3
                trigger_turn: 2
              }
              children {
                behavior {
                  condition {
                    use_chance: 75
                  }
                  enemy_skill_id: 1501
                }
              }
              children {
                behavior {
                  enemy_skill_id: 1498
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 3
                trigger_turn: 3
              }
              children {
                behavior {
                  enemy_skill_id: 1502
                }
              }
            }
          }
        }
      }
    }
  }
