  monster_id: 1625
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 13395
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          condition {
            trigger_turn: 1
            always_trigger_above: 1
          }
          children {
            behavior {
              enemy_skill_id: 13397
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            group {
              condition {
                trigger_turn: 2
                trigger_turn_end: 11
                always_trigger_above: 19
              }
              children {
                behavior {
                  enemy_skill_id: 13364
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 33
                  }
                  enemy_skill_id: 13365
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 33
                  }
                  enemy_skill_id: 13366
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 34
                  }
                  enemy_skill_id: 13367
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 12
                always_trigger_above: 19
              }
              children {
                behavior {
                  enemy_skill_id: 13358
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  enemy_skill_id: 13368
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 19
            trigger_turn: 2
          }
          children {
            behavior {
              enemy_skill_id: 13358
            }
          }
        }
      }
    }
  }
  levels {
    level: 6
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 13357
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          condition {
            trigger_turn: 1
            always_trigger_above: 1
          }
          children {
            behavior {
              enemy_skill_id: 13361
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            group {
              condition {
                trigger_turn: 2
                trigger_turn_end: 11
                always_trigger_above: 19
              }
              children {
                behavior {
                  enemy_skill_id: 13364
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 33
                  }
                  enemy_skill_id: 13365
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 33
                  }
                  enemy_skill_id: 13366
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 34
                  }
                  enemy_skill_id: 13367
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 12
                always_trigger_above: 19
              }
              children {
                behavior {
                  enemy_skill_id: 13358
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  enemy_skill_id: 13368
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 19
            trigger_turn: 2
          }
          children {
            behavior {
              enemy_skill_id: 13358
            }
          }
        }
      }
    }
  }
