  monster_id: 1646
  levels {
    level: 1
    groups {
      group_type: PASSIVE
      children {
        behavior {
          enemy_skill_id: 6158
        }
      }
    }
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 6177
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            behavior {
              enemy_skill_id: 6180
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 49
          }
          children {
            group {
              condition {
                trigger_turn: 1
                always_trigger_above: 1
              }
              children {
                behavior {
                  enemy_skill_id: 6179
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 2
                always_trigger_above: 1
              }
              children {
                behavior {
                  enemy_skill_id: 6161
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  condition {
                    use_chance: 33
                  }
                  enemy_skill_id: 6165
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 50
                  }
                  enemy_skill_id: 6166
                }
              }
              children {
                behavior {
                  enemy_skill_id: 6167
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 32
            trigger_turn: 3
            always_trigger_above: 4
          }
          children {
            behavior {
              enemy_skill_id: 6181
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 15
            trigger_turn: 4
            always_trigger_above: 4
          }
          children {
            behavior {
              enemy_skill_id: 6182
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 4
          }
          children {
            behavior {
              enemy_skill_id: 6163
            }
          }
        }
      }
    }
  }
  levels {
    level: 10
    groups {
      group_type: PASSIVE
      children {
        behavior {
          enemy_skill_id: 6158
        }
      }
    }
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 6176
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            behavior {
              enemy_skill_id: 6180
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 49
          }
          children {
            group {
              condition {
                trigger_turn: 1
                always_trigger_above: 1
              }
              children {
                behavior {
                  enemy_skill_id: 6179
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 2
                always_trigger_above: 1
              }
              children {
                behavior {
                  enemy_skill_id: 6161
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  condition {
                    use_chance: 33
                  }
                  enemy_skill_id: 6165
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 50
                  }
                  enemy_skill_id: 6166
                }
              }
              children {
                behavior {
                  enemy_skill_id: 6167
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 32
            trigger_turn: 3
            always_trigger_above: 4
          }
          children {
            behavior {
              enemy_skill_id: 6181
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 15
            trigger_turn: 4
            always_trigger_above: 4
          }
          children {
            behavior {
              enemy_skill_id: 6182
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 4
          }
          children {
            behavior {
              enemy_skill_id: 6163
            }
          }
        }
      }
    }
  }
