  monster_id: 1701
  levels {
    level: 5
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        behavior {
          enemy_skill_id: 1627
        }
      }
    }
  }
