  monster_id: 1849
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 2397
        }
      }
      children {
        behavior {
          enemy_skill_id: 2396
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        group {
          condition {
            repeats_every: 5
            trigger_turn: 1
          }
          children {
            behavior {
              enemy_skill_id: 2398
            }
          }
        }
      }
      children {
        group {
          condition {
            repeats_every: 5
            trigger_turn: 2
          }
          children {
            behavior {
              enemy_skill_id: 2399
            }
          }
        }
      }
      children {
        group {
          condition {
            repeats_every: 5
            trigger_turn: 3
          }
          children {
            behavior {
              enemy_skill_id: 2400
            }
          }
        }
      }
      children {
        group {
          condition {
            repeats_every: 5
            trigger_turn: 4
          }
          children {
            behavior {
              enemy_skill_id: 2401
            }
          }
        }
      }
      children {
        group {
          condition {
            repeats_every: 5
            trigger_turn: 5
          }
          children {
            behavior {
              enemy_skill_id: 2402
            }
          }
        }
      }
    }
  }
