  monster_id: 1916
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 2377
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        group {
          condition {
            repeats_every: 7
            trigger_turn: 1
          }
          children {
            behavior {
              enemy_skill_id: 2378
            }
          }
        }
      }
      children {
        group {
          condition {
            repeats_every: 7
            trigger_turn: 2
          }
          children {
            behavior {
              enemy_skill_id: 2379
            }
          }
        }
      }
      children {
        group {
          condition {
            repeats_every: 7
            trigger_turn: 3
          }
          children {
            behavior {
              enemy_skill_id: 2380
            }
          }
        }
      }
      children {
        group {
          condition {
            repeats_every: 7
            trigger_turn: 4
          }
          children {
            behavior {
              enemy_skill_id: 2381
            }
          }
        }
      }
      children {
        group {
          condition {
            repeats_every: 7
            trigger_turn: 5
          }
          children {
            behavior {
              enemy_skill_id: 2382
            }
          }
        }
      }
      children {
        group {
          condition {
            repeats_every: 7
            trigger_turn: 6
          }
          children {
            behavior {
              enemy_skill_id: 2383
            }
          }
        }
      }
      children {
        group {
          condition {
            repeats_every: 7
            trigger_turn: 7
          }
          children {
            behavior {
              enemy_skill_id: 2384
            }
          }
        }
      }
    }
  }
