  monster_id: 1926
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 22777
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            group {
              condition {
                trigger_turn: 1
                always_trigger_above: 49
              }
              children {
                behavior {
                  enemy_skill_id: 22781
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 4
                trigger_turn: 1
                trigger_turn_end: 3
              }
              children {
                behavior {
                  enemy_skill_id: -1
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 4
                trigger_turn: 4
              }
              children {
                behavior {
                  enemy_skill_id: 22786
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 49
            trigger_turn: 1
          }
          children {
            behavior {
              enemy_skill_id: 22784
            }
          }
        }
      }
    }
  }
