  monster_id: 1955
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 2628
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        group {
          condition {
            trigger_turn: 1
          }
          children {
            behavior {
              enemy_skill_id: 2236
            }
          }
          children {
            behavior {
              enemy_skill_id: 2226
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 2
          }
          children {
            behavior {
              enemy_skill_id: 2236
            }
          }
          children {
            behavior {
              enemy_skill_id: 2227
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 3
          }
          children {
            behavior {
              enemy_skill_id: 2236
            }
          }
          children {
            behavior {
              enemy_skill_id: 2228
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 4
          }
          children {
            behavior {
              enemy_skill_id: 2236
            }
          }
          children {
            behavior {
              enemy_skill_id: 2231
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 5
          }
          children {
            behavior {
              enemy_skill_id: 2236
            }
          }
          children {
            behavior {
              enemy_skill_id: 2234
            }
          }
        }
      }
      children {
        group {
          children {
            behavior {
              enemy_skill_id: 2236
            }
          }
          children {
            behavior {
              enemy_skill_id: 2235
            }
          }
        }
      }
    }
  }
