  monster_id: 200321
  levels {
    level: 2
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        behavior {
          enemy_skill_id: 615
        }
      }
    }
  }
