  monster_id: 200476
  levels {
    level: 1
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            behavior {
              condition {
                use_chance: 37
              }
              enemy_skill_id: 43
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 34
          }
          children {
            behavior {
              condition {
                use_chance: 40
              }
              enemy_skill_id: 199
            }
          }
          children {
            behavior {
              condition {
                use_chance: 37
              }
              enemy_skill_id: 43
            }
          }
        }
      }
    }
  }
