  monster_id: 200548
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 20629
        }
      }
      children {
        behavior {
          enemy_skill_id: 20630
        }
      }
      children {
        behavior {
          enemy_skill_id: 20631
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        behavior {
          enemy_skill_id: 20630
        }
      }
      children {
        behavior {
          enemy_skill_id: 20631
        }
      }
    }
  }
