  monster_id: 200542
  levels {
    level: 1
    groups {
      group_type: PASSIVE
      children {
        behavior {
          enemy_skill_id: 38269
        }
      }
    }
    groups {
      group_type: PREEMPT
      children {
        behavior {
          condition {
            trigger_monsters: 7846
          }
          enemy_skill_id: 38250
        }
      }
      children {
        behavior {
          enemy_skill_id: 38246
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            behavior {
              condition {
                use_chance: 33
              }
              enemy_skill_id: 38260
            }
          }
          children {
            behavior {
              condition {
                use_chance: 50
              }
              enemy_skill_id: 38263
            }
          }
          children {
            behavior {
              enemy_skill_id: 38266
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 49
          }
          children {
            group {
              condition {
                trigger_turn: 1
              }
              children {
                behavior {
                  enemy_skill_id: 38254
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 2
              }
              children {
                behavior {
                  enemy_skill_id: 38257
                }
              }
            }
          }
        }
      }
    }
  }
