  monster_id: 200894
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 19594
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        behavior {
          enemy_skill_id: 19595
        }
      }
    }
  }
