  monster_id: 201077
  levels {
    level: 3
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 4252
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        behavior {
          condition {
            if_attributes_available: true
          }
          enemy_skill_id: 4249
        }
      }
      children {
        behavior {
          enemy_skill_id: 4251
        }
      }
    }
    groups {
      group_type: UNKNOWN_USE
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 4250
        }
      }
    }
  }
