  monster_id: 201075
  levels {
    level: 3
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 4263
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        behavior {
          enemy_skill_id: 4260
        }
      }
      children {
        behavior {
          condition {
            if_attributes_available: true
          }
          enemy_skill_id: 4259
        }
      }
      children {
        behavior {
          enemy_skill_id: 4261
        }
      }
    }
    groups {
      group_type: UNKNOWN_USE
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 4262
        }
      }
    }
  }
