  monster_id: 201216
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 23021
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        group {
          condition {
            trigger_turn: 1
          }
          children {
            behavior {
              enemy_skill_id: 17938
            }
          }
          children {
            behavior {
              enemy_skill_id: 23029
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 2
          }
          children {
            behavior {
              condition {
                trigger_combos: 1
              }
              enemy_skill_id: 17939
            }
          }
          children {
            behavior {
              enemy_skill_id: 23030
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 3
          }
          children {
            behavior {
              enemy_skill_id: 17940
            }
          }
          children {
            behavior {
              enemy_skill_id: 17937
            }
          }
        }
      }
      children {
        group {
          children {
            behavior {
              enemy_skill_id: 17939
            }
          }
        }
      }
    }
  }
