  monster_id: 2012
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 23735
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        group {
          condition {
            trigger_turn: 1
          }
          children {
            behavior {
              enemy_skill_id: 23798
            }
          }
          children {
            behavior {
              enemy_skill_id: 23739
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 2
          }
          children {
            behavior {
              enemy_skill_id: 23740
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 3
          }
          children {
            behavior {
              enemy_skill_id: 23741
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 4
          }
          children {
            behavior {
              enemy_skill_id: 23742
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 5
          }
          children {
            behavior {
              enemy_skill_id: 23743
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 6
          }
          children {
            behavior {
              enemy_skill_id: 23744
            }
          }
        }
      }
      children {
        group {
          children {
            behavior {
              enemy_skill_id: 23745
            }
          }
        }
      }
    }
  }
