  monster_id: 201614
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 41925
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        group {
          condition {
            trigger_turn: 1
          }
          children {
            behavior {
              enemy_skill_id: 41930
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 2
          }
          children {
            behavior {
              condition {
                erased_attributes: 0
                erased_attributes: 1
                erased_attributes: 2
                erased_attributes: 3
                erased_attributes: 4
              }
              enemy_skill_id: 41934
            }
          }
          children {
            behavior {
              enemy_skill_id: 41948
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 3
          }
          children {
            behavior {
              condition {
                trigger_combos: 5
              }
              enemy_skill_id: 41937
            }
          }
          children {
            behavior {
              enemy_skill_id: 41948
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 4
          }
          children {
            behavior {
              enemy_skill_id: 41948
            }
          }
          children {
            behavior {
              enemy_skill_id: 41941
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 5
          }
          children {
            behavior {
              enemy_skill_id: 41948
            }
          }
          children {
            behavior {
              enemy_skill_id: 41948
            }
          }
          children {
            behavior {
              enemy_skill_id: 41944
            }
          }
        }
      }
      children {
        group {
          children {
            behavior {
              enemy_skill_id: 41948
            }
          }
        }
      }
    }
  }
