  monster_id: 201783
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 14832
        }
      }
    }
  }
  levels {
    level: 2
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 14831
        }
      }
    }
  }
