  monster_id: 202194
  levels {
    level: 1
    groups {
      group_type: PASSIVE
      children {
        behavior {
          enemy_skill_id: 31387
        }
      }
    }
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 31071
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            group {
              condition {
                trigger_turn: 1
                always_trigger_above: 9
              }
              children {
                behavior {
                  enemy_skill_id: 31075
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 2
                always_trigger_above: 9
              }
              children {
                behavior {
                  enemy_skill_id: 31076
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 3
                always_trigger_above: 9
              }
              children {
                behavior {
                  enemy_skill_id: 31077
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 4
                always_trigger_above: 9
              }
              children {
                behavior {
                  enemy_skill_id: 31078
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 5
                always_trigger_above: 9
              }
              children {
                behavior {
                  enemy_skill_id: 31308
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  enemy_skill_id: 31376
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 9
            trigger_turn: 1
            trigger_turn_end: 5
          }
          children {
            behavior {
              enemy_skill_id: 31079
            }
          }
        }
      }
    }
  }
