  monster_id: 202278
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 35579
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
        trigger_turn: 1
      }
      children {
        behavior {
          enemy_skill_id: 35583
        }
      }
    }
  }
