  monster_id: 202322
  levels {
    level: 1
    groups {
      group_type: PASSIVE
      children {
        behavior {
          enemy_skill_id: 38121
        }
      }
    }
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 38100
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            group {
              condition {
                trigger_turn: 1
                trigger_turn_end: 2
              }
              children {
                behavior {
                  condition {
                    use_chance: 33
                  }
                  enemy_skill_id: 38112
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 50
                  }
                  enemy_skill_id: 38115
                }
              }
              children {
                behavior {
                  enemy_skill_id: 38118
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 3
              }
              children {
                behavior {
                  enemy_skill_id: 38108
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  condition {
                    use_chance: 33
                  }
                  enemy_skill_id: 38112
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 50
                  }
                  enemy_skill_id: 38115
                }
              }
              children {
                behavior {
                  enemy_skill_id: 38118
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 1
          }
          children {
            behavior {
              enemy_skill_id: 38104
            }
          }
        }
      }
    }
  }
