  monster_id: 202330
  levels {
    level: 4
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        group {
          condition {
            trigger_turn: 1
          }
          children {
            behavior {
              enemy_skill_id: 18332
            }
          }
        }
      }
      children {
        group {
          children {
            behavior {
              enemy_skill_id: 18334
            }
          }
        }
      }
    }
  }
