  monster_id: 202590
  levels {
    level: 1
    groups {
      group_type: PASSIVE
      children {
        behavior {
          enemy_skill_id: 25642
        }
      }
    }
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 25634
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          condition {
            trigger_turn: 6
            always_trigger_above: 1
          }
          children {
            behavior {
              enemy_skill_id: 25637
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            group {
              condition {
                trigger_turn: 1
                trigger_turn_end: 5
              }
              children {
                behavior {
                  enemy_skill_id: 25640
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  enemy_skill_id: 25641
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 1
            trigger_turn: 1
            trigger_turn_end: 5
          }
          children {
            behavior {
              enemy_skill_id: 25641
            }
          }
        }
      }
    }
  }
