  monster_id: 202720
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 4300
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        group {
          condition {
            trigger_turn: 1
          }
          children {
            behavior {
              enemy_skill_id: 4307
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 2
          }
          children {
            behavior {
              enemy_skill_id: 4308
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 3
          }
          children {
            behavior {
              enemy_skill_id: 4309
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 4
          }
          children {
            behavior {
              enemy_skill_id: 4310
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 5
          }
          children {
            behavior {
              enemy_skill_id: 4311
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 6
          }
          children {
            behavior {
              enemy_skill_id: 4312
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 7
          }
          children {
            behavior {
              enemy_skill_id: 4313
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 8
          }
          children {
            behavior {
              enemy_skill_id: 4314
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 9
          }
          children {
            behavior {
              enemy_skill_id: 4315
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 10
          }
          children {
            behavior {
              enemy_skill_id: 4316
            }
          }
        }
      }
      children {
        group {
          condition {
            repeats_every: 2
            trigger_turn: 1
          }
          children {
            behavior {
              enemy_skill_id: 4317
            }
          }
        }
      }
      children {
        group {
          condition {
            repeats_every: 2
            trigger_turn: 2
          }
          children {
            behavior {
              enemy_skill_id: 4351
            }
          }
        }
      }
    }
  }
