  monster_id: 203261
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 24191
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        group {
          condition {
            trigger_turn: 1
          }
          children {
            behavior {
              enemy_skill_id: 24195
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 2
          }
          children {
            behavior {
              enemy_skill_id: 24196
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 3
          }
          children {
            behavior {
              enemy_skill_id: 24197
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 4
          }
          children {
            behavior {
              enemy_skill_id: 24198
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 5
          }
          children {
            behavior {
              enemy_skill_id: 24199
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 6
          }
          children {
            behavior {
              enemy_skill_id: 24200
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 7
          }
          children {
            behavior {
              enemy_skill_id: 24201
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 8
          }
          children {
            behavior {
              enemy_skill_id: 24202
            }
          }
        }
      }
      children {
        group {
          children {
            behavior {
              enemy_skill_id: 24203
            }
          }
        }
      }
    }
  }
