  monster_id: 203263
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 18682
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        group {
          condition {
            trigger_turn: 1
            trigger_turn_end: 10
          }
          children {
            behavior {
              condition {
                use_chance: 50
              }
              enemy_skill_id: 18688
            }
          }
          children {
            behavior {
              condition {
                use_chance: 50
              }
              enemy_skill_id: 18689
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 11
          }
          children {
            behavior {
              enemy_skill_id: 18682
            }
          }
        }
      }
      children {
        group {
          children {
            behavior {
              condition {
                use_chance: 50
              }
              enemy_skill_id: 18688
            }
          }
          children {
            behavior {
              condition {
                use_chance: 50
              }
              enemy_skill_id: 18689
            }
          }
        }
      }
    }
  }
