  monster_id: 203390
  levels {
    level: 1
    groups {
      group_type: PASSIVE
      children {
        behavior {
          enemy_skill_id: 26412
        }
      }
      children {
        behavior {
          enemy_skill_id: 26413
        }
      }
    }
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 26414
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            group {
              condition {
                trigger_turn: 1
              }
              children {
                behavior {
                  enemy_skill_id: 26415
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 2
              }
              children {
                behavior {
                  enemy_skill_id: 26418
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 3
              }
              children {
                behavior {
                  enemy_skill_id: 26420
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 4
              }
              children {
                behavior {
                  enemy_skill_id: 26415
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 5
              }
              children {
                behavior {
                  enemy_skill_id: 26418
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 6
              }
              children {
                behavior {
                  enemy_skill_id: 26420
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 7
              }
              children {
                behavior {
                  enemy_skill_id: 26415
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 8
              }
              children {
                behavior {
                  enemy_skill_id: 26418
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 9
              }
              children {
                behavior {
                  enemy_skill_id: 26420
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 10
              }
              children {
                behavior {
                  enemy_skill_id: 26468
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 3
                trigger_turn: 1
              }
              children {
                behavior {
                  enemy_skill_id: 26415
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 3
                trigger_turn: 2
              }
              children {
                behavior {
                  enemy_skill_id: 26418
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 3
                trigger_turn: 3
              }
              children {
                behavior {
                  enemy_skill_id: 26420
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 1
          }
          children {
            behavior {
              enemy_skill_id: 26422
            }
          }
        }
      }
    }
  }
