  monster_id: 203416
  levels {
    level: 1
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        behavior {
          enemy_skill_id: 10332
        }
      }
    }
    groups {
      group_type: UNKNOWN_USE
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 10335
        }
      }
      children {
        behavior {
          enemy_skill_id: 10316
        }
      }
    }
  }
