  monster_id: 203953
  levels {
    level: 4
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 8289
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            behavior {
              condition {
                use_chance: 25
              }
              enemy_skill_id: 8290
            }
          }
          children {
            behavior {
              condition {
                use_chance: 25
              }
              enemy_skill_id: 8291
            }
          }
          children {
            behavior {
              condition {
                use_chance: 25
              }
              enemy_skill_id: 8292
            }
          }
          children {
            behavior {
              condition {
                use_chance: 25
              }
              enemy_skill_id: 1
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 49
          }
          children {
            group {
              condition {
                trigger_turn: 1
                always_trigger_above: 1
              }
              children {
                behavior {
                  condition {
                    use_chance: 20
                  }
                  enemy_skill_id: 8299
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 20
                  }
                  enemy_skill_id: 8300
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 20
                  }
                  enemy_skill_id: 8301
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 20
                  }
                  enemy_skill_id: 8302
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 20
                  }
                  enemy_skill_id: 8303
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  enemy_skill_id: 8304
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 19
          }
          children {
            group {
              condition {
                trigger_turn: 2
              }
              children {
                behavior {
                  enemy_skill_id: 8305
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  enemy_skill_id: 8306
                }
              }
            }
          }
        }
      }
    }
  }
