  monster_id: 204132
  levels {
    level: 4
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        group {
          condition {
            repeats_every: 3
            trigger_turn: 1
          }
          children {
            behavior {
              enemy_skill_id: 8771
            }
          }
        }
      }
      children {
        group {
          condition {
            repeats_every: 3
            trigger_turn: 2
          }
          children {
            behavior {
              enemy_skill_id: 8772
            }
          }
        }
      }
      children {
        group {
          condition {
            repeats_every: 3
            trigger_turn: 3
          }
          children {
            behavior {
              enemy_skill_id: 8773
            }
          }
        }
      }
    }
  }
