  monster_id: 204430
  levels {
    level: 1
    groups {
      group_type: PASSIVE
      children {
        behavior {
          enemy_skill_id: 27193
        }
      }
    }
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 27194
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        group {
          condition {
            trigger_turn: 1
          }
          children {
            behavior {
              enemy_skill_id: 27201
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 2
          }
          children {
            behavior {
              enemy_skill_id: 27204
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 3
          }
          children {
            behavior {
              enemy_skill_id: 27207
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 4
          }
          children {
            behavior {
              enemy_skill_id: 27211
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 5
            trigger_turn_end: 10
          }
          children {
            behavior {
              condition {
                use_chance: 25
              }
              enemy_skill_id: 27214
            }
          }
          children {
            behavior {
              condition {
                use_chance: 25
              }
              enemy_skill_id: 27218
            }
          }
          children {
            behavior {
              condition {
                use_chance: 25
              }
              enemy_skill_id: 27222
            }
          }
          children {
            behavior {
              condition {
                use_chance: 25
              }
              enemy_skill_id: 27226
            }
          }
        }
      }
      children {
        group {
          children {
            behavior {
              enemy_skill_id: 27161
            }
          }
        }
      }
    }
  }
