  monster_id: 204585
  levels {
    level: 1
    groups {
      group_type: PASSIVE
      children {
        behavior {
          enemy_skill_id: 11515
        }
      }
      children {
        behavior {
          enemy_skill_id: 13770
        }
      }
    }
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 11514
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            behavior {
              condition {
                use_chance: 10
              }
              enemy_skill_id: 11541
            }
          }
          children {
            behavior {
              condition {
                use_chance: 60
              }
              enemy_skill_id: 11523
            }
          }
          children {
            behavior {
              condition {
                use_chance: 20
              }
              enemy_skill_id: 11524
            }
          }
          children {
            behavior {
              condition {
                use_chance: 20
              }
              enemy_skill_id: 13771
            }
          }
          children {
            behavior {
              enemy_skill_id: 11525
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 49
            trigger_turn: 1
            always_trigger_above: 1
          }
          children {
            behavior {
              condition {
                use_chance: 20
              }
              enemy_skill_id: 11516
            }
          }
          children {
            behavior {
              condition {
                use_chance: 20
              }
              enemy_skill_id: 11517
            }
          }
          children {
            behavior {
              condition {
                use_chance: 20
              }
              enemy_skill_id: 11518
            }
          }
          children {
            behavior {
              condition {
                use_chance: 20
              }
              enemy_skill_id: 11519
            }
          }
          children {
            behavior {
              condition {
                use_chance: 20
              }
              enemy_skill_id: 11520
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 14
            trigger_turn: 2
            trigger_turn_end: 4
            always_trigger_above: 9
          }
          children {
            behavior {
              enemy_skill_id: 11521
            }
          }
          children {
            behavior {
              condition {
                use_chance: 10
              }
              enemy_skill_id: 11541
            }
          }
          children {
            behavior {
              condition {
                use_chance: 60
              }
              enemy_skill_id: 11523
            }
          }
          children {
            behavior {
              condition {
                use_chance: 20
              }
              enemy_skill_id: 11524
            }
          }
          children {
            behavior {
              condition {
                use_chance: 20
              }
              enemy_skill_id: 13771
            }
          }
          children {
            behavior {
              enemy_skill_id: 11525
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 9
          }
          children {
            group {
              condition {
                trigger_turn: 2
                trigger_turn_end: 4
              }
              children {
                behavior {
                  enemy_skill_id: 11521
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  enemy_skill_id: 11522
                }
              }
            }
          }
        }
      }
    }
  }
