  monster_id: 204729
  levels {
    level: 4
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 98
      }
      children {
        behavior {
          enemy_skill_id: 10654
        }
      }
    }
  }
