  monster_id: 205358
  levels {
    level: 4
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        behavior {
          condition {
            use_chance: 50
          }
          enemy_skill_id: 13452
        }
      }
      children {
        behavior {
          condition {
            use_chance: 50
          }
          enemy_skill_id: 13453
        }
      }
    }
    groups {
      group_type: REMAINING
      condition {
        hp_threshold: 100
        trigger_enemies_remaining: 1
        trigger_turn: 1
      }
      children {
        behavior {
          enemy_skill_id: 13462
        }
      }
    }
  }
