  monster_id: 2057
  levels {
    level: 5
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 2126
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            behavior {
              condition {
                use_chance: 30
              }
              enemy_skill_id: 2127
            }
          }
          children {
            behavior {
              condition {
                use_chance: 30
              }
              enemy_skill_id: 2128
            }
          }
          children {
            behavior {
              condition {
                use_chance: 30
              }
              enemy_skill_id: 2129
            }
          }
          children {
            behavior {
              enemy_skill_id: 1
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 49
          }
          children {
            group {
              condition {
                trigger_turn: 1
              }
              children {
                behavior {
                  enemy_skill_id: 2138
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  condition {
                    use_chance: 50
                  }
                  enemy_skill_id: 2139
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 50
                  }
                  enemy_skill_id: 2137
                }
              }
            }
          }
        }
      }
    }
  }
