  monster_id: 205863
  levels {
    level: 1
    groups {
      group_type: PASSIVE
      children {
        behavior {
          enemy_skill_id: 27131
        }
      }
    }
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 27133
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          condition {
            trigger_turn: 3
            always_trigger_above: 1
          }
          children {
            behavior {
              enemy_skill_id: 27136
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 4
            always_trigger_above: 1
          }
          children {
            behavior {
              enemy_skill_id: 27139
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 5
            always_trigger_above: 1
          }
          children {
            behavior {
              enemy_skill_id: 27136
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 6
            always_trigger_above: 1
          }
          children {
            behavior {
              enemy_skill_id: 27139
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 7
            always_trigger_above: 1
          }
          children {
            behavior {
              enemy_skill_id: 27136
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 8
            always_trigger_above: 1
          }
          children {
            behavior {
              enemy_skill_id: 27139
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 9
            always_trigger_above: 1
          }
          children {
            behavior {
              enemy_skill_id: 27136
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 10
            always_trigger_above: 1
          }
          children {
            behavior {
              enemy_skill_id: 27139
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            group {
              condition {
                trigger_turn: 1
                always_trigger_above: 49
              }
              children {
                behavior {
                  enemy_skill_id: 27136
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 2
                always_trigger_above: 49
              }
              children {
                behavior {
                  enemy_skill_id: 27139
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  enemy_skill_id: 27161
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 49
          }
          children {
            group {
              condition {
                trigger_turn: 1
              }
              children {
                behavior {
                  enemy_skill_id: 27142
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 2
              }
              children {
                behavior {
                  enemy_skill_id: 27145
                }
              }
            }
          }
        }
      }
    }
  }
