  monster_id: 205961
  levels {
    level: 1
    groups {
      group_type: PASSIVE
      children {
        behavior {
          enemy_skill_id: 17093
        }
      }
      children {
        behavior {
          enemy_skill_id: 17094
        }
      }
    }
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 17048
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            group {
              condition {
                repeats_every: 4
                trigger_turn: 1
                trigger_turn_end: 2
              }
              children {
                behavior {
                  condition {
                    use_chance: 25
                  }
                  enemy_skill_id: 17044
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 25
                  }
                  enemy_skill_id: 17045
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 25
                  }
                  enemy_skill_id: 17046
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 5
                  }
                  enemy_skill_id: 17095
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 5
                  }
                  enemy_skill_id: 17096
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 5
                  }
                  enemy_skill_id: 17097
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 5
                  }
                  enemy_skill_id: 17098
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 5
                  }
                  enemy_skill_id: 17099
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 4
                trigger_turn: 3
              }
              children {
                behavior {
                  enemy_skill_id: 17047
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 4
                trigger_turn: 4
              }
              children {
                behavior {
                  condition {
                    use_chance: 25
                  }
                  enemy_skill_id: 17044
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 25
                  }
                  enemy_skill_id: 17045
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 25
                  }
                  enemy_skill_id: 17046
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 5
                  }
                  enemy_skill_id: 17095
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 5
                  }
                  enemy_skill_id: 17096
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 5
                  }
                  enemy_skill_id: 17097
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 5
                  }
                  enemy_skill_id: 17098
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 5
                  }
                  enemy_skill_id: 17099
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 1
          }
          children {
            behavior {
              enemy_skill_id: 17100
            }
          }
        }
      }
    }
  }
  levels {
    level: 9
    groups {
      group_type: PASSIVE
      children {
        behavior {
          enemy_skill_id: 17093
        }
      }
      children {
        behavior {
          enemy_skill_id: 17094
        }
      }
    }
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 17040
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            group {
              condition {
                repeats_every: 4
                trigger_turn: 1
                trigger_turn_end: 2
              }
              children {
                behavior {
                  condition {
                    use_chance: 25
                  }
                  enemy_skill_id: 17044
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 25
                  }
                  enemy_skill_id: 17045
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 25
                  }
                  enemy_skill_id: 17046
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 5
                  }
                  enemy_skill_id: 17095
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 5
                  }
                  enemy_skill_id: 17096
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 5
                  }
                  enemy_skill_id: 17097
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 5
                  }
                  enemy_skill_id: 17098
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 5
                  }
                  enemy_skill_id: 17099
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 4
                trigger_turn: 3
              }
              children {
                behavior {
                  enemy_skill_id: 17047
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 4
                trigger_turn: 4
              }
              children {
                behavior {
                  condition {
                    use_chance: 25
                  }
                  enemy_skill_id: 17044
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 25
                  }
                  enemy_skill_id: 17045
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 25
                  }
                  enemy_skill_id: 17046
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 5
                  }
                  enemy_skill_id: 17095
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 5
                  }
                  enemy_skill_id: 17096
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 5
                  }
                  enemy_skill_id: 17097
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 5
                  }
                  enemy_skill_id: 17098
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 5
                  }
                  enemy_skill_id: 17099
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 1
          }
          children {
            behavior {
              enemy_skill_id: 17100
            }
          }
        }
      }
    }
  }
