  monster_id: 206233
  levels {
    level: 1
    groups {
      group_type: PASSIVE
      children {
        behavior {
          enemy_skill_id: 22296
        }
      }
    }
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 22289
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            group {
              condition {
                trigger_turn: 1
                trigger_turn_end: 3
                always_trigger_above: 19
              }
              children {
                behavior {
                  enemy_skill_id: 22292
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 4
                trigger_turn_end: 14
                always_trigger_above: 19
              }
              children {
                behavior {
                  enemy_skill_id: 22295
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  enemy_skill_id: 22200
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 19
            repeats_every: 7
            trigger_turn: 1
            trigger_turn_end: 7
          }
          children {
            behavior {
              enemy_skill_id: 22295
            }
          }
        }
      }
    }
  }
