  monster_id: 2067
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 2064
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        behavior {
          condition {
            use_chance: 50
          }
          enemy_skill_id: 2064
        }
      }
      children {
        behavior {
          enemy_skill_id: 2065
        }
      }
    }
  }
  levels {
    level: 2
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 2064
        }
      }
    }
  }
