  monster_id: 207305
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 45223
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        group {
          condition {
            trigger_turn: 1
          }
          children {
            behavior {
              condition {
                use_chance: 33
              }
              enemy_skill_id: 45229
            }
          }
          children {
            behavior {
              condition {
                use_chance: 50
              }
              enemy_skill_id: 45232
            }
          }
          children {
            behavior {
              enemy_skill_id: 45233
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 2
          }
          children {
            behavior {
              enemy_skill_id: 45226
            }
          }
        }
      }
      children {
        group {
          children {
            behavior {
              condition {
                use_chance: 33
              }
              enemy_skill_id: 45229
            }
          }
          children {
            behavior {
              condition {
                use_chance: 50
              }
              enemy_skill_id: 45232
            }
          }
          children {
            behavior {
              enemy_skill_id: 45233
            }
          }
        }
      }
    }
  }
