  monster_id: 207777
  levels {
    level: 1
    groups {
      group_type: PASSIVE
      children {
        behavior {
          enemy_skill_id: 34042
        }
      }
    }
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 34490
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 9
        trigger_turn: 1
      }
      children {
        behavior {
          enemy_skill_id: 34047
        }
      }
    }
    groups {
      group_type: UNKNOWN_USE
      children {
        behavior {
          enemy_skill_id: 34557
        }
      }
      children {
        behavior {
          condition {
            use_chance: 20
          }
          enemy_skill_id: 34503
        }
      }
      children {
        behavior {
          condition {
            use_chance: 20
          }
          enemy_skill_id: 34507
        }
      }
      children {
        behavior {
          condition {
            use_chance: 20
          }
          enemy_skill_id: 34511
        }
      }
      children {
        behavior {
          condition {
            use_chance: 20
          }
          enemy_skill_id: 34515
        }
      }
      children {
        behavior {
          condition {
            use_chance: 20
          }
          enemy_skill_id: 34519
        }
      }
      children {
        behavior {
          enemy_skill_id: 34558
        }
      }
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 34500
        }
      }
      children {
        behavior {
          enemy_skill_id: 34560
        }
      }
      children {
        behavior {
          condition {
            use_chance: 20
          }
          enemy_skill_id: 34523
        }
      }
      children {
        behavior {
          condition {
            use_chance: 20
          }
          enemy_skill_id: 34526
        }
      }
      children {
        behavior {
          condition {
            use_chance: 20
          }
          enemy_skill_id: 34529
        }
      }
      children {
        behavior {
          condition {
            use_chance: 20
          }
          enemy_skill_id: 34532
        }
      }
      children {
        behavior {
          condition {
            use_chance: 20
          }
          enemy_skill_id: 34535
        }
      }
      children {
        behavior {
          enemy_skill_id: 34559
        }
      }
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 34495
        }
      }
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 34565
        }
      }
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 34561
        }
      }
    }
  }
