  monster_id: 207919
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 29981
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        group {
          condition {
            trigger_turn: 1
          }
          children {
            behavior {
              enemy_skill_id: 30432
            }
          }
          children {
            behavior {
              enemy_skill_id: 29985
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 2
          }
          children {
            behavior {
              enemy_skill_id: 30433
            }
          }
          children {
            behavior {
              enemy_skill_id: 29987
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 3
          }
          children {
            behavior {
              enemy_skill_id: 29996
            }
          }
          children {
            behavior {
              enemy_skill_id: 29989
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 4
          }
          children {
            behavior {
              enemy_skill_id: 29996
            }
          }
          children {
            behavior {
              enemy_skill_id: 29991
            }
          }
        }
      }
      children {
        group {
          children {
            behavior {
              enemy_skill_id: 29996
            }
          }
          children {
            behavior {
              enemy_skill_id: 29994
            }
          }
        }
      }
    }
    groups {
      group_type: UNKNOWN_USE
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 30434
        }
      }
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 30435
        }
      }
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 30436
        }
      }
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 30439
        }
      }
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 30440
        }
      }
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 30441
        }
      }
    }
  }
  levels {
    level: 2
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 29997
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        group {
          condition {
            trigger_turn: 1
          }
          children {
            behavior {
              enemy_skill_id: 30437
            }
          }
          children {
            behavior {
              enemy_skill_id: 29999
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 2
          }
          children {
            behavior {
              enemy_skill_id: 30438
            }
          }
          children {
            behavior {
              enemy_skill_id: 30001
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 3
          }
          children {
            behavior {
              enemy_skill_id: 29996
            }
          }
          children {
            behavior {
              enemy_skill_id: 30003
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 4
          }
          children {
            behavior {
              enemy_skill_id: 29996
            }
          }
          children {
            behavior {
              enemy_skill_id: 30005
            }
          }
        }
      }
      children {
        group {
          children {
            behavior {
              enemy_skill_id: 29996
            }
          }
          children {
            behavior {
              enemy_skill_id: 29994
            }
          }
        }
      }
    }
    groups {
      group_type: UNKNOWN_USE
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 30434
        }
      }
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 30435
        }
      }
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 30436
        }
      }
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 30439
        }
      }
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 30440
        }
      }
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 30441
        }
      }
    }
  }
