  monster_id: 207996
  levels {
    level: 1
    groups {
      group_type: PASSIVE
      children {
        behavior {
          enemy_skill_id: 28195
        }
      }
    }
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 28196
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          condition {
            trigger_turn: 1
            always_trigger_above: 1
          }
          children {
            behavior {
              enemy_skill_id: 28239
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 2
            always_trigger_above: 1
          }
          children {
            behavior {
              enemy_skill_id: 28242
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 3
            always_trigger_above: 1
          }
          children {
            behavior {
              enemy_skill_id: 28245
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 4
            always_trigger_above: 1
          }
          children {
            behavior {
              enemy_skill_id: 28250
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 9
            always_trigger_above: 1
          }
          children {
            behavior {
              enemy_skill_id: 28200
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 10
            always_trigger_above: 1
          }
          children {
            behavior {
              enemy_skill_id: 28203
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 11
            always_trigger_above: 1
          }
          children {
            behavior {
              enemy_skill_id: 27295
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 12
            always_trigger_above: 1
          }
          children {
            behavior {
              enemy_skill_id: 28200
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 13
            always_trigger_above: 1
          }
          children {
            behavior {
              enemy_skill_id: 28203
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 14
            always_trigger_above: 1
          }
          children {
            behavior {
              enemy_skill_id: 28206
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 15
            always_trigger_above: 1
          }
          children {
            behavior {
              enemy_skill_id: 28203
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            group {
              condition {
                trigger_turn: 5
                always_trigger_above: 49
              }
              children {
                behavior {
                  enemy_skill_id: 28200
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 6
                always_trigger_above: 49
              }
              children {
                behavior {
                  enemy_skill_id: 28203
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 7
                always_trigger_above: 49
              }
              children {
                behavior {
                  enemy_skill_id: 28206
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 8
                always_trigger_above: 49
              }
              children {
                behavior {
                  enemy_skill_id: 28203
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 2
                trigger_turn: 1
              }
              children {
                behavior {
                  enemy_skill_id: 28200
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 2
                trigger_turn: 2
              }
              children {
                behavior {
                  enemy_skill_id: 28203
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 49
          }
          children {
            group {
              condition {
                trigger_turn: 5
              }
              children {
                behavior {
                  enemy_skill_id: 28209
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 6
              }
              children {
                behavior {
                  enemy_skill_id: 28212
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 7
              }
              children {
                behavior {
                  enemy_skill_id: 28215
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 8
              }
              children {
                behavior {
                  enemy_skill_id: 28218
                }
              }
            }
          }
        }
      }
    }
  }
