  monster_id: 208060
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 31517
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        group {
          condition {
            trigger_turn: 1
          }
          children {
            behavior {
              enemy_skill_id: 31521
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 2
          }
          children {
            behavior {
              enemy_skill_id: 31525
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 3
          }
          children {
            behavior {
              enemy_skill_id: 31527
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 4
          }
          children {
            behavior {
              enemy_skill_id: 31529
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 5
          }
          children {
            behavior {
              enemy_skill_id: 31531
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 6
          }
          children {
            behavior {
              enemy_skill_id: 31533
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 7
          }
          children {
            behavior {
              enemy_skill_id: 31535
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 8
            trigger_turn_end: 10
          }
          children {
            behavior {
              enemy_skill_id: 31537
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 11
          }
          children {
            behavior {
              enemy_skill_id: 27295
            }
          }
        }
      }
      children {
        group {
          children {
            behavior {
              enemy_skill_id: 31537
            }
          }
        }
      }
    }
  }
