  monster_id: 208571
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 45065
        }
      }
    }
    groups {
      group_type: DEATH
      condition {
        if_defeated: true
      }
      children {
        behavior {
          enemy_skill_id: 45071
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        group {
          condition {
            repeats_every: 3
            trigger_turn: 1
          }
          children {
            behavior {
              enemy_skill_id: 45068
            }
          }
        }
      }
      children {
        group {
          condition {
            repeats_every: 3
            trigger_turn: 2
          }
          children {
            behavior {
              enemy_skill_id: 45069
            }
          }
        }
      }
      children {
        group {
          condition {
            repeats_every: 3
            trigger_turn: 3
          }
          children {
            behavior {
              enemy_skill_id: 45070
            }
          }
        }
      }
    }
  }
