  monster_id: 208600
  levels {
    level: 1
    groups {
      group_type: PASSIVE
      children {
        behavior {
          enemy_skill_id: 35393
        }
      }
    }
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 35380
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            behavior {
              condition {
                use_chance: 6
              }
              enemy_skill_id: 35386
            }
          }
          children {
            behavior {
              condition {
                use_chance: 7
              }
              enemy_skill_id: 35387
            }
          }
          children {
            behavior {
              condition {
                use_chance: 7
              }
              enemy_skill_id: 35388
            }
          }
          children {
            behavior {
              condition {
                use_chance: 7
              }
              enemy_skill_id: 35389
            }
          }
          children {
            behavior {
              condition {
                use_chance: 7
              }
              enemy_skill_id: 35390
            }
          }
          children {
            behavior {
              condition {
                use_chance: 33
              }
              enemy_skill_id: 35391
            }
          }
          children {
            behavior {
              condition {
                use_chance: 33
              }
              enemy_skill_id: 35392
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 49
            trigger_turn: 1
          }
          children {
            behavior {
              enemy_skill_id: 35383
            }
          }
        }
      }
    }
  }
