  monster_id: 209539
  levels {
    level: 1
    groups {
      group_type: PASSIVE
      children {
        behavior {
          enemy_skill_id: 43762
        }
      }
    }
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 43749
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        group {
          condition {
            repeats_every: 6
            trigger_turn: 1
          }
          children {
            behavior {
              enemy_skill_id: 43752
            }
          }
        }
      }
      children {
        group {
          condition {
            repeats_every: 6
            trigger_turn: 2
          }
          children {
            behavior {
              enemy_skill_id: 43753
            }
          }
        }
      }
      children {
        group {
          condition {
            repeats_every: 6
            trigger_turn: 3
          }
          children {
            behavior {
              enemy_skill_id: 43754
            }
          }
        }
      }
      children {
        group {
          condition {
            repeats_every: 6
            trigger_turn: 4
          }
          children {
            behavior {
              enemy_skill_id: 43755
            }
          }
        }
      }
      children {
        group {
          condition {
            repeats_every: 6
            trigger_turn: 5
          }
          children {
            behavior {
              enemy_skill_id: 43756
            }
          }
        }
      }
      children {
        group {
          condition {
            repeats_every: 6
            trigger_turn: 6
          }
          children {
            behavior {
              enemy_skill_id: 43757
            }
          }
        }
      }
    }
  }
