  monster_id: 209579
  levels {
    level: 1
    groups {
      group_type: PASSIVE
      children {
        behavior {
          enemy_skill_id: 43729
        }
      }
    }
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 43718
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            group {
              condition {
                repeats_every: 4
                trigger_turn: 1
              }
              children {
                behavior {
                  enemy_skill_id: 43725
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 4
                trigger_turn: 2
              }
              children {
                behavior {
                  enemy_skill_id: 43726
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 4
                trigger_turn: 3
              }
              children {
                behavior {
                  enemy_skill_id: 43727
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 4
                trigger_turn: 4
              }
              children {
                behavior {
                  enemy_skill_id: 43728
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 14
          }
          children {
            group {
              condition {
                trigger_turn: 1
              }
              children {
                behavior {
                  enemy_skill_id: 43721
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  enemy_skill_id: 43724
                }
              }
            }
          }
        }
      }
    }
  }
