  monster_id: 209770
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 46523
        }
      }
    }
  }
  levels {
    level: 4
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 46524
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        behavior {
          condition {
            use_chance: 50
          }
          enemy_skill_id: 46526
        }
      }
      children {
        behavior {
          condition {
            use_chance: 50
          }
          enemy_skill_id: 46527
        }
      }
    }
  }
