  monster_id: 2185
  levels {
    level: 1
    groups {
      group_type: PASSIVE
      children {
        behavior {
          enemy_skill_id: 21682
        }
      }
    }
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 21683
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            group {
              condition {
                trigger_turn: 1
              }
              children {
                behavior {
                  enemy_skill_id: 21686
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 2
                trigger_turn_end: 4
              }
              children {
                behavior {
                  enemy_skill_id: 21689
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  enemy_skill_id: 21690
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 1
            trigger_turn: 1
          }
          children {
            behavior {
              enemy_skill_id: 21691
            }
          }
        }
      }
    }
  }
