  monster_id: 2186
  levels {
    level: 5
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 3014
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        group {
          condition {
            trigger_turn: 1
          }
          children {
            behavior {
              enemy_skill_id: 3009
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 2
          }
          children {
            behavior {
              condition {
                use_chance: 20
              }
              enemy_skill_id: 3018
            }
          }
          children {
            behavior {
              condition {
                use_chance: 20
              }
              enemy_skill_id: 3016
            }
          }
          children {
            behavior {
              condition {
                use_chance: 20
              }
              enemy_skill_id: 3017
            }
          }
          children {
            behavior {
              condition {
                use_chance: 40
              }
              enemy_skill_id: 3019
            }
          }
        }
      }
      children {
        group {
          condition {
            repeats_every: 8
            trigger_turn: 1
            trigger_turn_end: 7
          }
          children {
            behavior {
              condition {
                use_chance: 20
              }
              enemy_skill_id: 3018
            }
          }
          children {
            behavior {
              condition {
                use_chance: 20
              }
              enemy_skill_id: 3016
            }
          }
          children {
            behavior {
              condition {
                use_chance: 20
              }
              enemy_skill_id: 3017
            }
          }
          children {
            behavior {
              condition {
                use_chance: 40
              }
              enemy_skill_id: 3019
            }
          }
        }
      }
      children {
        group {
          condition {
            repeats_every: 8
            trigger_turn: 8
          }
          children {
            behavior {
              enemy_skill_id: 3008
            }
          }
        }
      }
    }
  }
