  monster_id: 2194
  levels {
    level: 3
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 4268
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: MONSTER_STATUS
          children {
            behavior {
              enemy_skill_id: 4270
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            group {
              condition {
                trigger_turn: 1
                always_trigger_above: 4
              }
              children {
                behavior {
                  enemy_skill_id: 4273
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 2
                always_trigger_above: 4
              }
              children {
                behavior {
                  enemy_skill_id: 4274
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 3
                always_trigger_above: 4
              }
              children {
                behavior {
                  enemy_skill_id: 4275
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 4
                always_trigger_above: 4
              }
              children {
                behavior {
                  enemy_skill_id: 4267
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 5
                always_trigger_above: 4
              }
              children {
                behavior {
                  enemy_skill_id: 4271
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 6
                always_trigger_above: 4
              }
              children {
                behavior {
                  enemy_skill_id: 4276
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 7
                always_trigger_above: 4
              }
              children {
                behavior {
                  enemy_skill_id: 4277
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 8
                always_trigger_above: 4
              }
              children {
                behavior {
                  enemy_skill_id: 4278
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 9
                always_trigger_above: 4
              }
              children {
                behavior {
                  enemy_skill_id: 4279
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  enemy_skill_id: 4272
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 4
          }
          children {
            behavior {
              enemy_skill_id: 4269
            }
          }
        }
      }
    }
  }
