  monster_id: 2206
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 3032
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            behavior {
              enemy_skill_id: 3034
            }
          }
          children {
            behavior {
              enemy_skill_id: 3035
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 79
          }
          children {
            behavior {
              enemy_skill_id: 3034
            }
          }
          children {
            behavior {
              condition {
                use_chance: 60
              }
              enemy_skill_id: 3038
            }
          }
          children {
            behavior {
              enemy_skill_id: 3035
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 49
          }
          children {
            group {
              condition {
                trigger_turn: 1
                always_trigger_above: 1
              }
              children {
                behavior {
                  enemy_skill_id: 3041
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  enemy_skill_id: 3043
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 19
          }
          children {
            behavior {
              enemy_skill_id: 3046
            }
          }
        }
      }
    }
  }
