  monster_id: 221
  levels {
    level: 1
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
            trigger_turn: 1
            always_trigger_above: 24
          }
          children {
            behavior {
              enemy_skill_id: 331
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 24
          }
          children {
            group {
              condition {
                trigger_turn: 1
              }
              children {
                behavior {
                  enemy_skill_id: 331
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  enemy_skill_id: 332
                }
              }
            }
          }
        }
      }
    }
  }
