  monster_id: 2234
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 3201
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 101
          }
          children {
            group {
              condition {
                trigger_turn: 1
              }
              children {
                behavior {
                  condition {
                    trigger_monsters: 1947
                    trigger_monsters: 1949
                  }
                  enemy_skill_id: 3211
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  enemy_skill_id: 3202
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 99
          }
          children {
            group {
              condition {
                repeats_every: 2
                trigger_turn: 1
              }
              children {
                behavior {
                  enemy_skill_id: 3209
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 2
                trigger_turn: 2
              }
              children {
                behavior {
                  enemy_skill_id: 3208
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 79
          }
          children {
            group {
              condition {
                trigger_turn: 1
                always_trigger_above: 19
              }
              children {
                behavior {
                  condition {
                    use_chance: 33
                  }
                  enemy_skill_id: 3203
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 33
                  }
                  enemy_skill_id: 3204
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 34
                  }
                  enemy_skill_id: 3205
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 2
                trigger_turn: 1
              }
              children {
                behavior {
                  enemy_skill_id: 3209
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 2
                trigger_turn: 2
              }
              children {
                behavior {
                  condition {
                    use_chance: 20
                  }
                  enemy_skill_id: 3207
                }
              }
              children {
                behavior {
                  enemy_skill_id: 3208
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 19
          }
          children {
            group {
              condition {
                trigger_turn: 1
              }
              children {
                behavior {
                  enemy_skill_id: 3214
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  condition {
                    trigger_monsters: 1951
                    trigger_monsters: 1953
                    trigger_monsters: 2069
                    trigger_monsters: 2263
                    trigger_monsters: 2206
                  }
                  enemy_skill_id: 3213
                }
              }
              children {
                behavior {
                  enemy_skill_id: 3206
                }
              }
            }
          }
        }
      }
    }
  }
