  monster_id: 225
  levels {
    level: 1
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 39
      }
      children {
        behavior {
          condition {
            use_chance: 75
          }
          enemy_skill_id: 212
        }
      }
    }
  }
