  monster_id: 2295
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 10140
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            behavior {
              condition {
                use_chance: 50
              }
              enemy_skill_id: 10141
            }
          }
          children {
            behavior {
              enemy_skill_id: 10142
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 9
          }
          children {
            behavior {
              enemy_skill_id: 10143
            }
          }
        }
      }
    }
  }
