  monster_id: 230
  levels {
    level: 1
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 49
          }
          children {
            behavior {
              condition {
                use_chance: 30
              }
              enemy_skill_id: 151
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 24
          }
          children {
            behavior {
              condition {
                use_chance: 40
              }
              enemy_skill_id: 153
            }
          }
          children {
            behavior {
              condition {
                use_chance: 30
              }
              enemy_skill_id: 151
            }
          }
        }
      }
    }
  }
