  monster_id: 2310
  levels {
    level: 4
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 2614
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
        trigger_turn: 1
      }
      children {
        behavior {
          enemy_skill_id: 3319
        }
      }
    }
  }
