  monster_id: 2322
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          condition {
            trigger_monsters: 2983
          }
          enemy_skill_id: 6048
        }
      }
      children {
        behavior {
          condition {
            trigger_monsters: 2323
          }
          enemy_skill_id: 6047
        }
      }
      children {
        behavior {
          enemy_skill_id: 6018
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            group {
              condition {
                trigger_turn: 1
                always_trigger_above: 94
              }
              children {
                behavior {
                  enemy_skill_id: 6025
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 8
                trigger_turn: 1
                trigger_turn_end: 7
              }
              children {
                behavior {
                  condition {
                    use_chance: 13
                  }
                  enemy_skill_id: 6037
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 13
                  }
                  enemy_skill_id: 6038
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 13
                  }
                  enemy_skill_id: 6039
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 13
                  }
                  enemy_skill_id: 6040
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 12
                  }
                  enemy_skill_id: 6041
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 12
                  }
                  enemy_skill_id: 6042
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 12
                  }
                  enemy_skill_id: 6043
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 12
                  }
                  enemy_skill_id: 6044
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 8
                trigger_turn: 8
              }
              children {
                behavior {
                  enemy_skill_id: 6056
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 94
            trigger_turn: 1
            always_trigger_above: 1
          }
          children {
            behavior {
              enemy_skill_id: 6021
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 49
          }
          children {
            group {
              condition {
                trigger_turn: 2
              }
              children {
                behavior {
                  enemy_skill_id: 6045
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 8
                trigger_turn: 1
                trigger_turn_end: 6
              }
              children {
                behavior {
                  condition {
                    use_chance: 13
                  }
                  enemy_skill_id: 6037
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 13
                  }
                  enemy_skill_id: 6038
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 13
                  }
                  enemy_skill_id: 6039
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 13
                  }
                  enemy_skill_id: 6040
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 12
                  }
                  enemy_skill_id: 6041
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 12
                  }
                  enemy_skill_id: 6042
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 12
                  }
                  enemy_skill_id: 6043
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 12
                  }
                  enemy_skill_id: 6044
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 8
                trigger_turn: 7
              }
              children {
                behavior {
                  enemy_skill_id: 6056
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 8
                trigger_turn: 8
              }
              children {
                behavior {
                  condition {
                    use_chance: 13
                  }
                  enemy_skill_id: 6037
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 13
                  }
                  enemy_skill_id: 6038
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 13
                  }
                  enemy_skill_id: 6039
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 13
                  }
                  enemy_skill_id: 6040
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 12
                  }
                  enemy_skill_id: 6041
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 12
                  }
                  enemy_skill_id: 6042
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 12
                  }
                  enemy_skill_id: 6043
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 12
                  }
                  enemy_skill_id: 6044
                }
              }
            }
          }
        }
      }
    }
    groups {
      group_type: UNKNOWN_USE
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 6046
        }
      }
    }
  }
