  monster_id: 234
  levels {
    level: 2
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 49
      }
      children {
        behavior {
          enemy_skill_id: 407
        }
      }
    }
  }
