  monster_id: 2382
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 16026
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        group {
          condition {
            trigger_turn: 1
            trigger_turn_end: 6
          }
          children {
            behavior {
              enemy_skill_id: 16017
            }
          }
        }
      }
      children {
        group {
          children {
            behavior {
              enemy_skill_id: 16018
            }
          }
        }
      }
    }
    groups {
      group_type: UNKNOWN_USE
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 16019
        }
      }
    }
  }
