  monster_id: 2409
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 20289
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        group {
          condition {
            trigger_turn: 1
            trigger_turn_end: 9
          }
          children {
            behavior {
              condition {
                use_chance: 33
              }
              enemy_skill_id: 20292
            }
          }
          children {
            behavior {
              condition {
                use_chance: 33
              }
              enemy_skill_id: 20293
            }
          }
          children {
            behavior {
              condition {
                use_chance: 34
              }
              enemy_skill_id: 20294
            }
          }
        }
      }
      children {
        group {
          children {
            behavior {
              enemy_skill_id: 20295
            }
          }
        }
      }
    }
  }
