  monster_id: 2412
  levels {
    level: 4
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 3386
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          condition {
            trigger_turn: 1
            always_trigger_above: 1
          }
          children {
            behavior {
              enemy_skill_id: 3396
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 2
            always_trigger_above: 1
          }
          children {
            behavior {
              enemy_skill_id: 3397
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 3
            always_trigger_above: 1
          }
          children {
            behavior {
              enemy_skill_id: 3398
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            behavior {
              enemy_skill_id: 3399
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 19
          }
          children {
            behavior {
              enemy_skill_id: 3400
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 9
          }
          children {
            behavior {
              enemy_skill_id: 3401
            }
          }
        }
      }
    }
  }
