  monster_id: 2433
  levels {
    level: 4
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 3531
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            behavior {
              enemy_skill_id: 3473
            }
          }
          children {
            behavior {
              condition {
                use_chance: 25
              }
              enemy_skill_id: 3472
            }
          }
          children {
            behavior {
              condition {
                use_chance: 25
              }
              enemy_skill_id: 3533
            }
          }
          children {
            behavior {
              condition {
                use_chance: 25
              }
              enemy_skill_id: 3468
            }
          }
          children {
            behavior {
              condition {
                use_chance: 25
              }
              enemy_skill_id: 3532
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 69
            trigger_turn: 1
            always_trigger_above: 1
          }
          children {
            behavior {
              enemy_skill_id: 3473
            }
          }
          children {
            behavior {
              enemy_skill_id: 3471
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 9
          }
          children {
            behavior {
              enemy_skill_id: 3473
            }
          }
          children {
            behavior {
              enemy_skill_id: 3470
            }
          }
        }
      }
    }
  }
