  monster_id: 2479
  levels {
    level: 4
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 3474
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            group {
              condition {
                trigger_turn: 1
                always_trigger_above: 89
              }
              children {
                behavior {
                  enemy_skill_id: 3475
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 2
                always_trigger_above: 89
              }
              children {
                behavior {
                  condition {
                    trigger_monsters: 2472
                    trigger_monsters: 2473
                  }
                  enemy_skill_id: 3483
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 35
                  }
                  enemy_skill_id: 3477
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 35
                  }
                  enemy_skill_id: 3478
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 30
                  }
                  enemy_skill_id: 3476
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  condition {
                    use_chance: 35
                  }
                  enemy_skill_id: 3477
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 35
                  }
                  enemy_skill_id: 3478
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 30
                  }
                  enemy_skill_id: 3476
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 89
            trigger_turn: 1
            always_trigger_above: 49
          }
          children {
            behavior {
              condition {
                trigger_monsters: 2472
                trigger_monsters: 2473
              }
              enemy_skill_id: 3483
            }
          }
          children {
            behavior {
              condition {
                use_chance: 35
              }
              enemy_skill_id: 3477
            }
          }
          children {
            behavior {
              condition {
                use_chance: 35
              }
              enemy_skill_id: 3478
            }
          }
          children {
            behavior {
              condition {
                use_chance: 30
              }
              enemy_skill_id: 3476
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 49
          }
          children {
            group {
              condition {
                trigger_turn: 1
                always_trigger_above: 1
              }
              children {
                behavior {
                  enemy_skill_id: 3479
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 2
                always_trigger_above: 19
              }
              children {
                behavior {
                  condition {
                    trigger_monsters: 2472
                    trigger_monsters: 2473
                  }
                  enemy_skill_id: 3483
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 35
                  }
                  enemy_skill_id: 3477
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 35
                  }
                  enemy_skill_id: 3478
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 30
                  }
                  enemy_skill_id: 3476
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 19
          }
          children {
            behavior {
              enemy_skill_id: 3481
            }
          }
        }
      }
    }
  }
