  monster_id: 2483
  levels {
    level: 4
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 3492
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            group {
              condition {
                trigger_turn: 1
                always_trigger_above: 69
              }
              children {
                behavior {
                  condition {
                    trigger_monsters: 2457
                    trigger_monsters: 2458
                    trigger_monsters: 2459
                  }
                  enemy_skill_id: 3498
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  condition {
                    use_chance: 30
                  }
                  enemy_skill_id: 3493
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 50
                  }
                  enemy_skill_id: 3495
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 69
            trigger_turn: 1
            always_trigger_above: 1
          }
          children {
            behavior {
              condition {
                trigger_monsters: 2457
                trigger_monsters: 2458
                trigger_monsters: 2459
              }
              enemy_skill_id: 3498
            }
          }
          children {
            behavior {
              enemy_skill_id: 3494
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 19
          }
          children {
            group {
              condition {
                trigger_turn: 2
              }
              children {
                behavior {
                  enemy_skill_id: 3480
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  enemy_skill_id: 3496
                }
              }
            }
          }
        }
      }
    }
  }
