  monster_id: 2519
  levels {
    level: 1
    groups {
      group_type: PASSIVE
      children {
        behavior {
          enemy_skill_id: 25772
        }
      }
    }
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 25836
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            group {
              condition {
                trigger_turn: 1
                always_trigger_above: 49
              }
              children {
                behavior {
                  enemy_skill_id: 25766
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 2
                trigger_turn_end: 4
                always_trigger_above: 49
              }
              children {
                behavior {
                  enemy_skill_id: 25769
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 5
                always_trigger_above: 49
              }
              children {
                behavior {
                  enemy_skill_id: 25834
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  enemy_skill_id: 25769
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 49
          }
          children {
            group {
              condition {
                trigger_turn: 1
              }
              children {
                behavior {
                  enemy_skill_id: 25753
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  condition {
                    trigger_combos: 3
                  }
                  enemy_skill_id: 25758
                }
              }
              children {
                behavior {
                  enemy_skill_id: 25835
                }
              }
            }
          }
        }
      }
    }
  }
  levels {
    level: 10
    groups {
      group_type: PASSIVE
      children {
        behavior {
          enemy_skill_id: 25772
        }
      }
    }
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 25748
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            group {
              condition {
                trigger_turn: 1
                always_trigger_above: 49
              }
              children {
                behavior {
                  enemy_skill_id: 25766
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 2
                trigger_turn_end: 4
                always_trigger_above: 49
              }
              children {
                behavior {
                  enemy_skill_id: 25769
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 5
                always_trigger_above: 49
              }
              children {
                behavior {
                  enemy_skill_id: 25812
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  enemy_skill_id: 25769
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 49
          }
          children {
            group {
              condition {
                trigger_turn: 1
              }
              children {
                behavior {
                  enemy_skill_id: 25753
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  condition {
                    trigger_combos: 3
                  }
                  enemy_skill_id: 25758
                }
              }
              children {
                behavior {
                  enemy_skill_id: 25762
                }
              }
            }
          }
        }
      }
    }
  }
