  monster_id: 2550
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 16020
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        group {
          condition {
            trigger_turn: 1
            trigger_turn_end: 7
          }
          children {
            behavior {
              enemy_skill_id: 16022
            }
          }
        }
      }
      children {
        group {
          children {
            behavior {
              enemy_skill_id: 16023
            }
          }
        }
      }
    }
  }
