  monster_id: 2671
  levels {
    level: 3
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 4737
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        behavior {
          condition {
            use_chance: 40
          }
          enemy_skill_id: 4738
        }
      }
      children {
        behavior {
          condition {
            use_chance: 20
          }
          enemy_skill_id: 4739
        }
      }
      children {
        behavior {
          condition {
            use_chance: 10
          }
          enemy_skill_id: 4740
        }
      }
      children {
        behavior {
          condition {
            use_chance: 30
          }
          enemy_skill_id: 4741
        }
      }
    }
  }
