  monster_id: 2699
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 2759
        }
      }
    }
    groups {
      group_type: DEATH
      condition {
        if_defeated: true
      }
      children {
        behavior {
          enemy_skill_id: 2767
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            group {
              condition {
                trigger_turn: 1
                always_trigger_above: 49
              }
              children {
                behavior {
                  enemy_skill_id: 2760
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 2
                always_trigger_above: 49
              }
              children {
                behavior {
                  condition {
                    use_chance: 50
                  }
                  enemy_skill_id: 2761
                }
              }
              children {
                behavior {
                  enemy_skill_id: 2762
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  enemy_skill_id: 2763
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 49
          }
          children {
            group {
              condition {
                trigger_turn: 1
              }
              children {
                behavior {
                  condition {
                    trigger_monsters: 2702
                    trigger_monsters: 2703
                  }
                  enemy_skill_id: 2859
                }
              }
              children {
                behavior {
                  enemy_skill_id: 2863
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 2
              }
              children {
                behavior {
                  enemy_skill_id: 2765
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  enemy_skill_id: 2766
                }
              }
            }
          }
        }
      }
    }
  }
