  monster_id: 2717
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          condition {
            use_chance: 17
          }
          enemy_skill_id: 4159
        }
      }
      children {
        behavior {
          condition {
            use_chance: 17
          }
          enemy_skill_id: 4160
        }
      }
      children {
        behavior {
          condition {
            use_chance: 17
          }
          enemy_skill_id: 4161
        }
      }
      children {
        behavior {
          condition {
            use_chance: 17
          }
          enemy_skill_id: 4162
        }
      }
      children {
        behavior {
          condition {
            use_chance: 16
          }
          enemy_skill_id: 4163
        }
      }
      children {
        behavior {
          condition {
            use_chance: 16
          }
          enemy_skill_id: 4164
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            behavior {
              condition {
                use_chance: 8
              }
              enemy_skill_id: 4171
            }
          }
          children {
            behavior {
              condition {
                use_chance: 8
              }
              enemy_skill_id: 4172
            }
          }
          children {
            behavior {
              condition {
                use_chance: 8
              }
              enemy_skill_id: 4173
            }
          }
          children {
            behavior {
              condition {
                use_chance: 8
              }
              enemy_skill_id: 4174
            }
          }
          children {
            behavior {
              condition {
                use_chance: 9
              }
              enemy_skill_id: 4175
            }
          }
          children {
            behavior {
              condition {
                use_chance: 9
              }
              enemy_skill_id: 4176
            }
          }
          children {
            behavior {
              condition {
                use_chance: 9
              }
              enemy_skill_id: 4177
            }
          }
          children {
            behavior {
              condition {
                use_chance: 9
              }
              enemy_skill_id: 4178
            }
          }
          children {
            behavior {
              condition {
                use_chance: 8
              }
              enemy_skill_id: 4179
            }
          }
          children {
            behavior {
              condition {
                use_chance: 8
              }
              enemy_skill_id: 4180
            }
          }
          children {
            behavior {
              condition {
                use_chance: 8
              }
              enemy_skill_id: 4181
            }
          }
          children {
            behavior {
              condition {
                use_chance: 8
              }
              enemy_skill_id: 4182
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 89
            trigger_turn: 1
            always_trigger_above: 9
          }
          children {
            behavior {
              enemy_skill_id: 4196
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 69
            trigger_turn: 2
            always_trigger_above: 9
          }
          children {
            behavior {
              enemy_skill_id: 4197
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 49
          }
          children {
            group {
              condition {
                trigger_turn: 3
                always_trigger_above: 9
              }
              children {
                behavior {
                  enemy_skill_id: 4198
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  enemy_skill_id: 4184
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 29
            trigger_turn: 4
            always_trigger_above: 9
          }
          children {
            behavior {
              enemy_skill_id: 4199
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 9
          }
          children {
            behavior {
              enemy_skill_id: 4200
            }
          }
        }
      }
    }
  }
