  monster_id: 277
  levels {
    level: 1
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 74
      }
      children {
        behavior {
          condition {
            use_chance: 75
          }
          enemy_skill_id: 258
        }
      }
    }
  }
