  monster_id: 2786
  levels {
    level: 4
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 3897
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            behavior {
              condition {
                use_chance: 75
              }
              enemy_skill_id: 3899
            }
          }
          children {
            behavior {
              condition {
                use_chance: 25
              }
              enemy_skill_id: 3898
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 59
          }
          children {
            behavior {
              condition {
                use_chance: 40
                global_one_time: true
              }
              enemy_skill_id: 3901
            }
          }
          children {
            behavior {
              condition {
                use_chance: 75
              }
              enemy_skill_id: 3899
            }
          }
          children {
            behavior {
              condition {
                use_chance: 25
              }
              enemy_skill_id: 3898
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 19
          }
          children {
            behavior {
              condition {
                use_chance: 40
                global_one_time: true
              }
              enemy_skill_id: 3901
            }
          }
          children {
            behavior {
              enemy_skill_id: 3900
            }
          }
        }
      }
    }
  }
