  monster_id: 2787
  levels {
    level: 4
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 3906
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            group {
              condition {
                repeats_every: 4
                trigger_turn: 1
              }
              children {
                behavior {
                  enemy_skill_id: 3915
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 4
                trigger_turn: 2
              }
              children {
                behavior {
                  condition {
                    use_chance: 20
                  }
                  enemy_skill_id: 3907
                }
              }
              children {
                behavior {
                  enemy_skill_id: 3914
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 4
                trigger_turn: 3
              }
              children {
                behavior {
                  condition {
                    use_chance: 20
                  }
                  enemy_skill_id: 3907
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 20
                  }
                  enemy_skill_id: 3907
                }
              }
              children {
                behavior {
                  enemy_skill_id: 3915
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 4
                trigger_turn: 4
              }
              children {
                behavior {
                  condition {
                    use_chance: 20
                  }
                  enemy_skill_id: 3907
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 20
                  }
                  enemy_skill_id: 3907
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 20
                  }
                  enemy_skill_id: 3907
                }
              }
              children {
                behavior {
                  enemy_skill_id: 3911
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 39
          }
          children {
            group {
              condition {
                repeats_every: 4
                trigger_turn: 1
              }
              children {
                behavior {
                  enemy_skill_id: 3915
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 4
                trigger_turn: 2
              }
              children {
                behavior {
                  condition {
                    use_chance: 20
                  }
                  enemy_skill_id: 3907
                }
              }
              children {
                behavior {
                  enemy_skill_id: 3914
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 4
                trigger_turn: 3
              }
              children {
                behavior {
                  condition {
                    use_chance: 20
                  }
                  enemy_skill_id: 3907
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 20
                  }
                  enemy_skill_id: 3907
                }
              }
              children {
                behavior {
                  enemy_skill_id: 3915
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 4
                trigger_turn: 4
              }
              children {
                behavior {
                  condition {
                    use_chance: 20
                  }
                  enemy_skill_id: 3907
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 20
                  }
                  enemy_skill_id: 3907
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 20
                  }
                  enemy_skill_id: 3907
                }
              }
              children {
                behavior {
                  enemy_skill_id: 3908
                }
              }
            }
          }
        }
      }
    }
  }
