  monster_id: 279
  levels {
    level: 1
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 59
      }
      children {
        behavior {
          enemy_skill_id: 259
        }
      }
    }
  }
