  monster_id: 2790
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 3985
        }
      }
    }
  }
  levels {
    level: 4
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 3983
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            group {
              condition {
                trigger_turn: 1
                always_trigger_above: 39
              }
              children {
                behavior {
                  enemy_skill_id: 3945
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 2
                always_trigger_above: 39
              }
              children {
                behavior {
                  enemy_skill_id: 3937
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 3
                always_trigger_above: 39
              }
              children {
                behavior {
                  enemy_skill_id: 3938
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 4
                always_trigger_above: 39
              }
              children {
                behavior {
                  enemy_skill_id: 3939
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 5
                always_trigger_above: 39
              }
              children {
                behavior {
                  enemy_skill_id: 3946
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 6
                always_trigger_above: 39
              }
              children {
                behavior {
                  enemy_skill_id: 3942
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 7
                always_trigger_above: 39
              }
              children {
                behavior {
                  enemy_skill_id: 3941
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 8
                always_trigger_above: 39
              }
              children {
                behavior {
                  enemy_skill_id: 3943
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 9
                always_trigger_above: 39
              }
              children {
                behavior {
                  enemy_skill_id: 3947
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  condition {
                    use_chance: 65
                  }
                  enemy_skill_id: 3948
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 20
                  }
                  enemy_skill_id: 3949
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 15
                  }
                  enemy_skill_id: 3950
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 39
            trigger_turn: 1
          }
          children {
            behavior {
              enemy_skill_id: 3947
            }
          }
        }
      }
    }
  }
