  monster_id: 2791
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 3966
        }
      }
    }
    groups {
      group_type: UNKNOWN_USE
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 3974
        }
      }
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 3978
        }
      }
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 3976
        }
      }
    }
  }
  levels {
    level: 4
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 3967
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          condition {
            trigger_turn: 1
            always_trigger_above: 1
          }
          children {
            behavior {
              enemy_skill_id: 3957
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 2
            always_trigger_above: 1
          }
          children {
            behavior {
              enemy_skill_id: 3958
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 6
            always_trigger_above: 1
          }
          children {
            behavior {
              enemy_skill_id: 3981
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 7
            always_trigger_above: 1
          }
          children {
            behavior {
              enemy_skill_id: 3970
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 8
            always_trigger_above: 1
          }
          children {
            behavior {
              enemy_skill_id: 3963
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            group {
              condition {
                trigger_turn: 3
                always_trigger_above: 59
              }
              children {
                behavior {
                  enemy_skill_id: 3968
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 4
                always_trigger_above: 59
              }
              children {
                behavior {
                  enemy_skill_id: 3956
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 50
                  }
                  enemy_skill_id: 3979
                }
              }
              children {
                behavior {
                  enemy_skill_id: 3980
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 5
                always_trigger_above: 59
              }
              children {
                behavior {
                  enemy_skill_id: 3969
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  enemy_skill_id: 3959
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 59
          }
          children {
            group {
              condition {
                trigger_turn: 3
              }
              children {
                behavior {
                  enemy_skill_id: 3973
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 4
              }
              children {
                behavior {
                  enemy_skill_id: 3977
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 5
              }
              children {
                behavior {
                  enemy_skill_id: 3975
                }
              }
            }
          }
        }
      }
    }
    groups {
      group_type: UNKNOWN_USE
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 3974
        }
      }
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 3978
        }
      }
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 3976
        }
      }
    }
  }
