  monster_id: 2879
  levels {
    level: 1
    groups {
      group_type: PASSIVE
      children {
        behavior {
          enemy_skill_id: 4702
        }
      }
    }
  }
  levels {
    level: 4
    groups {
      group_type: PASSIVE
      children {
        behavior {
          enemy_skill_id: 4702
        }
      }
    }
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 4687
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            group {
              condition {
                trigger_turn: 1
                always_trigger_above: 49
              }
              children {
                behavior {
                  condition {
                    trigger_monsters: 1948
                    trigger_monsters: 1949
                    trigger_monsters: 2745
                  }
                  enemy_skill_id: 4692
                }
              }
              children {
                behavior {
                  enemy_skill_id: 4693
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  condition {
                    use_chance: 30
                  }
                  enemy_skill_id: 4691
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 50
                  }
                  enemy_skill_id: 4694
                }
              }
              children {
                behavior {
                  enemy_skill_id: 4695
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 74
            trigger_turn: 2
            always_trigger_above: 49
          }
          children {
            behavior {
              enemy_skill_id: 4693
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 49
          }
          children {
            group {
              condition {
                trigger_turn: 1
                always_trigger_above: 19
              }
              children {
                behavior {
                  enemy_skill_id: 4700
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  condition {
                    use_chance: 50
                  }
                  enemy_skill_id: 4696
                }
              }
              children {
                behavior {
                  enemy_skill_id: 4697
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 19
          }
          children {
            group {
              condition {
                trigger_turn: 1
              }
              children {
                behavior {
                  enemy_skill_id: 4382
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  enemy_skill_id: 4701
                }
              }
            }
          }
        }
      }
    }
  }
