  monster_id: 2885
  levels {
    level: 1
    groups {
      group_type: PASSIVE
      children {
        behavior {
          enemy_skill_id: 4486
        }
      }
    }
  }
  levels {
    level: 4
    groups {
      group_type: PASSIVE
      children {
        behavior {
          enemy_skill_id: 4486
        }
      }
    }
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 4488
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 9
      }
      children {
        behavior {
          enemy_skill_id: 4487
        }
      }
    }
  }
