  monster_id: 2897
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 7092
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        group {
          condition {
            trigger_turn: 1
          }
          children {
            behavior {
              condition {
                trigger_combos: 4
              }
              enemy_skill_id: 7096
            }
          }
          children {
            behavior {
              enemy_skill_id: 7115
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 2
          }
          children {
            behavior {
              condition {
                trigger_combos: 5
              }
              enemy_skill_id: 7100
            }
          }
          children {
            behavior {
              enemy_skill_id: 7115
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 3
          }
          children {
            behavior {
              condition {
                trigger_combos: 6
              }
              enemy_skill_id: 7104
            }
          }
          children {
            behavior {
              enemy_skill_id: 7115
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 4
          }
          children {
            behavior {
              condition {
                trigger_combos: 7
              }
              enemy_skill_id: 7107
            }
          }
          children {
            behavior {
              enemy_skill_id: 7115
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 5
          }
          children {
            behavior {
              condition {
                trigger_combos: 8
              }
              enemy_skill_id: 7111
            }
          }
          children {
            behavior {
              enemy_skill_id: 7116
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 6
          }
          children {
            behavior {
              condition {
                trigger_combos: 9
              }
              enemy_skill_id: 7114
            }
          }
          children {
            behavior {
              enemy_skill_id: 7116
            }
          }
        }
      }
      children {
        group {
          children {
            behavior {
              enemy_skill_id: 7116
            }
          }
        }
      }
    }
  }
