  monster_id: 2917
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 14161
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        group {
          condition {
            trigger_turn: 1
          }
          children {
            behavior {
              condition {
                trigger_combos: 1
              }
              enemy_skill_id: 14180
            }
          }
          children {
            behavior {
              enemy_skill_id: 14165
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 2
          }
          children {
            behavior {
              condition {
                trigger_combos: 1
              }
              enemy_skill_id: 14180
            }
          }
          children {
            behavior {
              enemy_skill_id: 14168
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 3
          }
          children {
            behavior {
              condition {
                trigger_combos: 1
              }
              enemy_skill_id: 14180
            }
          }
          children {
            behavior {
              enemy_skill_id: 14172
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 4
          }
          children {
            behavior {
              condition {
                trigger_combos: 1
              }
              enemy_skill_id: 14180
            }
          }
          children {
            behavior {
              enemy_skill_id: 14175
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 5
          }
          children {
            behavior {
              condition {
                trigger_combos: 10
              }
              enemy_skill_id: 14179
            }
          }
          children {
            behavior {
              condition {
                trigger_combos: 1
              }
              enemy_skill_id: 14180
            }
          }
        }
      }
      children {
        group {
          children {
            behavior {
              condition {
                trigger_combos: 10
              }
              enemy_skill_id: 14179
            }
          }
        }
      }
    }
  }
