  monster_id: 2935
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 4615
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            behavior {
              enemy_skill_id: 4616
            }
          }
          children {
            behavior {
              enemy_skill_id: 4617
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 49
          }
          children {
            group {
              condition {
                trigger_turn: 1
              }
              children {
                behavior {
                  enemy_skill_id: 4618
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  enemy_skill_id: 4619
                }
              }
            }
          }
        }
      }
    }
  }
