  monster_id: 2938
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 4620
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 101
          }
          children {
            behavior {
              enemy_skill_id: 4621
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 99
          }
          children {
            behavior {
              enemy_skill_id: 4623
            }
          }
          children {
            behavior {
              enemy_skill_id: 4622
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 59
            trigger_turn: 1
            always_trigger_above: 1
          }
          children {
            behavior {
              enemy_skill_id: 4624
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 29
          }
          children {
            group {
              condition {
                trigger_turn: 2
              }
              children {
                behavior {
                  enemy_skill_id: 4625
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  enemy_skill_id: 4626
                }
              }
            }
          }
        }
      }
    }
  }
