  monster_id: 300650
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 325
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          condition {
            trigger_turn: 1
            always_trigger_above: 1
          }
          children {
            behavior {
              enemy_skill_id: 90
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 69
          }
          children {
            behavior {
              condition {
                use_chance: 75
              }
              enemy_skill_id: 326
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 49
            trigger_turn: 2
            always_trigger_above: 29
          }
          children {
            behavior {
              enemy_skill_id: 328
            }
          }
          children {
            behavior {
              condition {
                use_chance: 75
              }
              enemy_skill_id: 326
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 29
          }
          children {
            group {
              condition {
                trigger_turn: 2
              }
              children {
                behavior {
                  enemy_skill_id: 328
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  condition {
                    use_chance: 75
                  }
                  enemy_skill_id: 327
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 75
                  }
                  enemy_skill_id: 326
                }
              }
            }
          }
        }
      }
    }
  }
