  monster_id: 300785
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 25499
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        group {
          condition {
            trigger_turn: 1
            trigger_turn_end: 4
          }
          children {
            behavior {
              enemy_skill_id: 600
            }
          }
        }
      }
      children {
        group {
          children {
            behavior {
              enemy_skill_id: 25621
            }
          }
        }
      }
    }
  }
