  monster_id: 302082
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 10152
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          condition {
            trigger_turn: 1
            always_trigger_above: 1
          }
          children {
            behavior {
              enemy_skill_id: 13549
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            behavior {
              enemy_skill_id: 10147
            }
          }
          children {
            behavior {
              enemy_skill_id: 10148
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 19
          }
          children {
            group {
              condition {
                trigger_turn: 2
              }
              children {
                behavior {
                  condition {
                    use_chance: 50
                  }
                  enemy_skill_id: 10146
                }
              }
              children {
                behavior {
                  enemy_skill_id: 10145
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  enemy_skill_id: 10144
                }
              }
            }
          }
        }
      }
    }
  }
