  monster_id: 302337
  levels {
    level: 1
    groups {
      group_type: PASSIVE
      children {
        behavior {
          enemy_skill_id: 44521
        }
      }
    }
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 44513
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        group {
          condition {
            trigger_turn: 2
          }
          children {
            behavior {
              enemy_skill_id: 44515
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 4
          }
          children {
            behavior {
              enemy_skill_id: 44515
            }
          }
        }
      }
      children {
        group {
          children {
            behavior {
              enemy_skill_id: 44526
            }
          }
        }
      }
    }
    groups {
      group_type: REMAINING
      condition {
        hp_threshold: 100
        trigger_enemies_remaining: 2
      }
      children {
        group {
          condition {
            trigger_turn: 1
          }
          children {
            behavior {
              enemy_skill_id: 44528
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 2
            trigger_turn_end: 5
          }
          children {
            behavior {
              enemy_skill_id: 44503
            }
          }
        }
      }
    }
  }
