  monster_id: 302547
  levels {
    level: 4
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            behavior {
              enemy_skill_id: 3689
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 29
            trigger_turn: 1
          }
          children {
            behavior {
              enemy_skill_id: 3690
            }
          }
        }
      }
    }
  }
