  monster_id: 302656
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 28503
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        group {
          condition {
            trigger_turn: 1
            trigger_turn_end: 5
          }
          children {
            behavior {
              condition {
                use_chance: 50
              }
              enemy_skill_id: 28504
            }
          }
          children {
            behavior {
              condition {
                use_chance: 50
              }
              enemy_skill_id: 28505
            }
          }
        }
      }
      children {
        group {
          children {
            behavior {
              enemy_skill_id: 28954
            }
          }
        }
      }
    }
  }
