  monster_id: 303382
  levels {
    level: 4
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 6191
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        group {
          condition {
            repeats_every: 2
            trigger_turn: 1
          }
          children {
            behavior {
              enemy_skill_id: 6187
            }
          }
        }
      }
      children {
        group {
          condition {
            repeats_every: 2
            trigger_turn: 2
          }
          children {
            behavior {
              enemy_skill_id: 6188
            }
          }
        }
      }
    }
  }
