  monster_id: 304010
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 18087
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        group {
          condition {
            trigger_turn: 1
            trigger_turn_end: 4
          }
          children {
            behavior {
              enemy_skill_id: 18082
            }
          }
          children {
            behavior {
              condition {
                use_chance: 33
              }
              enemy_skill_id: 18090
            }
          }
          children {
            behavior {
              condition {
                use_chance: 34
              }
              enemy_skill_id: 18091
            }
          }
          children {
            behavior {
              condition {
                use_chance: 33
              }
              enemy_skill_id: 18092
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 5
          }
          children {
            behavior {
              enemy_skill_id: 18082
            }
          }
          children {
            behavior {
              enemy_skill_id: 18112
            }
          }
        }
      }
      children {
        group {
          children {
            behavior {
              enemy_skill_id: 18082
            }
          }
          children {
            behavior {
              condition {
                use_chance: 33
              }
              enemy_skill_id: 18090
            }
          }
          children {
            behavior {
              condition {
                use_chance: 34
              }
              enemy_skill_id: 18091
            }
          }
          children {
            behavior {
              condition {
                use_chance: 33
              }
              enemy_skill_id: 18092
            }
          }
        }
      }
    }
  }
