  monster_id: 304271
  levels {
    level: 1
    groups {
      group_type: PASSIVE
      children {
        behavior {
          enemy_skill_id: 29722
        }
      }
    }
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 32516
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        group {
          condition {
            trigger_turn: 1
          }
          children {
            behavior {
              enemy_skill_id: 32520
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 2
            trigger_turn_end: 5
          }
          children {
            behavior {
              condition {
                use_chance: 50
              }
              enemy_skill_id: 32524
            }
          }
          children {
            behavior {
              condition {
                use_chance: 50
              }
              enemy_skill_id: 32527
            }
          }
        }
      }
      children {
        group {
          children {
            behavior {
              enemy_skill_id: 29723
            }
          }
        }
      }
    }
    groups {
      group_type: UNKNOWN_USE
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 32530
        }
      }
    }
  }
