  monster_id: 304244
  levels {
    level: 1
    groups {
      group_type: PASSIVE
      children {
        behavior {
          enemy_skill_id: 18022
        }
      }
      children {
        behavior {
          enemy_skill_id: 18022
        }
      }
    }
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 18023
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            behavior {
              enemy_skill_id: 18025
            }
          }
          children {
            behavior {
              enemy_skill_id: 18024
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 9
          }
          children {
            group {
              condition {
                trigger_turn: 1
              }
              children {
                behavior {
                  enemy_skill_id: 18026
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  enemy_skill_id: 18027
                }
              }
            }
          }
        }
      }
    }
  }
