  monster_id: 305431
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 40006
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            group {
              condition {
                trigger_turn: 1
                trigger_turn_end: 6
                always_trigger_above: 98
              }
              children {
                behavior {
                  enemy_skill_id: 40010
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  enemy_skill_id: 39739
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 98
            trigger_turn: 1
          }
          children {
            behavior {
              enemy_skill_id: 40009
            }
          }
        }
      }
    }
  }
