  monster_id: 3056
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 23173
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            group {
              condition {
                trigger_turn: 1
                trigger_turn_end: 2
                always_trigger_above: 9
              }
              children {
                behavior {
                  condition {
                    use_chance: 33
                  }
                  enemy_skill_id: 23184
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 33
                  }
                  enemy_skill_id: 23185
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 34
                  }
                  enemy_skill_id: 23186
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 3
                always_trigger_above: 9
              }
              children {
                behavior {
                  enemy_skill_id: 23177
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 4
                trigger_turn_end: 5
                always_trigger_above: 9
              }
              children {
                behavior {
                  condition {
                    use_chance: 33
                  }
                  enemy_skill_id: 23184
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 33
                  }
                  enemy_skill_id: 23185
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 34
                  }
                  enemy_skill_id: 23186
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 6
                always_trigger_above: 9
              }
              children {
                behavior {
                  enemy_skill_id: 23179
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 7
                trigger_turn_end: 8
                always_trigger_above: 9
              }
              children {
                behavior {
                  condition {
                    use_chance: 33
                  }
                  enemy_skill_id: 23184
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 33
                  }
                  enemy_skill_id: 23185
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 34
                  }
                  enemy_skill_id: 23186
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 9
                always_trigger_above: 9
              }
              children {
                behavior {
                  enemy_skill_id: 23181
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  condition {
                    use_chance: 33
                  }
                  enemy_skill_id: 23184
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 33
                  }
                  enemy_skill_id: 23185
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 34
                  }
                  enemy_skill_id: 23186
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 9
          }
          children {
            behavior {
              enemy_skill_id: 23187
            }
          }
        }
      }
    }
  }
