  monster_id: 305932
  levels {
    level: 1
    groups {
      group_type: PASSIVE
      children {
        behavior {
          enemy_skill_id: 22319
        }
      }
      children {
        behavior {
          enemy_skill_id: 33923
        }
      }
    }
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 22320
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            group {
              condition {
                trigger_turn: 1
                always_trigger_above: 4
              }
              children {
                behavior {
                  enemy_skill_id: 22323
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 2
                always_trigger_above: 4
              }
              children {
                behavior {
                  enemy_skill_id: 22326
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 3
                always_trigger_above: 4
              }
              children {
                behavior {
                  enemy_skill_id: 22329
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 4
                always_trigger_above: 4
              }
              children {
                behavior {
                  enemy_skill_id: 22332
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 5
                always_trigger_above: 4
              }
              children {
                behavior {
                  enemy_skill_id: 22335
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 6
                always_trigger_above: 4
              }
              children {
                behavior {
                  enemy_skill_id: 22323
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 7
                always_trigger_above: 4
              }
              children {
                behavior {
                  enemy_skill_id: 22326
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 8
                always_trigger_above: 4
              }
              children {
                behavior {
                  enemy_skill_id: 22329
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 9
                always_trigger_above: 4
              }
              children {
                behavior {
                  enemy_skill_id: 22332
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 10
                always_trigger_above: 4
              }
              children {
                behavior {
                  enemy_skill_id: 22335
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 11
                always_trigger_above: 4
              }
              children {
                behavior {
                  enemy_skill_id: 22323
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 12
                always_trigger_above: 4
              }
              children {
                behavior {
                  enemy_skill_id: 22326
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 13
                always_trigger_above: 4
              }
              children {
                behavior {
                  enemy_skill_id: 22329
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 14
                always_trigger_above: 4
              }
              children {
                behavior {
                  enemy_skill_id: 22332
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  enemy_skill_id: 22200
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 4
            repeats_every: 7
            trigger_turn: 1
            trigger_turn_end: 7
          }
          children {
            behavior {
              enemy_skill_id: 22337
            }
          }
        }
      }
    }
  }
