  monster_id: 305945
  levels {
    level: 1
    groups {
      group_type: PASSIVE
      children {
        behavior {
          enemy_skill_id: 45384
        }
      }
    }
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 45346
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        behavior {
          condition {
            use_chance: 20
          }
          enemy_skill_id: 45350
        }
      }
      children {
        behavior {
          condition {
            use_chance: 20
          }
          enemy_skill_id: 45354
        }
      }
      children {
        behavior {
          condition {
            use_chance: 20
          }
          enemy_skill_id: 45358
        }
      }
      children {
        behavior {
          condition {
            use_chance: 20
          }
          enemy_skill_id: 45362
        }
      }
      children {
        behavior {
          condition {
            use_chance: 20
          }
          enemy_skill_id: 45366
        }
      }
    }
  }
