  monster_id: 3062
  levels {
    level: 1
    groups {
      group_type: PASSIVE
      children {
        behavior {
          enemy_skill_id: 26188
        }
      }
      children {
        behavior {
          enemy_skill_id: 26121
        }
      }
    }
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 26173
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            group {
              condition {
                trigger_turn: 1
                trigger_turn_end: 6
                always_trigger_above: 49
              }
              children {
                behavior {
                  condition {
                    use_chance: 50
                  }
                  enemy_skill_id: 26184
                }
              }
              children {
                behavior {
                  enemy_skill_id: 26186
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 7
                always_trigger_above: 19
              }
              children {
                behavior {
                  enemy_skill_id: 26105
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  condition {
                    use_chance: 50
                  }
                  enemy_skill_id: 26184
                }
              }
              children {
                behavior {
                  enemy_skill_id: 26186
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 49
          }
          children {
            group {
              condition {
                trigger_turn: 1
                always_trigger_above: 19
              }
              children {
                behavior {
                  enemy_skill_id: 26177
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 2
                always_trigger_above: 19
              }
              children {
                behavior {
                  enemy_skill_id: 26179
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 3
                always_trigger_above: 19
              }
              children {
                behavior {
                  enemy_skill_id: 26182
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 4
                always_trigger_above: 19
              }
              children {
                behavior {
                  enemy_skill_id: 26179
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 5
                always_trigger_above: 19
              }
              children {
                behavior {
                  enemy_skill_id: 26182
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 6
                always_trigger_above: 19
              }
              children {
                behavior {
                  enemy_skill_id: 26179
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 2
                trigger_turn: 1
              }
              children {
                behavior {
                  enemy_skill_id: 26179
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 2
                trigger_turn: 2
              }
              children {
                behavior {
                  enemy_skill_id: 26182
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 19
          }
          children {
            group {
              condition {
                trigger_turn: 1
              }
              children {
                behavior {
                  enemy_skill_id: 26103
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  enemy_skill_id: 26176
                }
              }
            }
          }
        }
      }
    }
  }
