  monster_id: 306251
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          condition {
            trigger_monsters: 2957
          }
          enemy_skill_id: 24879
        }
      }
      children {
        behavior {
          enemy_skill_id: 24816
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            behavior {
              condition {
                use_chance: 50
              }
              enemy_skill_id: 24820
            }
          }
          children {
            behavior {
              enemy_skill_id: 24822
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 49
          }
          children {
            behavior {
              condition {
                use_chance: 50
              }
              enemy_skill_id: 24824
            }
          }
          children {
            behavior {
              enemy_skill_id: 24826
            }
          }
        }
      }
    }
  }
