  monster_id: 307725
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 28074
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        group {
          condition {
            trigger_turn: 1
          }
          children {
            behavior {
              enemy_skill_id: 28075
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 2
          }
          children {
            behavior {
              enemy_skill_id: 28076
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 3
            trigger_turn_end: 5
          }
          children {
            behavior {
              enemy_skill_id: 28078
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 6
          }
          children {
            behavior {
              enemy_skill_id: 28079
            }
          }
        }
      }
      children {
        group {
          children {
            behavior {
              enemy_skill_id: 28080
            }
          }
        }
      }
    }
    groups {
      group_type: UNKNOWN_USE
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 28077
        }
      }
    }
  }
