  monster_id: 307919
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 30008
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        group {
          condition {
            trigger_turn: 1
          }
          children {
            behavior {
              enemy_skill_id: 30442
            }
          }
          children {
            behavior {
              enemy_skill_id: 30010
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 2
          }
          children {
            behavior {
              enemy_skill_id: 30443
            }
          }
          children {
            behavior {
              enemy_skill_id: 30012
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 3
          }
          children {
            behavior {
              enemy_skill_id: 29996
            }
          }
          children {
            behavior {
              enemy_skill_id: 30014
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 4
          }
          children {
            behavior {
              enemy_skill_id: 29996
            }
          }
          children {
            behavior {
              enemy_skill_id: 30016
            }
          }
        }
      }
      children {
        group {
          children {
            behavior {
              enemy_skill_id: 29996
            }
          }
          children {
            behavior {
              enemy_skill_id: 29994
            }
          }
        }
      }
    }
    groups {
      group_type: UNKNOWN_USE
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 30444
        }
      }
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 30445
        }
      }
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 30446
        }
      }
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 30449
        }
      }
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 30450
        }
      }
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 30451
        }
      }
    }
  }
  levels {
    level: 4
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 30019
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        group {
          condition {
            trigger_turn: 1
          }
          children {
            behavior {
              enemy_skill_id: 30447
            }
          }
          children {
            behavior {
              enemy_skill_id: 30021
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 2
          }
          children {
            behavior {
              enemy_skill_id: 30448
            }
          }
          children {
            behavior {
              enemy_skill_id: 30023
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 3
          }
          children {
            behavior {
              enemy_skill_id: 29996
            }
          }
          children {
            behavior {
              enemy_skill_id: 30025
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 4
          }
          children {
            behavior {
              enemy_skill_id: 29996
            }
          }
          children {
            behavior {
              enemy_skill_id: 30027
            }
          }
        }
      }
      children {
        group {
          children {
            behavior {
              enemy_skill_id: 29996
            }
          }
          children {
            behavior {
              enemy_skill_id: 29994
            }
          }
        }
      }
    }
    groups {
      group_type: UNKNOWN_USE
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 30444
        }
      }
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 30445
        }
      }
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 30446
        }
      }
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 30449
        }
      }
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 30450
        }
      }
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 30451
        }
      }
    }
  }
