  monster_id: 308625
  levels {
    level: 1
    groups {
      group_type: PASSIVE
      children {
        behavior {
          enemy_skill_id: 35452
        }
      }
    }
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 35444
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        group {
          condition {
            trigger_turn: 1
          }
          children {
            behavior {
              enemy_skill_id: 35448
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 2
          }
          children {
            behavior {
              enemy_skill_id: 35449
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 3
          }
          children {
            behavior {
              enemy_skill_id: 35450
            }
          }
        }
      }
      children {
        group {
          children {
            behavior {
              enemy_skill_id: 35451
            }
          }
        }
      }
    }
  }
