  monster_id: 3092
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 5217
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            behavior {
              enemy_skill_id: 5220
            }
          }
          children {
            behavior {
              enemy_skill_id: 5221
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 49
          }
          children {
            behavior {
              enemy_skill_id: 5220
            }
          }
          children {
            behavior {
              enemy_skill_id: 5222
            }
          }
        }
      }
    }
  }
