  monster_id: 3117
  levels {
    level: 1
    groups {
      group_type: STANDARD
      children {
        group {
          condition {
            trigger_turn: 1
            always_trigger_above: 1
          }
          children {
            behavior {
              enemy_skill_id: 14263
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            behavior {
              condition {
                use_chance: 50
              }
              enemy_skill_id: 14264
            }
          }
          children {
            behavior {
              enemy_skill_id: 14265
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 29
          }
          children {
            behavior {
              condition {
                use_chance: 30
              }
              enemy_skill_id: 14266
            }
          }
          children {
            behavior {
              condition {
                use_chance: 50
              }
              enemy_skill_id: 14264
            }
          }
          children {
            behavior {
              enemy_skill_id: 14265
            }
          }
        }
      }
    }
  }
  levels {
    level: 4
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 14263
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            behavior {
              condition {
                use_chance: 50
              }
              enemy_skill_id: 14264
            }
          }
          children {
            behavior {
              enemy_skill_id: 14265
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 29
          }
          children {
            behavior {
              condition {
                use_chance: 30
              }
              enemy_skill_id: 14266
            }
          }
          children {
            behavior {
              condition {
                use_chance: 50
              }
              enemy_skill_id: 14264
            }
          }
          children {
            behavior {
              enemy_skill_id: 14265
            }
          }
        }
      }
    }
  }
