  monster_id: 3154
  levels {
    level: 1
    groups {
      group_type: PASSIVE
      children {
        behavior {
          enemy_skill_id: 5374
        }
      }
    }
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 5353
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            group {
              condition {
                repeats_every: 2
                trigger_turn: 1
              }
              children {
                behavior {
                  enemy_skill_id: 5354
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 2
                trigger_turn: 2
              }
              children {
                behavior {
                  condition {
                    use_chance: 20
                  }
                  enemy_skill_id: 5355
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 20
                  }
                  enemy_skill_id: 5356
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 20
                  }
                  enemy_skill_id: 5357
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 20
                  }
                  enemy_skill_id: 5358
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 20
                  }
                  enemy_skill_id: 5359
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 69
            trigger_turn: 1
            always_trigger_above: 1
          }
          children {
            behavior {
              enemy_skill_id: 5360
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 9
          }
          children {
            behavior {
              enemy_skill_id: 5361
            }
          }
        }
      }
    }
  }
