  monster_id: 3159
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 5395
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        group {
          condition {
            trigger_turn: 1
          }
          children {
            behavior {
              enemy_skill_id: 5398
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 2
          }
          children {
            behavior {
              condition {
                if_attributes_available: true
              }
              enemy_skill_id: 5408
            }
          }
          children {
            behavior {
              enemy_skill_id: 5488
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 3
          }
          children {
            behavior {
              enemy_skill_id: 5414
            }
          }
          children {
            behavior {
              enemy_skill_id: 5401
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 4
          }
          children {
            behavior {
              enemy_skill_id: 5401
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 5
          }
          children {
            behavior {
              condition {
                if_attributes_available: true
              }
              enemy_skill_id: 5409
            }
          }
          children {
            behavior {
              enemy_skill_id: 5489
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 6
          }
          children {
            behavior {
              enemy_skill_id: 5412
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 7
          }
          children {
            behavior {
              enemy_skill_id: 5404
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 8
          }
          children {
            behavior {
              condition {
                if_attributes_available: true
              }
              enemy_skill_id: 5410
            }
          }
          children {
            behavior {
              enemy_skill_id: 5490
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 9
          }
          children {
            behavior {
              enemy_skill_id: 5415
            }
          }
        }
      }
      children {
        group {
          children {
            behavior {
              enemy_skill_id: 5416
            }
          }
        }
      }
    }
  }
  levels {
    level: 6
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 5395
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        group {
          condition {
            trigger_turn: 1
          }
          children {
            behavior {
              enemy_skill_id: 5398
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 2
          }
          children {
            behavior {
              condition {
                if_attributes_available: true
              }
              enemy_skill_id: 5408
            }
          }
          children {
            behavior {
              enemy_skill_id: 5488
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 3
          }
          children {
            behavior {
              enemy_skill_id: 5414
            }
          }
          children {
            behavior {
              enemy_skill_id: 5401
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 4
          }
          children {
            behavior {
              enemy_skill_id: 5401
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 5
          }
          children {
            behavior {
              condition {
                if_attributes_available: true
              }
              enemy_skill_id: 5409
            }
          }
          children {
            behavior {
              enemy_skill_id: 5489
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 6
          }
          children {
            behavior {
              enemy_skill_id: 5413
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 7
          }
          children {
            behavior {
              enemy_skill_id: 5404
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 8
          }
          children {
            behavior {
              condition {
                if_attributes_available: true
              }
              enemy_skill_id: 5410
            }
          }
          children {
            behavior {
              enemy_skill_id: 5490
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 9
          }
          children {
            behavior {
              enemy_skill_id: 5415
            }
          }
        }
      }
      children {
        group {
          children {
            behavior {
              enemy_skill_id: 5416
            }
          }
        }
      }
    }
  }
