  monster_id: 3170
  levels {
    level: 4
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 5617
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          condition {
            trigger_turn: 1
            always_trigger_above: 1
          }
          children {
            behavior {
              enemy_skill_id: 5618
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            behavior {
              enemy_skill_id: 5620
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 48
            trigger_turn: 2
          }
          children {
            behavior {
              enemy_skill_id: 5619
            }
          }
        }
      }
    }
  }
