  monster_id: 3210
  levels {
    level: 1
    groups {
      group_type: PASSIVE
      children {
        behavior {
          enemy_skill_id: 5689
        }
      }
    }
  }
  levels {
    level: 4
    groups {
      group_type: PASSIVE
      children {
        behavior {
          enemy_skill_id: 5689
        }
      }
    }
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 5677
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            group {
              condition {
                trigger_turn: 1
                always_trigger_above: 69
              }
              children {
                behavior {
                  enemy_skill_id: 5680
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  condition {
                    use_chance: 40
                  }
                  enemy_skill_id: 5686
                }
              }
              children {
                behavior {
                  enemy_skill_id: 5687
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 69
          }
          children {
            group {
              condition {
                trigger_turn: 1
                always_trigger_above: 9
              }
              children {
                behavior {
                  enemy_skill_id: 5681
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 3
                trigger_turn: 1
              }
              children {
                behavior {
                  enemy_skill_id: 5688
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 40
                  }
                  enemy_skill_id: 5686
                }
              }
              children {
                behavior {
                  enemy_skill_id: 5687
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 3
                trigger_turn: 2
                trigger_turn_end: 3
              }
              children {
                behavior {
                  condition {
                    use_chance: 40
                  }
                  enemy_skill_id: 5686
                }
              }
              children {
                behavior {
                  enemy_skill_id: 5687
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 9
          }
          children {
            group {
              condition {
                trigger_turn: 1
              }
              children {
                behavior {
                  enemy_skill_id: 5682
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  enemy_skill_id: 5685
                }
              }
            }
          }
        }
      }
    }
  }
