  monster_id: 3237
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 8812
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            behavior {
              condition {
                use_chance: 50
              }
              enemy_skill_id: 8815
            }
          }
          children {
            behavior {
              enemy_skill_id: 8814
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 69
            trigger_turn: 1
            always_trigger_above: 1
          }
          children {
            behavior {
              enemy_skill_id: 8813
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 39
          }
          children {
            behavior {
              condition {
                use_chance: 30
              }
              enemy_skill_id: 8816
            }
          }
          children {
            behavior {
              enemy_skill_id: 8817
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 19
            trigger_turn: 2
          }
          children {
            behavior {
              enemy_skill_id: 8818
            }
          }
        }
      }
    }
  }
