  monster_id: 3361
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 17472
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            group {
              condition {
                repeats_every: 4
                trigger_turn: 1
              }
              children {
                behavior {
                  enemy_skill_id: 17475
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 4
                trigger_turn: 2
                trigger_turn_end: 4
              }
              children {
                behavior {
                  enemy_skill_id: 17473
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 39
          }
          children {
            group {
              condition {
                trigger_turn: 1
              }
              children {
                behavior {
                  enemy_skill_id: 17474
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  enemy_skill_id: 17476
                }
              }
            }
          }
        }
      }
    }
  }
