  monster_id: 3453
  levels {
    level: 1
    groups {
      group_type: PASSIVE
      children {
        behavior {
          enemy_skill_id: 27606
        }
      }
    }
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 27578
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            group {
              condition {
                trigger_turn: 1
                trigger_turn_end: 4
                always_trigger_above: 49
              }
              children {
                behavior {
                  condition {
                    use_chance: 50
                  }
                  enemy_skill_id: 27600
                }
              }
              children {
                behavior {
                  enemy_skill_id: 27603
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 5
                always_trigger_above: 14
              }
              children {
                behavior {
                  enemy_skill_id: 27590
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  condition {
                    use_chance: 50
                  }
                  enemy_skill_id: 27600
                }
              }
              children {
                behavior {
                  enemy_skill_id: 27603
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 49
          }
          children {
            behavior {
              condition {
                use_chance: 50
              }
              enemy_skill_id: 27594
            }
          }
          children {
            behavior {
              enemy_skill_id: 27597
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 14
          }
          children {
            group {
              condition {
                trigger_turn: 1
              }
              children {
                behavior {
                  enemy_skill_id: 27586
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  enemy_skill_id: 27589
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 1
          }
          children {
            behavior {
              enemy_skill_id: 27582
            }
          }
        }
      }
    }
  }
