  monster_id: 347
  levels {
    level: 1
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            behavior {
              condition {
                use_chance: 10
              }
              enemy_skill_id: 97
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 39
          }
          children {
            behavior {
              condition {
                use_chance: 60
                global_one_time: true
              }
              enemy_skill_id: 81
            }
          }
          children {
            behavior {
              condition {
                use_chance: 10
              }
              enemy_skill_id: 97
            }
          }
        }
      }
    }
  }
