  monster_id: 3503
  levels {
    level: 1
    groups {
      group_type: PASSIVE
      children {
        behavior {
          enemy_skill_id: 20311
        }
      }
    }
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 20312
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            group {
              condition {
                trigger_turn: 1
                trigger_turn_end: 2
                always_trigger_above: 49
              }
              children {
                behavior {
                  enemy_skill_id: 20300
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 3
                always_trigger_above: 49
              }
              children {
                behavior {
                  enemy_skill_id: 20304
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  enemy_skill_id: 20307
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 49
            trigger_turn: 1
            always_trigger_above: 24
          }
          children {
            behavior {
              enemy_skill_id: 20304
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 24
          }
          children {
            group {
              condition {
                repeats_every: 2
                trigger_turn: 1
              }
              children {
                behavior {
                  enemy_skill_id: 20309
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 2
                trigger_turn: 2
              }
              children {
                behavior {
                  enemy_skill_id: 20310
                }
              }
            }
          }
        }
      }
    }
  }
  levels {
    level: 6
    groups {
      group_type: PASSIVE
      children {
        behavior {
          enemy_skill_id: 20311
        }
      }
    }
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 20296
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            group {
              condition {
                trigger_turn: 1
                trigger_turn_end: 2
                always_trigger_above: 49
              }
              children {
                behavior {
                  enemy_skill_id: 20300
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 3
                always_trigger_above: 49
              }
              children {
                behavior {
                  enemy_skill_id: 20304
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  enemy_skill_id: 20307
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 49
            trigger_turn: 1
            always_trigger_above: 24
          }
          children {
            behavior {
              enemy_skill_id: 20304
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 24
          }
          children {
            group {
              condition {
                repeats_every: 2
                trigger_turn: 1
              }
              children {
                behavior {
                  enemy_skill_id: 20309
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 2
                trigger_turn: 2
              }
              children {
                behavior {
                  enemy_skill_id: 20310
                }
              }
            }
          }
        }
      }
    }
  }
