  monster_id: 3506
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 15661
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        group {
          condition {
            trigger_turn: 1
          }
          children {
            behavior {
              condition {
                trigger_combos: 10
              }
              enemy_skill_id: 15666
            }
          }
          children {
            behavior {
              enemy_skill_id: 15669
            }
          }
          children {
            behavior {
              enemy_skill_id: 15670
            }
          }
        }
      }
      children {
        group {
          children {
            behavior {
              enemy_skill_id: 15671
            }
          }
        }
      }
    }
  }
