  monster_id: 3539
  levels {
    level: 1
    groups {
      group_type: PASSIVE
      children {
        behavior {
          enemy_skill_id: 6923
        }
      }
    }
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 6856
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            group {
              condition {
                trigger_turn: 1
                always_trigger_above: 14
              }
              children {
                behavior {
                  enemy_skill_id: 6857
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 2
                always_trigger_above: 14
              }
              children {
                behavior {
                  enemy_skill_id: 6858
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 3
                always_trigger_above: 84
              }
              children {
                behavior {
                  enemy_skill_id: 6861
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 4
                always_trigger_above: 14
              }
              children {
                behavior {
                  enemy_skill_id: 6865
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 5
                always_trigger_above: 14
              }
              children {
                behavior {
                  enemy_skill_id: 6866
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 6
                always_trigger_above: 14
              }
              children {
                behavior {
                  enemy_skill_id: 6867
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 7
                always_trigger_above: 49
              }
              children {
                behavior {
                  enemy_skill_id: 6868
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 8
                always_trigger_above: 14
              }
              children {
                behavior {
                  enemy_skill_id: 6870
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 9
                always_trigger_above: 14
              }
              children {
                behavior {
                  enemy_skill_id: 6871
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 10
                always_trigger_above: 14
              }
              children {
                behavior {
                  enemy_skill_id: 6872
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  enemy_skill_id: 6873
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 84
            trigger_turn: 3
            always_trigger_above: 14
          }
          children {
            behavior {
              enemy_skill_id: 6863
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 49
            trigger_turn: 7
          }
          children {
            behavior {
              enemy_skill_id: 6869
            }
          }
        }
      }
    }
  }
