  monster_id: 3541
  levels {
    level: 1
    groups {
      group_type: PASSIVE
      children {
        behavior {
          enemy_skill_id: 6741
        }
      }
    }
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 6619
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: MONSTER_STATUS
          children {
            behavior {
              enemy_skill_id: 6628
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 1
            always_trigger_above: 1
          }
          children {
            behavior {
              enemy_skill_id: 6620
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 2
            always_trigger_above: 1
          }
          children {
            behavior {
              enemy_skill_id: 6621
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 3
            always_trigger_above: 1
          }
          children {
            behavior {
              enemy_skill_id: 6624
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 4
            always_trigger_above: 1
          }
          children {
            behavior {
              enemy_skill_id: 6627
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            behavior {
              condition {
                use_chance: 20
              }
              enemy_skill_id: 6629
            }
          }
          children {
            behavior {
              condition {
                use_chance: 20
              }
              enemy_skill_id: 6630
            }
          }
          children {
            behavior {
              condition {
                use_chance: 60
              }
              enemy_skill_id: 6631
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 14
          }
          children {
            behavior {
              enemy_skill_id: 6634
            }
          }
        }
      }
    }
  }
