  monster_id: 3545
  levels {
    level: 1
    groups {
      group_type: PASSIVE
      children {
        behavior {
          enemy_skill_id: 7023
        }
      }
    }
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 7025
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: MONSTER_STATUS
          children {
            behavior {
              enemy_skill_id: 7026
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            behavior {
              enemy_skill_id: 7029
            }
          }
        }
      }
    }
  }
