  monster_id: 3597
  levels {
    level: 1
    groups {
      group_type: PASSIVE
      children {
        behavior {
          enemy_skill_id: 6677
        }
      }
      children {
        behavior {
          enemy_skill_id: 6680
        }
      }
    }
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 6663
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            group {
              condition {
                trigger_turn: 1
              }
              children {
                behavior {
                  enemy_skill_id: 6664
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  condition {
                    use_chance: 15
                  }
                  enemy_skill_id: 6666
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 15
                  }
                  enemy_skill_id: 6667
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 70
                  }
                  enemy_skill_id: 6665
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 49
          }
          children {
            group {
              condition {
                trigger_turn: 2
              }
              children {
                behavior {
                  enemy_skill_id: 6670
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  condition {
                    use_chance: 20
                  }
                  enemy_skill_id: 6681
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 20
                  }
                  enemy_skill_id: 6682
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 60
                  }
                  enemy_skill_id: 6683
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 19
          }
          children {
            behavior {
              enemy_skill_id: 6676
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 1
          }
          children {
            behavior {
              enemy_skill_id: 6679
            }
          }
        }
      }
    }
  }
