  monster_id: 3617
  levels {
    level: 1
    groups {
      group_type: PASSIVE
      children {
        behavior {
          enemy_skill_id: 30744
        }
      }
    }
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 30736
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            behavior {
              enemy_skill_id: 30743
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 49
            trigger_turn: 1
            always_trigger_above: 14
          }
          children {
            behavior {
              enemy_skill_id: 30739
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 14
          }
          children {
            group {
              condition {
                trigger_turn: 1
              }
              children {
                behavior {
                  enemy_skill_id: 30742
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 2
              }
              children {
                behavior {
                  enemy_skill_id: 30739
                }
              }
            }
          }
        }
      }
    }
  }
