  monster_id: 3656
  levels {
    level: 4
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 7217
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            group {
              condition {
                repeats_every: 2
                trigger_turn: 1
              }
              children {
                behavior {
                  condition {
                    use_chance: 14
                  }
                  enemy_skill_id: 7224
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 16
                  }
                  enemy_skill_id: 7227
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 19
                  }
                  enemy_skill_id: 7226
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 24
                  }
                  enemy_skill_id: 7225
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 31
                  }
                  enemy_skill_id: 7222
                }
              }
              children {
                behavior {
                  enemy_skill_id: 7221
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 2
                trigger_turn: 2
              }
              children {
                behavior {
                  enemy_skill_id: 7223
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 49
            trigger_turn: 1
          }
          children {
            behavior {
              enemy_skill_id: 7220
            }
          }
        }
      }
    }
  }
