  monster_id: 3658
  levels {
    level: 4
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 7205
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          condition {
            trigger_turn: 4
            always_trigger_above: 1
          }
          children {
            behavior {
              enemy_skill_id: 7211
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            group {
              condition {
                trigger_turn: 1
                always_trigger_above: 39
              }
              children {
                behavior {
                  condition {
                    use_chance: 20
                  }
                  enemy_skill_id: 7208
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 20
                  }
                  enemy_skill_id: 7209
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 20
                  }
                  enemy_skill_id: 7210
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 2
                trigger_turn_end: 3
                always_trigger_above: 39
              }
              children {
                behavior {
                  condition {
                    use_chance: 20
                  }
                  enemy_skill_id: 7206
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 20
                  }
                  enemy_skill_id: 7207
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 20
                  }
                  enemy_skill_id: 7208
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 20
                  }
                  enemy_skill_id: 7209
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 20
                  }
                  enemy_skill_id: 7210
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 5
                trigger_turn_end: 6
                always_trigger_above: 39
              }
              children {
                behavior {
                  condition {
                    use_chance: 20
                  }
                  enemy_skill_id: 7206
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 20
                  }
                  enemy_skill_id: 7207
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 20
                  }
                  enemy_skill_id: 7208
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 20
                  }
                  enemy_skill_id: 7209
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 20
                  }
                  enemy_skill_id: 7210
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 5
                trigger_turn: 1
                trigger_turn_end: 2
              }
              children {
                behavior {
                  condition {
                    use_chance: 20
                  }
                  enemy_skill_id: 7206
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 20
                  }
                  enemy_skill_id: 7207
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 20
                  }
                  enemy_skill_id: 7208
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 20
                  }
                  enemy_skill_id: 7209
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 20
                  }
                  enemy_skill_id: 7210
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 5
                trigger_turn: 3
              }
              children {
                behavior {
                  enemy_skill_id: 7212
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 5
                trigger_turn: 4
                trigger_turn_end: 5
              }
              children {
                behavior {
                  condition {
                    use_chance: 20
                  }
                  enemy_skill_id: 7206
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 20
                  }
                  enemy_skill_id: 7207
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 20
                  }
                  enemy_skill_id: 7208
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 20
                  }
                  enemy_skill_id: 7209
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 20
                  }
                  enemy_skill_id: 7210
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 39
          }
          children {
            group {
              condition {
                trigger_turn: 1
                trigger_turn_end: 3
              }
              children {
                behavior {
                  condition {
                    use_chance: 50
                  }
                  enemy_skill_id: 7213
                }
              }
              children {
                behavior {
                  enemy_skill_id: 7214
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 5
                trigger_turn_end: 6
              }
              children {
                behavior {
                  condition {
                    use_chance: 50
                  }
                  enemy_skill_id: 7213
                }
              }
              children {
                behavior {
                  enemy_skill_id: 7214
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 5
                trigger_turn: 1
                trigger_turn_end: 2
              }
              children {
                behavior {
                  condition {
                    use_chance: 50
                  }
                  enemy_skill_id: 7213
                }
              }
              children {
                behavior {
                  enemy_skill_id: 7214
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 5
                trigger_turn: 3
              }
              children {
                behavior {
                  enemy_skill_id: 7212
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 5
                trigger_turn: 4
                trigger_turn_end: 5
              }
              children {
                behavior {
                  condition {
                    use_chance: 50
                  }
                  enemy_skill_id: 7213
                }
              }
              children {
                behavior {
                  enemy_skill_id: 7214
                }
              }
            }
          }
        }
      }
    }
  }
