  monster_id: 3660
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 7306
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        group {
          condition {
            trigger_turn: 1
          }
          children {
            behavior {
              enemy_skill_id: 7307
            }
          }
          children {
            behavior {
              enemy_skill_id: 7308
            }
          }
          children {
            behavior {
              enemy_skill_id: 7309
            }
          }
          children {
            behavior {
              enemy_skill_id: 7310
            }
          }
          children {
            behavior {
              enemy_skill_id: 7311
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 2
          }
          children {
            behavior {
              enemy_skill_id: 7308
            }
          }
          children {
            behavior {
              enemy_skill_id: 7309
            }
          }
          children {
            behavior {
              enemy_skill_id: 7310
            }
          }
          children {
            behavior {
              enemy_skill_id: 7311
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 3
          }
          children {
            behavior {
              enemy_skill_id: 7309
            }
          }
          children {
            behavior {
              enemy_skill_id: 7310
            }
          }
          children {
            behavior {
              enemy_skill_id: 7311
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 4
          }
          children {
            behavior {
              enemy_skill_id: 7310
            }
          }
          children {
            behavior {
              enemy_skill_id: 7311
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 5
          }
          children {
            behavior {
              enemy_skill_id: 7314
            }
          }
        }
      }
      children {
        group {
          children {
            behavior {
              condition {
                use_chance: 25
              }
              enemy_skill_id: 7318
            }
          }
          children {
            behavior {
              condition {
                use_chance: 33
              }
              enemy_skill_id: 7317
            }
          }
          children {
            behavior {
              condition {
                use_chance: 50
              }
              enemy_skill_id: 7316
            }
          }
          children {
            behavior {
              enemy_skill_id: 7315
            }
          }
          children {
            behavior {
              enemy_skill_id: 7319
            }
          }
        }
      }
    }
  }
