  monster_id: 3663
  levels {
    level: 1
    groups {
      group_type: PASSIVE
      children {
        behavior {
          enemy_skill_id: 7292
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        behavior {
          enemy_skill_id: 7254
        }
      }
    }
  }
  levels {
    level: 4
    groups {
      group_type: PASSIVE
      children {
        behavior {
          enemy_skill_id: 7292
        }
      }
    }
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 7253
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            behavior {
              condition {
                use_chance: 33
              }
              enemy_skill_id: 7254
            }
          }
          children {
            behavior {
              condition {
                use_chance: 33
              }
              enemy_skill_id: 7255
            }
          }
          children {
            behavior {
              condition {
                use_chance: 34
              }
              enemy_skill_id: 7256
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 89
          }
          children {
            group {
              condition {
                trigger_turn: 1
              }
              children {
                behavior {
                  enemy_skill_id: 7260
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 2
                always_trigger_above: 1
              }
              children {
                behavior {
                  enemy_skill_id: 7261
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  condition {
                    use_chance: 33
                  }
                  enemy_skill_id: 7269
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 50
                  }
                  enemy_skill_id: 7270
                }
              }
              children {
                behavior {
                  enemy_skill_id: 7271
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 69
          }
          children {
            behavior {
              condition {
                use_chance: 33
              }
              enemy_skill_id: 7272
            }
          }
          children {
            behavior {
              condition {
                use_chance: 50
              }
              enemy_skill_id: 7273
            }
          }
          children {
            behavior {
              enemy_skill_id: 7274
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 59
          }
          children {
            behavior {
              condition {
                use_chance: 33
              }
              enemy_skill_id: 7275
            }
          }
          children {
            behavior {
              condition {
                use_chance: 50
              }
              enemy_skill_id: 7276
            }
          }
          children {
            behavior {
              enemy_skill_id: 7277
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 39
          }
          children {
            behavior {
              condition {
                use_chance: 33
              }
              enemy_skill_id: 7278
            }
          }
          children {
            behavior {
              condition {
                use_chance: 50
              }
              enemy_skill_id: 7279
            }
          }
          children {
            behavior {
              enemy_skill_id: 7280
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 19
          }
          children {
            group {
              condition {
                trigger_turn: 3
                always_trigger_above: 1
              }
              children {
                behavior {
                  enemy_skill_id: 7284
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 4
                always_trigger_above: 1
              }
              children {
                behavior {
                  enemy_skill_id: 7288
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  enemy_skill_id: 7291
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 1
            trigger_turn: 1
          }
          children {
            behavior {
              enemy_skill_id: 7327
            }
          }
        }
      }
    }
  }
