  monster_id: 3749
  levels {
    level: 1
    groups {
      group_type: PASSIVE
      children {
        behavior {
          enemy_skill_id: 26252
        }
      }
      children {
        behavior {
          enemy_skill_id: 26253
        }
      }
    }
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 26230
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            group {
              condition {
                trigger_turn: 1
                always_trigger_above: 49
              }
              children {
                behavior {
                  enemy_skill_id: 26249
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 2
                always_trigger_above: 49
              }
              children {
                behavior {
                  enemy_skill_id: 26251
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 3
                always_trigger_above: 49
              }
              children {
                behavior {
                  enemy_skill_id: 26249
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 4
                always_trigger_above: 49
              }
              children {
                behavior {
                  enemy_skill_id: 26251
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 5
                always_trigger_above: 19
              }
              children {
                behavior {
                  enemy_skill_id: 26240
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 2
                trigger_turn: 1
              }
              children {
                behavior {
                  enemy_skill_id: 26249
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 2
                trigger_turn: 2
              }
              children {
                behavior {
                  enemy_skill_id: 26251
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 49
          }
          children {
            group {
              condition {
                trigger_turn: 1
                always_trigger_above: 19
              }
              children {
                behavior {
                  enemy_skill_id: 26243
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 2
                always_trigger_above: 19
              }
              children {
                behavior {
                  enemy_skill_id: 26246
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 3
                always_trigger_above: 19
              }
              children {
                behavior {
                  enemy_skill_id: 26243
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 4
                always_trigger_above: 19
              }
              children {
                behavior {
                  enemy_skill_id: 26246
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 2
                trigger_turn: 1
              }
              children {
                behavior {
                  enemy_skill_id: 26243
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 2
                trigger_turn: 2
              }
              children {
                behavior {
                  enemy_skill_id: 26246
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 19
          }
          children {
            group {
              condition {
                trigger_turn: 1
              }
              children {
                behavior {
                  enemy_skill_id: 26236
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  enemy_skill_id: 26239
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 1
          }
          children {
            behavior {
              enemy_skill_id: 26234
            }
          }
        }
      }
    }
  }
