  monster_id: 3804
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 7719
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            group {
              condition {
                trigger_turn: 1
                trigger_turn_end: 4
                always_trigger_above: 49
              }
              children {
                behavior {
                  condition {
                    use_chance: 20
                  }
                  enemy_skill_id: 7722
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 15
                  }
                  enemy_skill_id: 7723
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 15
                  }
                  enemy_skill_id: 7724
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 20
                  }
                  enemy_skill_id: 7725
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 20
                  }
                  enemy_skill_id: 7726
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 10
                  }
                  enemy_skill_id: 1
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 5
                always_trigger_above: 49
              }
              children {
                behavior {
                  enemy_skill_id: 7727
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 6
                trigger_turn_end: 7
                always_trigger_above: 49
              }
              children {
                behavior {
                  condition {
                    use_chance: 10
                  }
                  enemy_skill_id: 7729
                }
              }
              children {
                behavior {
                  enemy_skill_id: 7730
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 8
                always_trigger_above: 49
              }
              children {
                behavior {
                  enemy_skill_id: 7728
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 9
                trigger_turn_end: 12
                always_trigger_above: 49
              }
              children {
                behavior {
                  condition {
                    use_chance: 20
                  }
                  enemy_skill_id: 7722
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 15
                  }
                  enemy_skill_id: 7723
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 15
                  }
                  enemy_skill_id: 7724
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 20
                  }
                  enemy_skill_id: 7725
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 20
                  }
                  enemy_skill_id: 7726
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 10
                  }
                  enemy_skill_id: 1
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 13
                always_trigger_above: 49
              }
              children {
                behavior {
                  enemy_skill_id: 7728
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 14
                trigger_turn_end: 15
                always_trigger_above: 49
              }
              children {
                behavior {
                  condition {
                    use_chance: 10
                  }
                  enemy_skill_id: 7729
                }
              }
              children {
                behavior {
                  enemy_skill_id: 7730
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 16
                always_trigger_above: 49
              }
              children {
                behavior {
                  enemy_skill_id: 7728
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  condition {
                    use_chance: 20
                  }
                  enemy_skill_id: 7722
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 15
                  }
                  enemy_skill_id: 7723
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 15
                  }
                  enemy_skill_id: 7724
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 20
                  }
                  enemy_skill_id: 7725
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 20
                  }
                  enemy_skill_id: 7726
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 10
                  }
                  enemy_skill_id: 1
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 49
          }
          children {
            group {
              condition {
                trigger_turn: 1
                always_trigger_above: 9
              }
              children {
                behavior {
                  enemy_skill_id: 7721
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 5
                always_trigger_above: 9
              }
              children {
                behavior {
                  condition {
                    use_chance: 20
                  }
                  enemy_skill_id: 7722
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 15
                  }
                  enemy_skill_id: 7723
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 15
                  }
                  enemy_skill_id: 7724
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 20
                  }
                  enemy_skill_id: 7725
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 20
                  }
                  enemy_skill_id: 7726
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 10
                  }
                  enemy_skill_id: 1
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 6
                always_trigger_above: 9
              }
              children {
                behavior {
                  enemy_skill_id: 7727
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 8
                always_trigger_above: 9
              }
              children {
                behavior {
                  condition {
                    use_chance: 10
                  }
                  enemy_skill_id: 7729
                }
              }
              children {
                behavior {
                  enemy_skill_id: 7730
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 9
                always_trigger_above: 9
              }
              children {
                behavior {
                  enemy_skill_id: 7728
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 13
                always_trigger_above: 9
              }
              children {
                behavior {
                  condition {
                    use_chance: 20
                  }
                  enemy_skill_id: 7722
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 15
                  }
                  enemy_skill_id: 7723
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 15
                  }
                  enemy_skill_id: 7724
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 20
                  }
                  enemy_skill_id: 7725
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 20
                  }
                  enemy_skill_id: 7726
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 10
                  }
                  enemy_skill_id: 1
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 14
                always_trigger_above: 9
              }
              children {
                behavior {
                  enemy_skill_id: 7728
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 16
                always_trigger_above: 9
              }
              children {
                behavior {
                  condition {
                    use_chance: 10
                  }
                  enemy_skill_id: 7729
                }
              }
              children {
                behavior {
                  enemy_skill_id: 7730
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 17
                always_trigger_above: 9
              }
              children {
                behavior {
                  enemy_skill_id: 7728
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 9
          }
          children {
            group {
              condition {
                trigger_turn: 1
              }
              children {
                behavior {
                  enemy_skill_id: 7720
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 2
              }
              children {
                behavior {
                  enemy_skill_id: 7721
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 3
              }
              children {
                behavior {
                  enemy_skill_id: 7727
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 4
              }
              children {
                behavior {
                  enemy_skill_id: 7731
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  condition {
                    use_chance: 20
                  }
                  enemy_skill_id: 7729
                }
              }
              children {
                behavior {
                  enemy_skill_id: 7732
                }
              }
            }
          }
        }
      }
    }
  }
