  monster_id: 382
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 133
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
        trigger_turn: 11
      }
      children {
        behavior {
          enemy_skill_id: 133
        }
      }
    }
  }
