  monster_id: 384
  levels {
    level: 1
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 74
      }
      children {
        behavior {
          enemy_skill_id: 101
        }
      }
    }
  }
