  monster_id: 3951
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 14001
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        behavior {
          condition {
            use_chance: 50
          }
          enemy_skill_id: 14002
        }
      }
      children {
        behavior {
          condition {
            use_chance: 50
          }
          enemy_skill_id: 14003
        }
      }
    }
  }
