  monster_id: 3992
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 8382
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        behavior {
          enemy_skill_id: 8383
        }
      }
    }
  }
  levels {
    level: 2
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 8363
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            group {
              condition {
                trigger_turn: 1
                always_trigger_above: 79
              }
              children {
                behavior {
                  enemy_skill_id: 8364
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  enemy_skill_id: 8365
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 79
          }
          children {
            behavior {
              condition {
                use_chance: 5
              }
              enemy_skill_id: 8374
            }
          }
          children {
            behavior {
              condition {
                use_chance: 16
              }
              enemy_skill_id: 8375
            }
          }
          children {
            behavior {
              condition {
                use_chance: 16
              }
              enemy_skill_id: 8376
            }
          }
          children {
            behavior {
              condition {
                use_chance: 16
              }
              enemy_skill_id: 8377
            }
          }
          children {
            behavior {
              condition {
                use_chance: 16
              }
              enemy_skill_id: 8378
            }
          }
          children {
            behavior {
              condition {
                use_chance: 16
              }
              enemy_skill_id: 8379
            }
          }
          children {
            behavior {
              condition {
                use_chance: 15
              }
              enemy_skill_id: 8380
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 14
          }
          children {
            behavior {
              enemy_skill_id: 8357
            }
          }
        }
      }
    }
  }
