  monster_id: 3995
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 19856
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        group {
          condition {
            trigger_turn: 1
            trigger_turn_end: 9
          }
          children {
            behavior {
              condition {
                use_chance: 33
              }
              enemy_skill_id: 19859
            }
          }
          children {
            behavior {
              condition {
                use_chance: 50
              }
              enemy_skill_id: 19861
            }
          }
          children {
            behavior {
              enemy_skill_id: 19860
            }
          }
        }
      }
      children {
        group {
          children {
            behavior {
              enemy_skill_id: 19862
            }
          }
        }
      }
    }
  }
