  monster_id: 400062
  levels {
    level: 1
    groups {
      group_type: PASSIVE
      children {
        behavior {
          enemy_skill_id: 21018
        }
      }
    }
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 19246
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
            repeats_every: 3
            trigger_turn: 1
            trigger_turn_end: 3
          }
          children {
            behavior {
              enemy_skill_id: 19247
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 74
            repeats_every: 3
            trigger_turn: 1
            trigger_turn_end: 3
          }
          children {
            behavior {
              enemy_skill_id: 19252
            }
          }
        }
      }
    }
    groups {
      group_type: UNKNOWN_USE
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 20950
        }
      }
    }
  }
