  monster_id: 401368
  levels {
    level: 1
    groups {
      group_type: PASSIVE
      children {
        behavior {
          enemy_skill_id: 42619
        }
      }
    }
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 42602
        }
      }
      children {
        behavior {
          enemy_skill_id: 42609
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        group {
          condition {
            trigger_turn: 2
          }
          children {
            behavior {
              enemy_skill_id: 42609
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 4
            trigger_turn_end: 5
          }
          children {
            behavior {
              enemy_skill_id: 42609
            }
          }
        }
      }
      children {
        group {
          children {
            behavior {
              enemy_skill_id: 42624
            }
          }
        }
      }
    }
    groups {
      group_type: REMAINING
      condition {
        hp_threshold: 100
        trigger_enemies_remaining: 1
      }
      children {
        group {
          condition {
            trigger_turn: 1
          }
          children {
            behavior {
              enemy_skill_id: 42625
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 2
            trigger_turn_end: 5
          }
          children {
            behavior {
              enemy_skill_id: 42609
            }
          }
        }
      }
    }
  }
