  monster_id: 4016
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          condition {
            trigger_monsters: 3940
            trigger_monsters: 3941
          }
          enemy_skill_id: 8563
        }
      }
      children {
        behavior {
          condition {
            trigger_monsters: 2442
            trigger_monsters: 2443
            trigger_monsters: 3768
            trigger_monsters: 3769
            trigger_monsters: 1948
            trigger_monsters: 1949
            trigger_monsters: 2745
            trigger_monsters: 3908
          }
          enemy_skill_id: 8564
        }
      }
      children {
        behavior {
          enemy_skill_id: 8562
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        group {
          condition {
            trigger_turn: 1
          }
          children {
            behavior {
              enemy_skill_id: 8565
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 2
          }
          children {
            behavior {
              enemy_skill_id: 8566
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 3
          }
          children {
            behavior {
              enemy_skill_id: 8569
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 4
          }
          children {
            behavior {
              enemy_skill_id: 8570
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 5
          }
          children {
            behavior {
              enemy_skill_id: 8574
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 6
            trigger_turn_end: 8
          }
          children {
            behavior {
              condition {
                use_chance: 33
              }
              enemy_skill_id: 8572
            }
          }
          children {
            behavior {
              condition {
                use_chance: 33
              }
              enemy_skill_id: 8573
            }
          }
          children {
            behavior {
              condition {
                use_chance: 34
              }
              enemy_skill_id: 8571
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 9
          }
          children {
            behavior {
              enemy_skill_id: 8577
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 10
          }
          children {
            behavior {
              enemy_skill_id: 8592
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 11
          }
          children {
            behavior {
              enemy_skill_id: 8580
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 12
          }
          children {
            behavior {
              enemy_skill_id: 8581
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 13
          }
          children {
            behavior {
              enemy_skill_id: 8582
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 14
          }
          children {
            behavior {
              enemy_skill_id: 8585
            }
          }
        }
      }
      children {
        group {
          children {
            behavior {
              enemy_skill_id: 8586
            }
          }
        }
      }
    }
  }
