  monster_id: 403
  levels {
    level: 10
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 853
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 29
      }
      children {
        behavior {
          enemy_skill_id: 321
        }
      }
    }
  }
