  monster_id: 403208
  levels {
    level: 4
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 13648
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            group {
              condition {
                trigger_turn: 1
                always_trigger_above: 89
              }
              children {
                behavior {
                  enemy_skill_id: 6080
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 4
                trigger_turn: 1
              }
              children {
                behavior {
                  enemy_skill_id: 6084
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 4
                trigger_turn: 2
              }
              children {
                behavior {
                  enemy_skill_id: 6085
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 4
                trigger_turn: 3
              }
              children {
                behavior {
                  enemy_skill_id: 6086
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 4
                trigger_turn: 4
              }
              children {
                behavior {
                  enemy_skill_id: 6087
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 89
            trigger_turn: 1
            always_trigger_above: 1
          }
          children {
            behavior {
              enemy_skill_id: 6079
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 49
            trigger_turn: 2
            always_trigger_above: 19
          }
          children {
            behavior {
              enemy_skill_id: 6082
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 19
          }
          children {
            group {
              condition {
                trigger_turn: 2
              }
              children {
                behavior {
                  enemy_skill_id: 6081
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  enemy_skill_id: 6083
                }
              }
            }
          }
        }
      }
    }
  }
