  monster_id: 403724
  levels {
    level: 1
    groups {
      group_type: PASSIVE
      children {
        behavior {
          enemy_skill_id: 42619
        }
      }
      children {
        behavior {
          enemy_skill_id: 42616
        }
      }
    }
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 42881
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        group {
          condition {
            trigger_turn: 1
          }
          children {
            behavior {
              enemy_skill_id: 42884
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 2
            trigger_turn_end: 6
          }
          children {
            behavior {
              condition {
                use_chance: 50
              }
              enemy_skill_id: 42882
            }
          }
          children {
            behavior {
              condition {
                use_chance: 50
              }
              enemy_skill_id: 42883
            }
          }
        }
      }
      children {
        group {
          children {
            behavior {
              enemy_skill_id: 42624
            }
          }
        }
      }
    }
    groups {
      group_type: UNKNOWN_USE
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 42888
        }
      }
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 42889
        }
      }
    }
  }
