  monster_id: 404
  levels {
    level: 10
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 1005
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        behavior {
          enemy_skill_id: 1006
        }
      }
    }
  }
