  monster_id: 404417
  levels {
    level: 1
    groups {
      group_type: PASSIVE
      children {
        behavior {
          enemy_skill_id: 9887
        }
      }
    }
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 13720
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            group {
              condition {
                trigger_turn: 1
                trigger_turn_end: 2
                always_trigger_above: 19
              }
              children {
                behavior {
                  condition {
                    use_chance: 30
                  }
                  enemy_skill_id: 9885
                }
              }
              children {
                behavior {
                  enemy_skill_id: 9884
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 3
                always_trigger_above: 19
              }
              children {
                behavior {
                  enemy_skill_id: 9874
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 4
                trigger_turn_end: 5
                always_trigger_above: 19
              }
              children {
                behavior {
                  condition {
                    use_chance: 30
                  }
                  enemy_skill_id: 9885
                }
              }
              children {
                behavior {
                  enemy_skill_id: 9884
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 6
                always_trigger_above: 19
              }
              children {
                behavior {
                  enemy_skill_id: 9875
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 7
                trigger_turn_end: 8
                always_trigger_above: 19
              }
              children {
                behavior {
                  condition {
                    use_chance: 30
                  }
                  enemy_skill_id: 9885
                }
              }
              children {
                behavior {
                  enemy_skill_id: 9884
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 9
                always_trigger_above: 19
              }
              children {
                behavior {
                  enemy_skill_id: 9876
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 10
                trigger_turn_end: 11
                always_trigger_above: 19
              }
              children {
                behavior {
                  condition {
                    use_chance: 30
                  }
                  enemy_skill_id: 9885
                }
              }
              children {
                behavior {
                  enemy_skill_id: 9884
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 12
                always_trigger_above: 19
              }
              children {
                behavior {
                  enemy_skill_id: 9877
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 13
                trigger_turn_end: 14
                always_trigger_above: 19
              }
              children {
                behavior {
                  condition {
                    use_chance: 30
                  }
                  enemy_skill_id: 9885
                }
              }
              children {
                behavior {
                  enemy_skill_id: 9884
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 15
                always_trigger_above: 19
              }
              children {
                behavior {
                  enemy_skill_id: 9878
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 16
                trigger_turn_end: 17
                always_trigger_above: 19
              }
              children {
                behavior {
                  condition {
                    use_chance: 30
                  }
                  enemy_skill_id: 9885
                }
              }
              children {
                behavior {
                  enemy_skill_id: 9884
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 18
                always_trigger_above: 19
              }
              children {
                behavior {
                  enemy_skill_id: 9879
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  condition {
                    use_chance: 30
                  }
                  enemy_skill_id: 9885
                }
              }
              children {
                behavior {
                  enemy_skill_id: 9884
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 19
          }
          children {
            behavior {
              enemy_skill_id: 9850
            }
          }
          children {
            behavior {
              enemy_skill_id: 9886
            }
          }
        }
      }
    }
    groups {
      group_type: UNKNOWN_USE
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 9880
        }
      }
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 9881
        }
      }
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 9882
        }
      }
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 9883
        }
      }
    }
  }
