  monster_id: 405074
  levels {
    level: 1
    groups {
      group_type: PASSIVE
      children {
        behavior {
          enemy_skill_id: 18367
        }
      }
    }
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 18368
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
        repeats_every: 3
        trigger_turn: 1
        trigger_turn_end: 3
      }
      children {
        behavior {
          enemy_skill_id: 18348
        }
      }
    }
    groups {
      group_type: REMAINING
      condition {
        hp_threshold: 100
        trigger_enemies_remaining: 1
        trigger_turn: 1
      }
      children {
        behavior {
          enemy_skill_id: 18349
        }
      }
    }
    groups {
      group_type: UNKNOWN_USE
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 20950
        }
      }
    }
  }
