  monster_id: 405179
  levels {
    level: 1
    groups {
      group_type: PASSIVE
      children {
        behavior {
          enemy_skill_id: 12890
        }
      }
      children {
        behavior {
          enemy_skill_id: 13563
        }
      }
    }
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 12873
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            group {
              condition {
                trigger_turn: 1
                always_trigger_above: 49
              }
              children {
                behavior {
                  condition {
                    use_chance: 33
                  }
                  enemy_skill_id: 12877
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 33
                  }
                  enemy_skill_id: 12878
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 34
                  }
                  enemy_skill_id: 12879
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 2
                always_trigger_above: 49
              }
              children {
                behavior {
                  enemy_skill_id: 12873
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 3
                always_trigger_above: 49
              }
              children {
                behavior {
                  condition {
                    use_chance: 33
                  }
                  enemy_skill_id: 12877
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 33
                  }
                  enemy_skill_id: 12878
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 34
                  }
                  enemy_skill_id: 12879
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 4
                always_trigger_above: 49
              }
              children {
                behavior {
                  enemy_skill_id: 12873
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 5
                always_trigger_above: 49
              }
              children {
                behavior {
                  condition {
                    use_chance: 33
                  }
                  enemy_skill_id: 12877
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 33
                  }
                  enemy_skill_id: 12878
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 34
                  }
                  enemy_skill_id: 12879
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 6
                always_trigger_above: 49
              }
              children {
                behavior {
                  enemy_skill_id: 12873
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 7
                always_trigger_above: 49
              }
              children {
                behavior {
                  condition {
                    use_chance: 33
                  }
                  enemy_skill_id: 12877
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 33
                  }
                  enemy_skill_id: 12878
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 34
                  }
                  enemy_skill_id: 12879
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 8
                trigger_turn: 1
              }
              children {
                behavior {
                  enemy_skill_id: 12884
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 8
                trigger_turn: 2
              }
              children {
                behavior {
                  enemy_skill_id: 12873
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 8
                trigger_turn: 3
              }
              children {
                behavior {
                  condition {
                    use_chance: 33
                  }
                  enemy_skill_id: 12877
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 33
                  }
                  enemy_skill_id: 12878
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 34
                  }
                  enemy_skill_id: 12879
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 8
                trigger_turn: 4
              }
              children {
                behavior {
                  enemy_skill_id: 12873
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 8
                trigger_turn: 5
              }
              children {
                behavior {
                  condition {
                    use_chance: 33
                  }
                  enemy_skill_id: 12877
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 33
                  }
                  enemy_skill_id: 12878
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 34
                  }
                  enemy_skill_id: 12879
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 8
                trigger_turn: 6
              }
              children {
                behavior {
                  enemy_skill_id: 12873
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 8
                trigger_turn: 7
              }
              children {
                behavior {
                  condition {
                    use_chance: 33
                  }
                  enemy_skill_id: 12877
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 33
                  }
                  enemy_skill_id: 12878
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 34
                  }
                  enemy_skill_id: 12879
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 8
                trigger_turn: 8
              }
              children {
                behavior {
                  enemy_skill_id: 12873
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 9
          }
          children {
            behavior {
              enemy_skill_id: 12887
            }
          }
        }
      }
    }
  }
