  monster_id: 405554
  levels {
    level: 1
    groups {
      group_type: PASSIVE
      children {
        behavior {
          enemy_skill_id: 42620
        }
      }
      children {
        behavior {
          enemy_skill_id: 42618
        }
      }
      children {
        behavior {
          enemy_skill_id: 42615
        }
      }
    }
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 42753
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          condition {
            trigger_turn: 1
            trigger_turn_end: 6
            always_trigger_above: 1
          }
          children {
            behavior {
              enemy_skill_id: 42757
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            behavior {
              enemy_skill_id: 42622
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 1
            trigger_turn: 1
          }
          children {
            behavior {
              enemy_skill_id: 42758
            }
          }
        }
      }
    }
  }
