  monster_id: 406565
  levels {
    level: 1
    groups {
      group_type: PASSIVE
      children {
        behavior {
          enemy_skill_id: 20118
        }
      }
    }
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 20158
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            group {
              condition {
                trigger_turn: 1
                always_trigger_above: 49
              }
              children {
                behavior {
                  enemy_skill_id: 20136
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 2
                always_trigger_above: 49
              }
              children {
                behavior {
                  enemy_skill_id: 20190
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 3
                always_trigger_above: 49
              }
              children {
                behavior {
                  enemy_skill_id: 20067
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 4
                always_trigger_above: 49
              }
              children {
                behavior {
                  enemy_skill_id: 20192
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 5
                always_trigger_above: 49
              }
              children {
                behavior {
                  enemy_skill_id: 20096
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 6
                always_trigger_above: 49
              }
              children {
                behavior {
                  enemy_skill_id: 20107
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 50
                  }
                  enemy_skill_id: 20066
                }
              }
              children {
                behavior {
                  enemy_skill_id: 20065
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  condition {
                    use_chance: 50
                  }
                  enemy_skill_id: 20066
                }
              }
              children {
                behavior {
                  enemy_skill_id: 20065
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 49
          }
          children {
            group {
              condition {
                trigger_turn: 1
              }
              children {
                behavior {
                  enemy_skill_id: 20191
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 2
              }
              children {
                behavior {
                  enemy_skill_id: 20163
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 3
              }
              children {
                behavior {
                  enemy_skill_id: 20165
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 2
                trigger_turn: 1
              }
              children {
                behavior {
                  enemy_skill_id: 20181
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 2
                trigger_turn: 2
              }
              children {
                behavior {
                  enemy_skill_id: 20072
                }
              }
            }
          }
        }
      }
    }
  }
