  monster_id: 406617
  levels {
    level: 1
    groups {
      group_type: PASSIVE
      children {
        behavior {
          enemy_skill_id: 41434
        }
      }
    }
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 41435
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        group {
          condition {
            repeats_every: 4
            trigger_turn: 1
          }
          children {
            behavior {
              enemy_skill_id: 41438
            }
          }
        }
      }
      children {
        group {
          condition {
            repeats_every: 4
            trigger_turn: 2
          }
          children {
            behavior {
              enemy_skill_id: 41439
            }
          }
        }
      }
      children {
        group {
          condition {
            repeats_every: 4
            trigger_turn: 3
          }
          children {
            behavior {
              enemy_skill_id: 41440
            }
          }
        }
      }
      children {
        group {
          condition {
            repeats_every: 4
            trigger_turn: 4
          }
          children {
            behavior {
              enemy_skill_id: 41441
            }
          }
        }
      }
    }
  }
