  monster_id: 406763
  levels {
    level: 1
    groups {
      group_type: PASSIVE
      children {
        behavior {
          enemy_skill_id: 20514
        }
      }
    }
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 20502
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            behavior {
              enemy_skill_id: 20504
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 2
          }
          children {
            group {
              condition {
                trigger_turn: 1
                trigger_turn_end: 3
              }
              children {
                behavior {
                  enemy_skill_id: 20503
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  enemy_skill_id: 20508
                }
              }
            }
          }
        }
      }
    }
  }
