  monster_id: 407
  levels {
    level: 10
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        behavior {
          enemy_skill_id: 101
        }
      }
    }
  }
