  monster_id: 407699
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 26805
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        behavior {
          enemy_skill_id: 26807
        }
      }
      children {
        behavior {
          enemy_skill_id: 26806
        }
      }
    }
  }
