  monster_id: 407855
  levels {
    level: 1
    groups {
      group_type: PASSIVE
      children {
        behavior {
          enemy_skill_id: 41339
        }
      }
      children {
        behavior {
          enemy_skill_id: 41338
        }
      }
    }
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 41340
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        group {
          condition {
            trigger_turn: 1
          }
          children {
            behavior {
              enemy_skill_id: 41343
            }
          }
        }
      }
      children {
        group {
          condition {
            repeats_every: 3
            trigger_turn: 1
          }
          children {
            behavior {
              enemy_skill_id: 41344
            }
          }
        }
      }
      children {
        group {
          condition {
            repeats_every: 3
            trigger_turn: 2
          }
          children {
            behavior {
              enemy_skill_id: 41345
            }
          }
        }
      }
    }
  }
