  monster_id: 407919
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 30030
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        group {
          condition {
            trigger_turn: 1
          }
          children {
            behavior {
              enemy_skill_id: 30452
            }
          }
          children {
            behavior {
              enemy_skill_id: 30032
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 2
          }
          children {
            behavior {
              enemy_skill_id: 30453
            }
          }
          children {
            behavior {
              enemy_skill_id: 30034
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 3
          }
          children {
            behavior {
              enemy_skill_id: 29996
            }
          }
          children {
            behavior {
              enemy_skill_id: 30036
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 4
          }
          children {
            behavior {
              enemy_skill_id: 29996
            }
          }
          children {
            behavior {
              enemy_skill_id: 30038
            }
          }
        }
      }
      children {
        group {
          children {
            behavior {
              enemy_skill_id: 29996
            }
          }
          children {
            behavior {
              enemy_skill_id: 29994
            }
          }
        }
      }
    }
    groups {
      group_type: UNKNOWN_USE
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 30454
        }
      }
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 30455
        }
      }
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 30456
        }
      }
    }
  }
