  monster_id: 4091
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          condition {
            trigger_monsters: 4076
            trigger_monsters: 4077
            trigger_monsters: 4078
          }
          enemy_skill_id: 8678
        }
      }
      children {
        behavior {
          enemy_skill_id: 8677
        }
      }
    }
  }
