  monster_id: 412
  levels {
    level: 1
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            behavior {
              condition {
                use_chance: 5
              }
              enemy_skill_id: 234
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 74
          }
          children {
            behavior {
              condition {
                use_chance: 70
              }
              enemy_skill_id: 235
            }
          }
          children {
            behavior {
              condition {
                use_chance: 5
              }
              enemy_skill_id: 234
            }
          }
        }
      }
    }
  }
