  monster_id: 416
  levels {
    level: 1
    groups {
      group_type: STANDARD
      children {
        group {
          condition {
            trigger_turn: 1
            always_trigger_above: 1
          }
          children {
            behavior {
              enemy_skill_id: 245
            }
          }
          children {
            behavior {
              enemy_skill_id: 246
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 29
          }
          children {
            behavior {
              enemy_skill_id: 247
            }
          }
        }
      }
    }
  }
