  monster_id: 4179
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          condition {
            use_chance: 20
          }
          enemy_skill_id: 16510
        }
      }
      children {
        behavior {
          condition {
            use_chance: 20
          }
          enemy_skill_id: 16511
        }
      }
      children {
        behavior {
          condition {
            use_chance: 20
          }
          enemy_skill_id: 16512
        }
      }
      children {
        behavior {
          condition {
            use_chance: 20
          }
          enemy_skill_id: 16513
        }
      }
      children {
        behavior {
          enemy_skill_id: 16514
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 98
        trigger_turn: 1
      }
      children {
        behavior {
          enemy_skill_id: 16509
        }
      }
    }
    groups {
      group_type: UNKNOWN_USE
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 16508
        }
      }
      children {
        behavior {
          enemy_skill_id: 16535
        }
      }
    }
  }
