  monster_id: 4214
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 12650
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        group {
          condition {
            repeats_every: 4
            trigger_turn: 1
          }
          children {
            behavior {
              enemy_skill_id: 12651
            }
          }
        }
      }
      children {
        group {
          condition {
            repeats_every: 4
            trigger_turn: 2
          }
          children {
            behavior {
              enemy_skill_id: 12652
            }
          }
        }
      }
      children {
        group {
          condition {
            repeats_every: 4
            trigger_turn: 3
          }
          children {
            behavior {
              enemy_skill_id: 12653
            }
          }
        }
      }
      children {
        group {
          condition {
            repeats_every: 4
            trigger_turn: 4
          }
          children {
            behavior {
              enemy_skill_id: 12656
            }
          }
        }
      }
    }
  }
