  monster_id: 4344
  levels {
    level: 1
    groups {
      group_type: PASSIVE
      children {
        behavior {
          enemy_skill_id: 13062
        }
      }
      children {
        behavior {
          enemy_skill_id: 13065
        }
      }
    }
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 13048
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            group {
              condition {
                trigger_turn: 1
                always_trigger_above: 49
              }
              children {
                behavior {
                  condition {
                    use_chance: 25
                  }
                  enemy_skill_id: 13049
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 25
                  }
                  enemy_skill_id: 13050
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 25
                  }
                  enemy_skill_id: 13051
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 25
                  }
                  enemy_skill_id: 13052
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 3
                trigger_turn: 1
              }
              children {
                behavior {
                  condition {
                    use_chance: 25
                  }
                  enemy_skill_id: 13056
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 25
                  }
                  enemy_skill_id: 13053
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 25
                  }
                  enemy_skill_id: 13054
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 25
                  }
                  enemy_skill_id: 13055
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 3
                trigger_turn: 2
              }
              children {
                behavior {
                  condition {
                    use_chance: 60
                  }
                  enemy_skill_id: 13057
                }
              }
              children {
                behavior {
                  enemy_skill_id: 13058
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 3
                trigger_turn: 3
              }
              children {
                behavior {
                  condition {
                    use_chance: 25
                  }
                  enemy_skill_id: 13052
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 49
          }
          children {
            group {
              condition {
                trigger_turn: 1
                always_trigger_above: 19
              }
              children {
                behavior {
                  enemy_skill_id: 13060
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 2
                always_trigger_above: 19
              }
              children {
                behavior {
                  condition {
                    use_chance: 25
                  }
                  enemy_skill_id: 13049
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 25
                  }
                  enemy_skill_id: 13050
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 25
                  }
                  enemy_skill_id: 13051
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 25
                  }
                  enemy_skill_id: 13052
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 19
          }
          children {
            behavior {
              enemy_skill_id: 13061
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 1
          }
          children {
            behavior {
              enemy_skill_id: 13063
            }
          }
        }
      }
    }
    groups {
      group_type: UNKNOWN_USE
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 13059
        }
      }
    }
  }
