  monster_id: 4421
  levels {
    level: 1
    groups {
      group_type: PASSIVE
      children {
        behavior {
          enemy_skill_id: 10166
        }
      }
    }
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 10171
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            group {
              condition {
                trigger_turn: 1
              }
              children {
                behavior {
                  condition {
                    trigger_combos: 10
                  }
                  enemy_skill_id: 10175
                }
              }
              children {
                behavior {
                  enemy_skill_id: 10177
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 2
                trigger_turn_end: 4
              }
              children {
                behavior {
                  condition {
                    use_chance: 33
                  }
                  enemy_skill_id: 10178
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 33
                  }
                  enemy_skill_id: 10179
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 34
                  }
                  enemy_skill_id: 10180
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 5
              }
              children {
                behavior {
                  enemy_skill_id: 10183
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 6
              }
              children {
                behavior {
                  condition {
                    trigger_combos: 10
                  }
                  enemy_skill_id: 10187
                }
              }
              children {
                behavior {
                  enemy_skill_id: 10189
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 7
                trigger_turn_end: 9
              }
              children {
                behavior {
                  condition {
                    use_chance: 33
                  }
                  enemy_skill_id: 10190
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 33
                  }
                  enemy_skill_id: 10191
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 34
                  }
                  enemy_skill_id: 10192
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 10
              }
              children {
                behavior {
                  enemy_skill_id: 10182
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 11
              }
              children {
                behavior {
                  condition {
                    trigger_combos: 10
                  }
                  enemy_skill_id: 10195
                }
              }
              children {
                behavior {
                  enemy_skill_id: 10197
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 12
                trigger_turn_end: 14
              }
              children {
                behavior {
                  enemy_skill_id: 10198
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 15
              }
              children {
                behavior {
                  enemy_skill_id: 10201
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 16
              }
              children {
                behavior {
                  enemy_skill_id: 10202
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  enemy_skill_id: 10205
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 1
          }
          children {
            group {
              condition {
                trigger_turn: 1
              }
              children {
                behavior {
                  enemy_skill_id: 10208
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  enemy_skill_id: 10138
                }
              }
            }
          }
        }
      }
    }
  }
