  monster_id: 4590
  levels {
    level: 4
    groups {
      group_type: PREEMPT
      children {
        behavior {
          condition {
            use_chance: 50
          }
          enemy_skill_id: 10445
        }
      }
      children {
        behavior {
          enemy_skill_id: 10444
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        behavior {
          condition {
            use_chance: 50
          }
          enemy_skill_id: 10443
        }
      }
      children {
        behavior {
          enemy_skill_id: 10442
        }
      }
    }
  }
