  monster_id: 461
  levels {
    level: 6
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 74
      }
      children {
        behavior {
          condition {
            use_chance: 40
          }
          enemy_skill_id: 186
        }
      }
    }
  }
