  monster_id: 463
  levels {
    level: 6
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 29
        trigger_turn: 1
      }
      children {
        behavior {
          enemy_skill_id: 184
        }
      }
    }
  }
