  monster_id: 4635
  levels {
    level: 1
    groups {
      group_type: PASSIVE
      children {
        behavior {
          enemy_skill_id: 10478
        }
      }
    }
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 10454
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          condition {
            trigger_turn: 1
            always_trigger_above: 1
          }
          children {
            behavior {
              enemy_skill_id: 10457
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 2
            always_trigger_above: 1
          }
          children {
            behavior {
              enemy_skill_id: 10460
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 3
            always_trigger_above: 1
          }
          children {
            behavior {
              condition {
                trigger_combos: 8
              }
              enemy_skill_id: 10486
            }
          }
          children {
            behavior {
              enemy_skill_id: 10487
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            behavior {
              condition {
                use_chance: 20
              }
              enemy_skill_id: 10501
            }
          }
          children {
            behavior {
              condition {
                use_chance: 20
              }
              enemy_skill_id: 10502
            }
          }
          children {
            behavior {
              condition {
                use_chance: 20
              }
              enemy_skill_id: 10503
            }
          }
          children {
            behavior {
              condition {
                use_chance: 20
              }
              enemy_skill_id: 10490
            }
          }
          children {
            behavior {
              condition {
                use_chance: 20
              }
              enemy_skill_id: 10489
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 49
            trigger_turn: 4
            always_trigger_above: 9
          }
          children {
            behavior {
              enemy_skill_id: 10499
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 9
          }
          children {
            behavior {
              enemy_skill_id: 10498
            }
          }
        }
      }
    }
    groups {
      group_type: UNKNOWN_USE
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 10481
        }
      }
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 10482
        }
      }
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 10483
        }
      }
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 10484
        }
      }
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 10485
        }
      }
      children {
        behavior {
          condition {
            limited_execution: 31
          }
          enemy_skill_id: 10495
        }
      }
      children {
        behavior {
          condition {
            use_chance: 20
          }
          enemy_skill_id: 10488
        }
      }
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 10480
        }
      }
      children {
        behavior {
          condition {
            use_chance: 50
          }
          enemy_skill_id: 10491
        }
      }
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 10492
        }
      }
    }
  }
