  monster_id: 4733
  levels {
    level: 1
    groups {
      group_type: PASSIVE
      children {
        behavior {
          enemy_skill_id: 11067
        }
      }
    }
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 11068
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            behavior {
              condition {
                use_chance: 20
              }
              enemy_skill_id: 11071
            }
          }
          children {
            behavior {
              condition {
                use_chance: 20
              }
              enemy_skill_id: 11072
            }
          }
          children {
            behavior {
              condition {
                use_chance: 4
              }
              enemy_skill_id: 11073
            }
          }
          children {
            behavior {
              condition {
                use_chance: 4
              }
              enemy_skill_id: 11074
            }
          }
          children {
            behavior {
              condition {
                use_chance: 4
              }
              enemy_skill_id: 11075
            }
          }
          children {
            behavior {
              condition {
                use_chance: 4
              }
              enemy_skill_id: 11076
            }
          }
          children {
            behavior {
              condition {
                use_chance: 4
              }
              enemy_skill_id: 11077
            }
          }
          children {
            behavior {
              condition {
                use_chance: 20
              }
              enemy_skill_id: 11078
            }
          }
          children {
            behavior {
              condition {
                use_chance: 20
              }
              enemy_skill_id: 11079
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 49
            trigger_turn: 1
            always_trigger_above: 19
          }
          children {
            behavior {
              enemy_skill_id: 11292
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 19
          }
          children {
            group {
              condition {
                trigger_turn: 1
              }
              children {
                behavior {
                  enemy_skill_id: 11295
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  enemy_skill_id: 11298
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 1
          }
          children {
            behavior {
              enemy_skill_id: 11301
            }
          }
        }
      }
    }
  }
