  monster_id: 4751
  levels {
    level: 4
    groups {
      group_type: PREEMPT
      children {
        behavior {
          condition {
            trigger_monsters: 4754
            trigger_monsters: 4755
          }
          enemy_skill_id: 11011
        }
      }
      children {
        behavior {
          enemy_skill_id: 11009
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            behavior {
              condition {
                use_chance: 33
              }
              enemy_skill_id: 11013
            }
          }
          children {
            behavior {
              condition {
                use_chance: 33
              }
              enemy_skill_id: 11014
            }
          }
          children {
            behavior {
              condition {
                use_chance: 34
              }
              enemy_skill_id: 11015
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 69
            trigger_turn: 1
            always_trigger_above: 1
          }
          children {
            behavior {
              enemy_skill_id: 11012
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 29
            trigger_turn: 2
          }
          children {
            behavior {
              enemy_skill_id: 11016
            }
          }
        }
      }
    }
  }
  levels {
    level: 6
    groups {
      group_type: PREEMPT
      children {
        behavior {
          condition {
            trigger_monsters: 4754
            trigger_monsters: 4755
          }
          enemy_skill_id: 11011
        }
      }
      children {
        behavior {
          enemy_skill_id: 11010
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            behavior {
              condition {
                use_chance: 33
              }
              enemy_skill_id: 11013
            }
          }
          children {
            behavior {
              condition {
                use_chance: 33
              }
              enemy_skill_id: 11014
            }
          }
          children {
            behavior {
              condition {
                use_chance: 34
              }
              enemy_skill_id: 11015
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 69
            trigger_turn: 1
            always_trigger_above: 1
          }
          children {
            behavior {
              enemy_skill_id: 11012
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 29
            trigger_turn: 2
          }
          children {
            behavior {
              enemy_skill_id: 11016
            }
          }
        }
      }
    }
  }
