  monster_id: 4797
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          condition {
            trigger_monsters: 4802
            trigger_monsters: 4803
            trigger_monsters: 4804
            trigger_monsters: 4805
          }
          enemy_skill_id: 11201
        }
      }
      children {
        behavior {
          enemy_skill_id: 11200
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 101
          }
          children {
            behavior {
              enemy_skill_id: 11216
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 99
          }
          children {
            behavior {
              condition {
                use_chance: 25
              }
              enemy_skill_id: 11206
            }
          }
          children {
            behavior {
              condition {
                use_chance: 25
              }
              enemy_skill_id: 11207
            }
          }
          children {
            behavior {
              condition {
                use_chance: 25
              }
              enemy_skill_id: 11208
            }
          }
          children {
            behavior {
              condition {
                use_chance: 25
              }
              enemy_skill_id: 11209
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 74
            trigger_turn: 1
            always_trigger_above: 49
          }
          children {
            behavior {
              enemy_skill_id: 11219
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 49
            trigger_turn: 1
            always_trigger_above: 19
          }
          children {
            behavior {
              enemy_skill_id: 11222
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 19
          }
          children {
            group {
              condition {
                trigger_turn: 1
              }
              children {
                behavior {
                  enemy_skill_id: 11224
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 2
              }
              children {
                behavior {
                  enemy_skill_id: 11227
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  enemy_skill_id: 11230
                }
              }
            }
          }
        }
      }
    }
  }
