  monster_id: 4975
  levels {
    level: 1
    groups {
      group_type: PASSIVE
      children {
        behavior {
          enemy_skill_id: 12045
        }
      }
    }
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 12017
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            behavior {
              condition {
                use_chance: 33
              }
              enemy_skill_id: 12020
            }
          }
          children {
            behavior {
              condition {
                use_chance: 33
              }
              enemy_skill_id: 12021
            }
          }
          children {
            behavior {
              condition {
                use_chance: 34
              }
              enemy_skill_id: 12022
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 49
            trigger_turn: 1
            always_trigger_above: 19
          }
          children {
            behavior {
              enemy_skill_id: 12024
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 19
          }
          children {
            group {
              condition {
                trigger_turn: 1
              }
              children {
                behavior {
                  enemy_skill_id: 12027
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  enemy_skill_id: 12030
                }
              }
            }
          }
        }
      }
    }
    groups {
      group_type: REMAINING
      condition {
        trigger_enemies_remaining: 1
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
            trigger_turn: 1
            always_trigger_above: 49
          }
          children {
            behavior {
              enemy_skill_id: 12023
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 49
          }
          children {
            group {
              condition {
                trigger_turn: 1
                always_trigger_above: 19
              }
              children {
                behavior {
                  enemy_skill_id: 12024
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 2
                always_trigger_above: 19
              }
              children {
                behavior {
                  enemy_skill_id: 12023
                }
              }
            }
          }
        }
      }
    }
  }
