  monster_id: 500083
  levels {
    level: 1
    groups {
      group_type: DEATH
      condition {
        if_defeated: true
      }
      children {
        behavior {
          enemy_skill_id: 13987
        }
      }
    }
  }
