  monster_id: 500075
  levels {
    level: 1
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        behavior {
          condition {
            use_chance: 60
          }
          enemy_skill_id: 13994
        }
      }
    }
  }
