  monster_id: 500584
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 15409
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        behavior {
          enemy_skill_id: 15410
        }
      }
    }
    groups {
      group_type: REMAINING
      condition {
        hp_threshold: 100
        trigger_enemies_remaining: 1
      }
      children {
        group {
          condition {
            repeats_every: 6
            trigger_turn: 1
          }
          children {
            behavior {
              enemy_skill_id: 15408
            }
          }
        }
      }
      children {
        group {
          condition {
            repeats_every: 6
            trigger_turn: 2
            trigger_turn_end: 6
          }
          children {
            behavior {
              enemy_skill_id: 15407
            }
          }
        }
      }
    }
  }
