  monster_id: 500789
  levels {
    level: 1
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        behavior {
          condition {
            use_chance: 20
          }
          enemy_skill_id: 15466
        }
      }
      children {
        behavior {
          condition {
            use_chance: 30
          }
          enemy_skill_id: 15467
        }
      }
      children {
        behavior {
          enemy_skill_id: 15468
        }
      }
    }
  }
