  monster_id: 501504
  levels {
    level: 1
    groups {
      group_type: PASSIVE
      children {
        behavior {
          enemy_skill_id: 20475
        }
      }
    }
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 20472
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            behavior {
              enemy_skill_id: 20472
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 49
          }
          children {
            group {
              condition {
                trigger_turn: 1
                trigger_turn_end: 3
              }
              children {
                behavior {
                  enemy_skill_id: 20473
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  condition {
                    use_chance: 30
                  }
                  enemy_skill_id: 20474
                }
              }
              children {
                behavior {
                  enemy_skill_id: 20472
                }
              }
            }
          }
        }
      }
    }
    groups {
      group_type: REMAINING
      condition {
        trigger_enemies_remaining: 2
        trigger_turn: 1
        always_trigger_above: 1
      }
      children {
        behavior {
          enemy_skill_id: 20471
        }
      }
    }
  }
