  monster_id: 502141
  levels {
    level: 1
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        group {
          condition {
            trigger_turn: 1
          }
          children {
            behavior {
              enemy_skill_id: 13931
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 2
          }
          children {
            behavior {
              enemy_skill_id: 13932
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 3
          }
          children {
            behavior {
              enemy_skill_id: 13933
            }
          }
          children {
            behavior {
              enemy_skill_id: 13934
            }
          }
        }
      }
      children {
        group {
          children {
            behavior {
              enemy_skill_id: 13934
            }
          }
        }
      }
    }
  }
