  monster_id: 502641
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 15523
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        group {
          condition {
            repeats_every: 10
            trigger_turn: 1
            trigger_turn_end: 9
          }
          children {
            behavior {
              condition {
                use_chance: 50
              }
              enemy_skill_id: 15526
            }
          }
          children {
            behavior {
              enemy_skill_id: 15524
            }
          }
        }
      }
      children {
        group {
          condition {
            repeats_every: 10
            trigger_turn: 10
          }
          children {
            behavior {
              enemy_skill_id: 15525
            }
          }
        }
      }
    }
  }
