  monster_id: 502639
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 15500
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            behavior {
              condition {
                use_chance: 30
              }
              enemy_skill_id: 15494
            }
          }
          children {
            behavior {
              enemy_skill_id: 15493
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 49
          }
          children {
            group {
              condition {
                trigger_turn: 1
                always_trigger_above: 1
              }
              children {
                behavior {
                  enemy_skill_id: 15496
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  condition {
                    use_chance: 30
                  }
                  enemy_skill_id: 15495
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 30
                  }
                  enemy_skill_id: 15494
                }
              }
              children {
                behavior {
                  enemy_skill_id: 15493
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 9
          }
          children {
            behavior {
              enemy_skill_id: 15497
            }
          }
        }
      }
    }
  }
