  monster_id: 502756
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 21077
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        behavior {
          condition {
            use_chance: 33
          }
          enemy_skill_id: 21081
        }
      }
      children {
        behavior {
          condition {
            use_chance: 33
          }
          enemy_skill_id: 21082
        }
      }
      children {
        behavior {
          condition {
            use_chance: 34
          }
          enemy_skill_id: 21083
        }
      }
    }
  }
