  monster_id: 502746
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 16847
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        behavior {
          condition {
            use_chance: 25
            limited_execution: 3
          }
          enemy_skill_id: 16845
        }
      }
      children {
        behavior {
          condition {
            use_chance: 50
          }
          enemy_skill_id: 16844
        }
      }
      children {
        behavior {
          enemy_skill_id: 16846
        }
      }
    }
  }
