  monster_id: 503527
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 16826
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        group {
          condition {
            trigger_turn: 1
          }
          children {
            behavior {
              condition {
                trigger_combos: 6
              }
              enemy_skill_id: 16819
            }
          }
          children {
            behavior {
              enemy_skill_id: 16823
            }
          }
        }
      }
      children {
        group {
          children {
            behavior {
              enemy_skill_id: 16818
            }
          }
        }
      }
    }
    groups {
      group_type: UNKNOWN_USE
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 16820
        }
      }
    }
  }
