  monster_id: 503651
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 23496
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        group {
          condition {
            trigger_turn: 1
          }
          children {
            behavior {
              condition {
                trigger_combos: 1
              }
              enemy_skill_id: 23503
            }
          }
          children {
            behavior {
              enemy_skill_id: 23499
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 2
          }
          children {
            behavior {
              condition {
                trigger_combos: 1
              }
              enemy_skill_id: 23504
            }
          }
          children {
            behavior {
              enemy_skill_id: 23500
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 3
          }
          children {
            behavior {
              condition {
                trigger_combos: 1
              }
              enemy_skill_id: 23505
            }
          }
          children {
            behavior {
              enemy_skill_id: 23501
            }
          }
        }
      }
      children {
        group {
          children {
            behavior {
              condition {
                trigger_combos: 1
              }
              enemy_skill_id: 23506
            }
          }
          children {
            behavior {
              enemy_skill_id: 23564
            }
          }
        }
      }
    }
    groups {
      group_type: UNKNOWN_USE
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 23502
        }
      }
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 23507
        }
      }
    }
  }
