  monster_id: 504347
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 23432
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        group {
          condition {
            trigger_turn: 1
          }
          children {
            behavior {
              enemy_skill_id: 23435
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 2
          }
          children {
            behavior {
              enemy_skill_id: 23436
            }
          }
        }
      }
      children {
        group {
          children {
            behavior {
              enemy_skill_id: 23437
            }
          }
        }
      }
    }
  }
