  monster_id: 504344
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 47377
        }
      }
    }
    groups {
      group_type: DEATH
      condition {
        if_defeated: true
      }
      children {
        behavior {
          enemy_skill_id: 47393
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        group {
          condition {
            repeats_every: 4
            trigger_turn: 1
          }
          children {
            behavior {
              enemy_skill_id: 47380
            }
          }
        }
      }
      children {
        group {
          condition {
            repeats_every: 4
            trigger_turn: 2
          }
          children {
            behavior {
              enemy_skill_id: 47383
            }
          }
        }
      }
      children {
        group {
          condition {
            repeats_every: 4
            trigger_turn: 3
          }
          children {
            behavior {
              enemy_skill_id: 47386
            }
          }
        }
      }
      children {
        group {
          condition {
            repeats_every: 4
            trigger_turn: 4
          }
          children {
            behavior {
              enemy_skill_id: 47390
            }
          }
        }
      }
    }
  }
