  monster_id: 504800
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 37845
        }
      }
    }
    groups {
      group_type: DEATH
      condition {
        if_defeated: true
      }
      children {
        behavior {
          enemy_skill_id: 37865
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            group {
              condition {
                trigger_turn: 1
                always_trigger_above: 98
              }
              children {
                behavior {
                  enemy_skill_id: 37858
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 2
                always_trigger_above: 98
              }
              children {
                behavior {
                  enemy_skill_id: 37860
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 3
                always_trigger_above: 98
              }
              children {
                behavior {
                  enemy_skill_id: 37869
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  enemy_skill_id: 37871
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 98
          }
          children {
            group {
              condition {
                trigger_turn: 1
              }
              children {
                behavior {
                  enemy_skill_id: 37858
                }
              }
              children {
                behavior {
                  enemy_skill_id: 37849
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 2
              }
              children {
                behavior {
                  enemy_skill_id: 37860
                }
              }
              children {
                behavior {
                  enemy_skill_id: 37852
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  enemy_skill_id: 37869
                }
              }
              children {
                behavior {
                  enemy_skill_id: 37867
                }
              }
            }
          }
        }
      }
    }
  }
