  monster_id: 505974
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 23317
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        group {
          condition {
            trigger_turn: 1
          }
          children {
            behavior {
              enemy_skill_id: 23337
            }
          }
          children {
            behavior {
              enemy_skill_id: 23321
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 2
          }
          children {
            behavior {
              enemy_skill_id: 23337
            }
          }
          children {
            behavior {
              enemy_skill_id: 23324
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 3
          }
          children {
            behavior {
              enemy_skill_id: 23337
            }
          }
          children {
            behavior {
              enemy_skill_id: 23328
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 4
          }
          children {
            behavior {
              enemy_skill_id: 23337
            }
          }
          children {
            behavior {
              enemy_skill_id: 23331
            }
          }
        }
      }
      children {
        group {
          children {
            behavior {
              enemy_skill_id: 23337
            }
          }
          children {
            behavior {
              enemy_skill_id: 23334
            }
          }
        }
      }
    }
    groups {
      group_type: UNKNOWN_USE
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 23338
        }
      }
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 23339
        }
      }
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 23340
        }
      }
    }
  }
