  monster_id: 506146
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 37829
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        group {
          condition {
            trigger_turn: 1
          }
          children {
            behavior {
              enemy_skill_id: 37830
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 2
          }
          children {
            behavior {
              enemy_skill_id: 37831
            }
          }
        }
      }
      children {
        group {
          condition {
            repeats_every: 2
            trigger_turn: 1
          }
          children {
            behavior {
              enemy_skill_id: 37832
            }
          }
        }
      }
      children {
        group {
          condition {
            repeats_every: 2
            trigger_turn: 2
          }
          children {
            behavior {
              enemy_skill_id: 37833
            }
          }
        }
      }
    }
  }
