  monster_id: 506749
  levels {
    level: 1
    groups {
      group_type: PASSIVE
      children {
        behavior {
          enemy_skill_id: 22492
        }
      }
    }
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 22224
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
        repeats_every: 7
        trigger_turn: 1
        trigger_turn_end: 7
      }
      children {
        behavior {
          enemy_skill_id: 22229
        }
      }
    }
    groups {
      group_type: REMAINING
      condition {
        hp_threshold: 100
        trigger_enemies_remaining: 1
      }
      children {
        group {
          condition {
            trigger_turn: 1
          }
          children {
            behavior {
              enemy_skill_id: 22441
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 2
            trigger_turn_end: 14
          }
          children {
            behavior {
              enemy_skill_id: 22229
            }
          }
        }
      }
      children {
        group {
          children {
            behavior {
              enemy_skill_id: 22200
            }
          }
        }
      }
    }
    groups {
      group_type: UNKNOWN_USE
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 20950
        }
      }
    }
  }
