  monster_id: 507
  levels {
    level: 1
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 49
      }
      children {
        behavior {
          condition {
            use_chance: 40
          }
          enemy_skill_id: 191
        }
      }
    }
  }
