  monster_id: 507024
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 22401
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          condition {
            trigger_turn: 1
            trigger_turn_end: 3
            always_trigger_above: 1
          }
          children {
            behavior {
              enemy_skill_id: 22409
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 9
            always_trigger_above: 1
          }
          children {
            behavior {
              enemy_skill_id: 22677
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 15
            always_trigger_above: 1
          }
          children {
            behavior {
              enemy_skill_id: 22678
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            group {
              condition {
                trigger_turn: 4
                trigger_turn_end: 8
                always_trigger_above: 49
              }
              children {
                behavior {
                  condition {
                    use_chance: 20
                  }
                  enemy_skill_id: 22689
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 20
                  }
                  enemy_skill_id: 22690
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 20
                  }
                  enemy_skill_id: 22691
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 20
                  }
                  enemy_skill_id: 22412
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 20
                  }
                  enemy_skill_id: 22413
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 10
                trigger_turn_end: 14
                always_trigger_above: 49
              }
              children {
                behavior {
                  condition {
                    use_chance: 20
                  }
                  enemy_skill_id: 22689
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 20
                  }
                  enemy_skill_id: 22690
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 20
                  }
                  enemy_skill_id: 22691
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 20
                  }
                  enemy_skill_id: 22412
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 20
                  }
                  enemy_skill_id: 22413
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  condition {
                    use_chance: 20
                  }
                  enemy_skill_id: 22689
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 20
                  }
                  enemy_skill_id: 22690
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 20
                  }
                  enemy_skill_id: 22691
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 20
                  }
                  enemy_skill_id: 22412
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 20
                  }
                  enemy_skill_id: 22413
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 49
          }
          children {
            group {
              condition {
                trigger_turn: 4
                always_trigger_above: 1
              }
              children {
                behavior {
                  enemy_skill_id: 33933
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 5
                trigger_turn_end: 8
                always_trigger_above: 1
              }
              children {
                behavior {
                  condition {
                    use_chance: 20
                  }
                  enemy_skill_id: 22469
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 20
                  }
                  enemy_skill_id: 22470
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 20
                  }
                  enemy_skill_id: 22471
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 20
                  }
                  enemy_skill_id: 22472
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 20
                  }
                  enemy_skill_id: 22473
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 10
                trigger_turn_end: 14
                always_trigger_above: 1
              }
              children {
                behavior {
                  condition {
                    use_chance: 20
                  }
                  enemy_skill_id: 22469
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 20
                  }
                  enemy_skill_id: 22470
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 20
                  }
                  enemy_skill_id: 22471
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 20
                  }
                  enemy_skill_id: 22472
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 20
                  }
                  enemy_skill_id: 22473
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  condition {
                    use_chance: 20
                  }
                  enemy_skill_id: 22469
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 20
                  }
                  enemy_skill_id: 22470
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 20
                  }
                  enemy_skill_id: 22471
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 20
                  }
                  enemy_skill_id: 22472
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 20
                  }
                  enemy_skill_id: 22473
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 1
          }
          children {
            behavior {
              enemy_skill_id: 22422
            }
          }
        }
      }
    }
    groups {
      group_type: UNKNOWN_USE
      children {
        behavior {
          condition {
            use_chance: 33
          }
          enemy_skill_id: 22402
        }
      }
      children {
        behavior {
          condition {
            use_chance: 33
          }
          enemy_skill_id: 22403
        }
      }
      children {
        behavior {
          condition {
            use_chance: 34
          }
          enemy_skill_id: 22404
        }
      }
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 22405
        }
      }
      children {
        behavior {
          condition {
            use_chance: 33
          }
          enemy_skill_id: 22406
        }
      }
      children {
        behavior {
          condition {
            use_chance: 33
          }
          enemy_skill_id: 22407
        }
      }
      children {
        behavior {
          condition {
            use_chance: 34
          }
          enemy_skill_id: 22408
        }
      }
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 22679
        }
      }
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 22680
        }
      }
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 22681
        }
      }
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 22682
        }
      }
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 22683
        }
      }
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 22684
        }
      }
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 22685
        }
      }
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 22686
        }
      }
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 22687
        }
      }
    }
  }
