  monster_id: 509428
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 41117
        }
      }
    }
    groups {
      group_type: DEATH
      condition {
        if_defeated: true
      }
      children {
        behavior {
          enemy_skill_id: 41075
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        behavior {
          condition {
            trigger_combos: 5
          }
          enemy_skill_id: 41129
        }
      }
      children {
        behavior {
          enemy_skill_id: 41120
        }
      }
    }
    groups {
      group_type: UNKNOWN_USE
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 41123
        }
      }
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 41132
        }
      }
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 41126
        }
      }
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 41135
        }
      }
    }
  }
