  monster_id: 509593
  levels {
    level: 1
    groups {
      group_type: PASSIVE
      children {
        behavior {
          enemy_skill_id: 43924
        }
      }
    }
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 43917
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        behavior {
          condition {
            use_chance: 25
          }
          enemy_skill_id: 43920
        }
      }
      children {
        behavior {
          condition {
            use_chance: 25
          }
          enemy_skill_id: 43921
        }
      }
      children {
        behavior {
          condition {
            use_chance: 25
          }
          enemy_skill_id: 43922
        }
      }
      children {
        behavior {
          condition {
            use_chance: 25
          }
          enemy_skill_id: 43923
        }
      }
    }
  }
