  monster_id: 5111
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 12607
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        behavior {
          enemy_skill_id: 12607
        }
      }
    }
    groups {
      group_type: UNKNOWN_USE
      children {
        behavior {
          condition {
            use_chance: 25
          }
          enemy_skill_id: 12619
        }
      }
      children {
        behavior {
          condition {
            use_chance: 33
          }
          enemy_skill_id: 12608
        }
      }
      children {
        behavior {
          condition {
            use_chance: 33
          }
          enemy_skill_id: 12611
        }
      }
      children {
        behavior {
          condition {
            use_chance: 34
          }
          enemy_skill_id: 12614
        }
      }
      children {
        behavior {
          condition {
            trigger_enemies_remaining: 1
          }
          enemy_skill_id: 12618
        }
      }
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 12620
        }
      }
    }
  }
