  monster_id: 5131
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 13401
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            behavior {
              condition {
                trigger_combos: 8
              }
              enemy_skill_id: 13415
            }
          }
          children {
            behavior {
              enemy_skill_id: 13406
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 49
          }
          children {
            group {
              condition {
                trigger_turn: 1
                always_trigger_above: 1
              }
              children {
                behavior {
                  enemy_skill_id: 13405
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  condition {
                    trigger_combos: 8
                  }
                  enemy_skill_id: 13415
                }
              }
              children {
                behavior {
                  enemy_skill_id: 13409
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 19
          }
          children {
            group {
              condition {
                trigger_turn: 2
              }
              children {
                behavior {
                  enemy_skill_id: 13411
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  enemy_skill_id: 13414
                }
              }
            }
          }
        }
      }
    }
  }
