  monster_id: 515
  levels {
    level: 1
    groups {
      group_type: PASSIVE
      children {
        behavior {
          enemy_skill_id: 6503
        }
      }
    }
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 6476
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            behavior {
              enemy_skill_id: 6507
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 94
          }
          children {
            behavior {
              enemy_skill_id: 6490
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 89
            trigger_turn: 1
            always_trigger_above: 79
          }
          children {
            behavior {
              enemy_skill_id: 6480
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 79
            trigger_turn: 1
            always_trigger_above: 69
          }
          children {
            behavior {
              enemy_skill_id: 6504
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 69
            trigger_turn: 1
            always_trigger_above: 59
          }
          children {
            behavior {
              enemy_skill_id: 6506
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 59
            trigger_turn: 1
            always_trigger_above: 49
          }
          children {
            behavior {
              enemy_skill_id: 6486
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 49
          }
          children {
            behavior {
              enemy_skill_id: 6487
            }
          }
        }
      }
    }
    groups {
      group_type: UNKNOWN_USE
      children {
        behavior {
          condition {
            limited_execution: 2
          }
          enemy_skill_id: 6485
        }
      }
      children {
        behavior {
          condition {
            limited_execution: 2
          }
          enemy_skill_id: 6505
        }
      }
      children {
        behavior {
          condition {
            limited_execution: 3
          }
          enemy_skill_id: 6481
        }
      }
      children {
        behavior {
          condition {
            limited_execution: 5
          }
          enemy_skill_id: 6484
        }
      }
      children {
        behavior {
          condition {
            limited_execution: 7
          }
          enemy_skill_id: 6482
        }
      }
      children {
        behavior {
          condition {
            limited_execution: 15
          }
          enemy_skill_id: 6483
        }
      }
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 6496
        }
      }
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 6500
        }
      }
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 6493
        }
      }
    }
  }
