  monster_id: 5173
  levels {
    level: 1
    groups {
      group_type: PASSIVE
      children {
        behavior {
          enemy_skill_id: 12727
        }
      }
    }
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 12698
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            group {
              condition {
                trigger_turn: 1
              }
              children {
                behavior {
                  enemy_skill_id: 12702
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 2
              }
              children {
                behavior {
                  enemy_skill_id: 12705
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 3
              }
              children {
                behavior {
                  enemy_skill_id: 12708
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 4
              }
              children {
                behavior {
                  enemy_skill_id: 12711
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 5
              }
              children {
                behavior {
                  enemy_skill_id: 12714
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 6
              }
              children {
                behavior {
                  enemy_skill_id: 12717
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 7
              }
              children {
                behavior {
                  enemy_skill_id: 12720
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 8
              }
              children {
                behavior {
                  enemy_skill_id: 12723
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 9
              }
              children {
                behavior {
                  enemy_skill_id: 12726
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 10
              }
              children {
                behavior {
                  enemy_skill_id: 12702
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 11
              }
              children {
                behavior {
                  enemy_skill_id: 12705
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 12
              }
              children {
                behavior {
                  enemy_skill_id: 12708
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 13
              }
              children {
                behavior {
                  enemy_skill_id: 12711
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 14
              }
              children {
                behavior {
                  enemy_skill_id: 12714
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 15
              }
              children {
                behavior {
                  enemy_skill_id: 12717
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 16
              }
              children {
                behavior {
                  enemy_skill_id: 12720
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 17
              }
              children {
                behavior {
                  enemy_skill_id: 12723
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  enemy_skill_id: 12728
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 1
          }
          children {
            behavior {
              enemy_skill_id: 12762
            }
          }
        }
      }
    }
  }
