  monster_id: 5185
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 21716
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        group {
          condition {
            trigger_turn: 1
            trigger_turn_end: 8
          }
          children {
            behavior {
              enemy_skill_id: 21717
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 9
          }
          children {
            behavior {
              enemy_skill_id: 21718
            }
          }
        }
      }
      children {
        group {
          children {
            behavior {
              enemy_skill_id: 21719
            }
          }
        }
      }
    }
  }
