  monster_id: 5228
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 13213
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        group {
          condition {
            repeats_every: 2
            trigger_turn: 1
          }
          children {
            behavior {
              enemy_skill_id: 13214
            }
          }
        }
      }
      children {
        group {
          condition {
            repeats_every: 2
            trigger_turn: 2
          }
          children {
            behavior {
              enemy_skill_id: 13213
            }
          }
        }
      }
    }
  }
