  monster_id: 5302
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 13323
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        skill_set: 1
      }
      children {
        behavior {
          condition {
            use_chance: 20
          }
          enemy_skill_id: 13327
        }
      }
      children {
        behavior {
          condition {
            use_chance: 25
          }
          enemy_skill_id: 13328
        }
      }
      children {
        behavior {
          condition {
            use_chance: 33
          }
          enemy_skill_id: 13329
        }
      }
      children {
        behavior {
          condition {
            use_chance: 50
          }
          enemy_skill_id: 13330
        }
      }
      children {
        behavior {
          enemy_skill_id: 13331
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        skill_set: 2
      }
      children {
        behavior {
          condition {
            use_chance: 50
          }
          enemy_skill_id: 13345
        }
      }
      children {
        behavior {
          condition {
            use_chance: 50
          }
          enemy_skill_id: 13346
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          condition {
            trigger_turn: 1
            always_trigger_above: 1
          }
          children {
            behavior {
              condition {
                trigger_combos: 10
              }
              enemy_skill_id: 13386
            }
          }
          children {
            behavior {
              condition {
                trigger_combos: 7
              }
              enemy_skill_id: 13389
            }
          }
          children {
            behavior {
              enemy_skill_id: 13393
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            behavior {
              enemy_skill_id: 13342
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 94
          }
          children {
            group {
              condition {
                trigger_turn: 2
                always_trigger_above: 49
              }
              children {
                behavior {
                  enemy_skill_id: -10
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 3
                trigger_turn_end: 4
                always_trigger_above: 49
              }
              children {
                behavior {
                  enemy_skill_id: -11
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 5
                always_trigger_above: 49
              }
              children {
                behavior {
                  enemy_skill_id: -10
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 6
                trigger_turn_end: 7
                always_trigger_above: 49
              }
              children {
                behavior {
                  enemy_skill_id: -11
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 8
                always_trigger_above: 49
              }
              children {
                behavior {
                  enemy_skill_id: -10
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 9
                always_trigger_above: 49
              }
              children {
                behavior {
                  enemy_skill_id: -11
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 3
                trigger_turn: 1
              }
              children {
                behavior {
                  enemy_skill_id: -11
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 3
                trigger_turn: 2
              }
              children {
                behavior {
                  enemy_skill_id: -10
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 3
                trigger_turn: 3
              }
              children {
                behavior {
                  enemy_skill_id: 13351
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 49
          }
          children {
            group {
              condition {
                trigger_turn: 2
                always_trigger_above: 14
              }
              children {
                behavior {
                  enemy_skill_id: 13353
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 3
                always_trigger_above: 14
              }
              children {
                behavior {
                  enemy_skill_id: -10
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 5
                always_trigger_above: 14
              }
              children {
                behavior {
                  enemy_skill_id: -11
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 6
                always_trigger_above: 14
              }
              children {
                behavior {
                  enemy_skill_id: -10
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 8
                always_trigger_above: 14
              }
              children {
                behavior {
                  enemy_skill_id: -11
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 9
                always_trigger_above: 14
              }
              children {
                behavior {
                  enemy_skill_id: -10
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 10
                always_trigger_above: 14
              }
              children {
                behavior {
                  enemy_skill_id: -11
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 11
                always_trigger_above: 14
              }
              children {
                behavior {
                  enemy_skill_id: 13351
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 3
                trigger_turn: 1
              }
              children {
                behavior {
                  enemy_skill_id: -10
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 3
                trigger_turn: 2
              }
              children {
                behavior {
                  enemy_skill_id: 13351
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 3
                trigger_turn: 3
              }
              children {
                behavior {
                  condition {
                    use_chance: 33
                  }
                  enemy_skill_id: 13345
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 33
                  }
                  enemy_skill_id: 13346
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 14
          }
          children {
            group {
              condition {
                trigger_turn: 2
              }
              children {
                behavior {
                  enemy_skill_id: 13355
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  enemy_skill_id: 13356
                }
              }
            }
          }
        }
      }
    }
  }
  levels {
    level: 6
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 13323
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        skill_set: 1
      }
      children {
        behavior {
          condition {
            use_chance: 20
          }
          enemy_skill_id: 13327
        }
      }
      children {
        behavior {
          condition {
            use_chance: 25
          }
          enemy_skill_id: 13328
        }
      }
      children {
        behavior {
          condition {
            use_chance: 33
          }
          enemy_skill_id: 13329
        }
      }
      children {
        behavior {
          condition {
            use_chance: 50
          }
          enemy_skill_id: 13330
        }
      }
      children {
        behavior {
          enemy_skill_id: 13331
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        skill_set: 2
      }
      children {
        behavior {
          condition {
            use_chance: 50
          }
          enemy_skill_id: 13345
        }
      }
      children {
        behavior {
          condition {
            use_chance: 50
          }
          enemy_skill_id: 13346
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          condition {
            trigger_turn: 1
            always_trigger_above: 1
          }
          children {
            behavior {
              condition {
                trigger_combos: 10
              }
              enemy_skill_id: 13386
            }
          }
          children {
            behavior {
              condition {
                trigger_combos: 8
              }
              enemy_skill_id: 13389
            }
          }
          children {
            behavior {
              enemy_skill_id: 13391
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            behavior {
              enemy_skill_id: 13342
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 94
          }
          children {
            group {
              condition {
                trigger_turn: 2
                always_trigger_above: 49
              }
              children {
                behavior {
                  enemy_skill_id: -10
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 3
                trigger_turn_end: 4
                always_trigger_above: 49
              }
              children {
                behavior {
                  enemy_skill_id: -11
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 5
                always_trigger_above: 49
              }
              children {
                behavior {
                  enemy_skill_id: -10
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 6
                trigger_turn_end: 7
                always_trigger_above: 49
              }
              children {
                behavior {
                  enemy_skill_id: -11
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 8
                always_trigger_above: 49
              }
              children {
                behavior {
                  enemy_skill_id: -10
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 9
                always_trigger_above: 49
              }
              children {
                behavior {
                  enemy_skill_id: -11
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 3
                trigger_turn: 1
              }
              children {
                behavior {
                  enemy_skill_id: -11
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 3
                trigger_turn: 2
              }
              children {
                behavior {
                  enemy_skill_id: -10
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 3
                trigger_turn: 3
              }
              children {
                behavior {
                  enemy_skill_id: 13351
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 49
          }
          children {
            group {
              condition {
                trigger_turn: 2
                always_trigger_above: 14
              }
              children {
                behavior {
                  enemy_skill_id: 13353
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 3
                always_trigger_above: 14
              }
              children {
                behavior {
                  enemy_skill_id: -10
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 5
                always_trigger_above: 14
              }
              children {
                behavior {
                  enemy_skill_id: -11
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 6
                always_trigger_above: 14
              }
              children {
                behavior {
                  enemy_skill_id: -10
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 8
                always_trigger_above: 14
              }
              children {
                behavior {
                  enemy_skill_id: -11
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 9
                always_trigger_above: 14
              }
              children {
                behavior {
                  enemy_skill_id: -10
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 10
                always_trigger_above: 14
              }
              children {
                behavior {
                  enemy_skill_id: -11
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 11
                always_trigger_above: 14
              }
              children {
                behavior {
                  enemy_skill_id: 13351
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 3
                trigger_turn: 1
              }
              children {
                behavior {
                  enemy_skill_id: -10
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 3
                trigger_turn: 2
              }
              children {
                behavior {
                  enemy_skill_id: 13351
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 3
                trigger_turn: 3
              }
              children {
                behavior {
                  condition {
                    use_chance: 33
                  }
                  enemy_skill_id: 13345
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 33
                  }
                  enemy_skill_id: 13346
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 14
          }
          children {
            group {
              condition {
                trigger_turn: 2
              }
              children {
                behavior {
                  enemy_skill_id: 13355
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  enemy_skill_id: 13356
                }
              }
            }
          }
        }
      }
    }
  }
