  monster_id: 5322
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 32703
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        group {
          condition {
            trigger_turn: 1
          }
          children {
            behavior {
              enemy_skill_id: 32707
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 2
          }
          children {
            behavior {
              enemy_skill_id: 32711
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 3
          }
          children {
            behavior {
              enemy_skill_id: 32715
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 4
          }
          children {
            behavior {
              enemy_skill_id: 32723
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 5
          }
          children {
            behavior {
              enemy_skill_id: 32728
            }
          }
        }
      }
      children {
        group {
          children {
            behavior {
              enemy_skill_id: 32730
            }
          }
        }
      }
    }
  }
