  monster_id: 543
  levels {
    level: 5
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            behavior {
              condition {
                use_chance: 40
              }
              enemy_skill_id: 445
            }
          }
          children {
            behavior {
              enemy_skill_id: 446
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 19
            trigger_turn: 1
          }
          children {
            behavior {
              enemy_skill_id: 444
            }
          }
        }
      }
    }
  }
