  monster_id: 5458
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 14118
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        group {
          condition {
            trigger_turn: 1
          }
          children {
            behavior {
              enemy_skill_id: 14119
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 2
          }
          children {
            behavior {
              enemy_skill_id: 14120
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 3
          }
          children {
            behavior {
              enemy_skill_id: 14121
            }
          }
        }
      }
      children {
        group {
          condition {
            repeats_every: 2
            trigger_turn: 1
          }
          children {
            behavior {
              enemy_skill_id: 14122
            }
          }
        }
      }
      children {
        group {
          condition {
            repeats_every: 2
            trigger_turn: 2
          }
          children {
            behavior {
              enemy_skill_id: 14123
            }
          }
        }
      }
    }
  }
