  monster_id: 5568
  levels {
    level: 4
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 14620
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            behavior {
              condition {
                use_chance: 25
              }
              enemy_skill_id: 14621
            }
          }
          children {
            behavior {
              condition {
                use_chance: 25
              }
              enemy_skill_id: 14622
            }
          }
          children {
            behavior {
              condition {
                use_chance: 25
              }
              enemy_skill_id: 14623
            }
          }
          children {
            behavior {
              condition {
                use_chance: 25
              }
              enemy_skill_id: 14625
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 49
            trigger_turn: 1
            always_trigger_above: 14
          }
          children {
            behavior {
              enemy_skill_id: 14624
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 14
          }
          children {
            behavior {
              condition {
                use_chance: 50
                limited_execution: 3
              }
              enemy_skill_id: 14629
            }
          }
          children {
            behavior {
              enemy_skill_id: 14628
            }
          }
        }
      }
    }
  }
