  monster_id: 5571
  levels {
    level: 4
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 14630
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            behavior {
              condition {
                use_chance: 34
              }
              enemy_skill_id: 14631
            }
          }
          children {
            behavior {
              condition {
                use_chance: 33
              }
              enemy_skill_id: 14632
            }
          }
          children {
            behavior {
              condition {
                use_chance: 33
              }
              enemy_skill_id: 14633
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 14
          }
          children {
            behavior {
              condition {
                use_chance: 50
                limited_execution: 3
              }
              enemy_skill_id: 14635
            }
          }
          children {
            behavior {
              enemy_skill_id: 14634
            }
          }
        }
      }
    }
  }
