  monster_id: 5574
  levels {
    level: 4
    groups {
      group_type: PREEMPT
      children {
        behavior {
          condition {
            trigger_monsters: 5565
            trigger_monsters: 5566
          }
          enemy_skill_id: 14601
        }
      }
      children {
        behavior {
          enemy_skill_id: 14600
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            behavior {
              condition {
                use_chance: 25
              }
              enemy_skill_id: 14603
            }
          }
          children {
            behavior {
              condition {
                use_chance: 25
              }
              enemy_skill_id: 14607
            }
          }
          children {
            behavior {
              condition {
                use_chance: 25
              }
              enemy_skill_id: 14608
            }
          }
          children {
            behavior {
              condition {
                use_chance: 25
              }
              enemy_skill_id: 14609
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 49
            trigger_turn: 1
            always_trigger_above: 14
          }
          children {
            behavior {
              enemy_skill_id: 14610
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 14
          }
          children {
            behavior {
              condition {
                use_chance: 50
                limited_execution: 3
              }
              enemy_skill_id: 14612
            }
          }
          children {
            behavior {
              enemy_skill_id: 14611
            }
          }
        }
      }
    }
  }
