  monster_id: 5595
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 14672
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            behavior {
              condition {
                use_chance: 20
              }
              enemy_skill_id: 14673
            }
          }
          children {
            behavior {
              condition {
                use_chance: 20
              }
              enemy_skill_id: 14674
            }
          }
          children {
            behavior {
              condition {
                use_chance: 20
              }
              enemy_skill_id: 14675
            }
          }
          children {
            behavior {
              condition {
                use_chance: 20
              }
              enemy_skill_id: 14676
            }
          }
          children {
            behavior {
              condition {
                use_chance: 20
              }
              enemy_skill_id: 14677
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 14
          }
          children {
            behavior {
              condition {
                use_chance: 50
                limited_execution: 3
              }
              enemy_skill_id: 14679
            }
          }
          children {
            behavior {
              enemy_skill_id: 14678
            }
          }
        }
      }
    }
  }
