  monster_id: 5623
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 14817
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        group {
          condition {
            trigger_turn: 1
            trigger_turn_end: 4
          }
          children {
            behavior {
              condition {
                trigger_combos: 6
              }
              enemy_skill_id: 14825
            }
          }
          children {
            behavior {
              condition {
                trigger_combos: 5
              }
              enemy_skill_id: 14824
            }
          }
          children {
            behavior {
              enemy_skill_id: 14826
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 5
          }
          children {
            behavior {
              condition {
                trigger_combos: 6
              }
              enemy_skill_id: 14825
            }
          }
          children {
            behavior {
              enemy_skill_id: 14829
            }
          }
        }
      }
      children {
        group {
          children {
            behavior {
              condition {
                trigger_combos: 6
              }
              enemy_skill_id: 14825
            }
          }
          children {
            behavior {
              condition {
                trigger_combos: 5
              }
              enemy_skill_id: 14824
            }
          }
          children {
            behavior {
              enemy_skill_id: 14826
            }
          }
        }
      }
    }
  }
