  monster_id: 5637
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 19488
        }
      }
    }
  }
  levels {
    level: 2
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 19491
        }
      }
    }
  }
