  monster_id: 5660
  levels {
    level: 1
    groups {
      group_type: PASSIVE
      children {
        behavior {
          enemy_skill_id: 14965
        }
      }
    }
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 14925
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            behavior {
              condition {
                use_chance: 33
              }
              enemy_skill_id: 14926
            }
          }
          children {
            behavior {
              condition {
                use_chance: 33
              }
              enemy_skill_id: 14927
            }
          }
          children {
            behavior {
              condition {
                use_chance: 34
              }
              enemy_skill_id: 14928
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 75
            trigger_turn: 1
            always_trigger_above: 49
          }
          children {
            behavior {
              enemy_skill_id: 14930
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 49
          }
          children {
            group {
              condition {
                trigger_turn: 1
                always_trigger_above: 1
              }
              children {
                behavior {
                  enemy_skill_id: 14929
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 2
                always_trigger_above: 20
              }
              children {
                behavior {
                  enemy_skill_id: 14930
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 20
          }
          children {
            behavior {
              enemy_skill_id: 14931
            }
          }
        }
      }
    }
  }
