  monster_id: 5669
  levels {
    level: 1
    groups {
      group_type: PASSIVE
      children {
        behavior {
          enemy_skill_id: 14997
        }
      }
    }
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 14947
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            behavior {
              condition {
                use_chance: 30
              }
              enemy_skill_id: 14950
            }
          }
          children {
            behavior {
              condition {
                use_chance: 50
              }
              enemy_skill_id: 14951
            }
          }
          children {
            behavior {
              condition {
                use_chance: 50
              }
              enemy_skill_id: 14952
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 49
            trigger_turn: 1
            always_trigger_above: 1
          }
          children {
            behavior {
              enemy_skill_id: 14953
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 20
          }
          children {
            behavior {
              enemy_skill_id: 14954
            }
          }
        }
      }
    }
  }
