  monster_id: 57
  levels {
    level: 1
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        behavior {
          condition {
            use_chance: 50
            global_one_time: true
          }
          enemy_skill_id: 241
        }
      }
    }
  }
