  monster_id: 5714
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 15262
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            group {
              condition {
                trigger_turn: 1
                always_trigger_above: 49
              }
              children {
                behavior {
                  enemy_skill_id: 15239
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  enemy_skill_id: 15238
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 49
          }
          children {
            group {
              condition {
                trigger_turn: 1
              }
              children {
                behavior {
                  enemy_skill_id: 15240
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  enemy_skill_id: 15241
                }
              }
            }
          }
        }
      }
    }
  }
