  monster_id: 5766
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 20899
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            group {
              condition {
                trigger_turn: 1
                always_trigger_above: 49
              }
              children {
                behavior {
                  enemy_skill_id: 20903
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  condition {
                    use_chance: 25
                  }
                  enemy_skill_id: 20906
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 25
                  }
                  enemy_skill_id: 20908
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 25
                  }
                  enemy_skill_id: 20910
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 25
                  }
                  enemy_skill_id: 20912
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 49
          }
          children {
            group {
              condition {
                trigger_turn: 1
                always_trigger_above: 19
              }
              children {
                behavior {
                  enemy_skill_id: 20900
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  condition {
                    use_chance: 25
                  }
                  enemy_skill_id: 20907
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 25
                  }
                  enemy_skill_id: 20909
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 25
                  }
                  enemy_skill_id: 20911
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 25
                  }
                  enemy_skill_id: 20913
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 19
          }
          children {
            behavior {
              enemy_skill_id: 20914
            }
          }
        }
      }
    }
  }
