  monster_id: 579
  levels {
    level: 1
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 24
      }
      children {
        behavior {
          enemy_skill_id: 236
        }
      }
    }
  }
