  monster_id: 600031
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 37793
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        group {
          condition {
            repeats_every: 3
            trigger_turn: 1
          }
          children {
            behavior {
              enemy_skill_id: 37794
            }
          }
        }
      }
      children {
        group {
          condition {
            repeats_every: 3
            trigger_turn: 2
          }
          children {
            behavior {
              enemy_skill_id: 37796
            }
          }
        }
      }
      children {
        group {
          condition {
            repeats_every: 3
            trigger_turn: 3
          }
          children {
            behavior {
              enemy_skill_id: 37795
            }
          }
        }
      }
    }
  }
