  monster_id: 6057
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 16407
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        group {
          condition {
            trigger_turn: 1
          }
          children {
            behavior {
              condition {
                trigger_combos: 5
              }
              enemy_skill_id: 16406
            }
          }
          children {
            behavior {
              enemy_skill_id: 16399
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 2
          }
          children {
            behavior {
              condition {
                trigger_combos: 6
              }
              enemy_skill_id: 16405
            }
          }
          children {
            behavior {
              enemy_skill_id: 16399
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 3
          }
          children {
            behavior {
              condition {
                trigger_combos: 7
              }
              enemy_skill_id: 16402
            }
          }
          children {
            behavior {
              enemy_skill_id: 16399
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 4
          }
          children {
            behavior {
              enemy_skill_id: 16401
            }
          }
        }
      }
      children {
        group {
          children {
            behavior {
              condition {
                trigger_combos: 10
              }
              enemy_skill_id: 16400
            }
          }
          children {
            behavior {
              enemy_skill_id: 16399
            }
          }
        }
      }
    }
  }
