  monster_id: 605930
  levels {
    level: 1
    groups {
      group_type: PASSIVE
      children {
        behavior {
          enemy_skill_id: 34043
        }
      }
    }
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 34185
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          condition {
            trigger_turn: 2
            always_trigger_above: 1
          }
          children {
            behavior {
              enemy_skill_id: 34205
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 3
            always_trigger_above: 1
          }
          children {
            behavior {
              enemy_skill_id: 34206
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 4
            always_trigger_above: 1
          }
          children {
            behavior {
              enemy_skill_id: 34207
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 5
            always_trigger_above: 1
          }
          children {
            behavior {
              enemy_skill_id: 34208
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            group {
              condition {
                trigger_turn: 1
                always_trigger_above: 49
              }
              children {
                behavior {
                  enemy_skill_id: 34204
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  enemy_skill_id: 34044
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 49
            trigger_turn: 1
          }
          children {
            behavior {
              enemy_skill_id: 34190
            }
          }
        }
      }
    }
  }
