  monster_id: 608
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 295
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 49
      }
      children {
        behavior {
          condition {
            use_chance: 50
          }
          enemy_skill_id: 296
        }
      }
    }
  }
