  monster_id: 608488
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 43145
        }
      }
    }
    groups {
      group_type: UNKNOWN_USE
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 43110
        }
      }
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 43113
        }
      }
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 43117
        }
      }
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 43120
        }
      }
    }
  }
