  monster_id: 608409
  levels {
    level: 1
    groups {
      group_type: PASSIVE
      children {
        behavior {
          enemy_skill_id: 34043
        }
      }
    }
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 40353
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        group {
          condition {
            trigger_turn: 1
            trigger_turn_end: 5
          }
          children {
            behavior {
              enemy_skill_id: 40384
            }
          }
        }
      }
      children {
        group {
          children {
            behavior {
              enemy_skill_id: 34046
            }
          }
        }
      }
    }
  }
