  monster_id: 6087
  levels {
    level: 1
    groups {
      group_type: PASSIVE
      children {
        behavior {
          enemy_skill_id: 17285
        }
      }
      children {
        behavior {
          enemy_skill_id: 17284
        }
      }
    }
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 17286
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          condition {
            trigger_turn: 1
            always_trigger_above: 1
          }
          children {
            behavior {
              enemy_skill_id: 17282
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            group {
              condition {
                trigger_turn: 2
                trigger_turn_end: 3
                always_trigger_above: 9
              }
              children {
                behavior {
                  condition {
                    use_chance: 50
                    trigger_combos: 3
                  }
                  enemy_skill_id: 17308
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 50
                    trigger_combos: 3
                  }
                  enemy_skill_id: 17305
                }
              }
              children {
                behavior {
                  enemy_skill_id: 17302
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 4
                always_trigger_above: 9
              }
              children {
                behavior {
                  enemy_skill_id: 17294
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 5
                always_trigger_above: 9
              }
              children {
                behavior {
                  enemy_skill_id: 17300
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 6
                trigger_turn_end: 8
                always_trigger_above: 9
              }
              children {
                behavior {
                  condition {
                    use_chance: 50
                    trigger_combos: 3
                  }
                  enemy_skill_id: 17308
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 50
                    trigger_combos: 3
                  }
                  enemy_skill_id: 17305
                }
              }
              children {
                behavior {
                  enemy_skill_id: 17302
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 9
                always_trigger_above: 9
              }
              children {
                behavior {
                  enemy_skill_id: 17294
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 10
                always_trigger_above: 9
              }
              children {
                behavior {
                  enemy_skill_id: 17300
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 11
                always_trigger_above: 9
              }
              children {
                behavior {
                  enemy_skill_id: 17297
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 5
                trigger_turn: 1
                trigger_turn_end: 2
              }
              children {
                behavior {
                  condition {
                    use_chance: 50
                    trigger_combos: 3
                  }
                  enemy_skill_id: 17308
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 50
                    trigger_combos: 3
                  }
                  enemy_skill_id: 17305
                }
              }
              children {
                behavior {
                  enemy_skill_id: 17302
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 5
                trigger_turn: 3
              }
              children {
                behavior {
                  enemy_skill_id: 17294
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 5
                trigger_turn: 4
              }
              children {
                behavior {
                  enemy_skill_id: 17300
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 5
                trigger_turn: 5
              }
              children {
                behavior {
                  condition {
                    use_chance: 50
                    trigger_combos: 3
                  }
                  enemy_skill_id: 17308
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 50
                    trigger_combos: 3
                  }
                  enemy_skill_id: 17305
                }
              }
              children {
                behavior {
                  enemy_skill_id: 17302
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 9
          }
          children {
            group {
              condition {
                trigger_turn: 2
              }
              children {
                behavior {
                  enemy_skill_id: 17311
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  enemy_skill_id: 17313
                }
              }
            }
          }
        }
      }
    }
  }
  levels {
    level: 6
    groups {
      group_type: PASSIVE
      children {
        behavior {
          enemy_skill_id: 17285
        }
      }
      children {
        behavior {
          enemy_skill_id: 17284
        }
      }
    }
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 17286
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          condition {
            trigger_turn: 1
            always_trigger_above: 1
          }
          children {
            behavior {
              enemy_skill_id: 17291
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            group {
              condition {
                trigger_turn: 2
                trigger_turn_end: 3
                always_trigger_above: 9
              }
              children {
                behavior {
                  condition {
                    use_chance: 50
                    trigger_combos: 3
                  }
                  enemy_skill_id: 17308
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 50
                    trigger_combos: 3
                  }
                  enemy_skill_id: 17305
                }
              }
              children {
                behavior {
                  enemy_skill_id: 17302
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 4
                always_trigger_above: 9
              }
              children {
                behavior {
                  enemy_skill_id: 17294
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 5
                always_trigger_above: 9
              }
              children {
                behavior {
                  enemy_skill_id: 17300
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 6
                trigger_turn_end: 8
                always_trigger_above: 9
              }
              children {
                behavior {
                  condition {
                    use_chance: 50
                    trigger_combos: 3
                  }
                  enemy_skill_id: 17308
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 50
                    trigger_combos: 3
                  }
                  enemy_skill_id: 17305
                }
              }
              children {
                behavior {
                  enemy_skill_id: 17302
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 9
                always_trigger_above: 9
              }
              children {
                behavior {
                  enemy_skill_id: 17294
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 10
                always_trigger_above: 9
              }
              children {
                behavior {
                  enemy_skill_id: 17300
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 11
                always_trigger_above: 9
              }
              children {
                behavior {
                  enemy_skill_id: 17297
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 5
                trigger_turn: 1
                trigger_turn_end: 2
              }
              children {
                behavior {
                  condition {
                    use_chance: 50
                    trigger_combos: 3
                  }
                  enemy_skill_id: 17308
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 50
                    trigger_combos: 3
                  }
                  enemy_skill_id: 17305
                }
              }
              children {
                behavior {
                  enemy_skill_id: 17302
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 5
                trigger_turn: 3
              }
              children {
                behavior {
                  enemy_skill_id: 17294
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 5
                trigger_turn: 4
              }
              children {
                behavior {
                  enemy_skill_id: 17300
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 5
                trigger_turn: 5
              }
              children {
                behavior {
                  condition {
                    use_chance: 50
                    trigger_combos: 3
                  }
                  enemy_skill_id: 17308
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 50
                    trigger_combos: 3
                  }
                  enemy_skill_id: 17305
                }
              }
              children {
                behavior {
                  enemy_skill_id: 17302
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 9
          }
          children {
            group {
              condition {
                trigger_turn: 2
              }
              children {
                behavior {
                  enemy_skill_id: 17311
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  enemy_skill_id: 17313
                }
              }
            }
          }
        }
      }
    }
  }
