  monster_id: 609335
  levels {
    level: 1
    groups {
      group_type: PASSIVE
      children {
        behavior {
          enemy_skill_id: 34042
        }
      }
    }
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 40361
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        group {
          condition {
            trigger_turn: 1
          }
          children {
            behavior {
              enemy_skill_id: 40364
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 2
            trigger_turn_end: 5
          }
          children {
            behavior {
              enemy_skill_id: 40367
            }
          }
        }
      }
      children {
        group {
          children {
            behavior {
              enemy_skill_id: 34046
            }
          }
        }
      }
    }
    groups {
      group_type: UNKNOWN_USE
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 40362
        }
      }
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 40363
        }
      }
    }
  }
