  monster_id: 609428
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 47352
        }
      }
    }
    groups {
      group_type: DEATH
      condition {
        if_defeated: true
      }
      children {
        behavior {
          enemy_skill_id: 47400
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        behavior {
          condition {
            trigger_combos: 5
          }
          enemy_skill_id: 47364
        }
      }
      children {
        behavior {
          enemy_skill_id: 47355
        }
      }
    }
    groups {
      group_type: UNKNOWN_USE
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 47358
        }
      }
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 47367
        }
      }
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 47361
        }
      }
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 47370
        }
      }
    }
  }
