  monster_id: 6220
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 17821
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        group {
          condition {
            trigger_turn: 1
          }
          children {
            behavior {
              enemy_skill_id: 17822
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 2
          }
          children {
            behavior {
              enemy_skill_id: 17823
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 3
          }
          children {
            behavior {
              enemy_skill_id: 17824
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 4
          }
          children {
            behavior {
              enemy_skill_id: 17825
            }
          }
        }
      }
      children {
        group {
          children {
            behavior {
              enemy_skill_id: 17826
            }
          }
        }
      }
    }
  }
