  monster_id: 6339
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 30812
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        group {
          condition {
            trigger_turn: 1
          }
          children {
            behavior {
              condition {
                damage_done: 1
              }
              enemy_skill_id: 30839
            }
          }
          children {
            behavior {
              enemy_skill_id: 30817
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 2
          }
          children {
            behavior {
              condition {
                damage_done: 1
              }
              enemy_skill_id: 30839
            }
          }
          children {
            behavior {
              enemy_skill_id: 30826
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 3
          }
          children {
            behavior {
              condition {
                damage_done: 1
              }
              enemy_skill_id: 30839
            }
          }
          children {
            behavior {
              enemy_skill_id: 30822
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 4
          }
          children {
            behavior {
              condition {
                damage_done: 1
              }
              enemy_skill_id: 30839
            }
          }
          children {
            behavior {
              enemy_skill_id: 30830
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 5
          }
          children {
            behavior {
              condition {
                damage_done: 1
              }
              enemy_skill_id: 30839
            }
          }
          children {
            behavior {
              enemy_skill_id: 30834
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 6
          }
          children {
            behavior {
              condition {
                damage_done: 1
              }
              enemy_skill_id: 30839
            }
          }
          children {
            behavior {
              enemy_skill_id: 30842
            }
          }
        }
      }
      children {
        group {
          children {
            behavior {
              enemy_skill_id: 30842
            }
          }
        }
      }
    }
  }
