  monster_id: 6414
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 18902
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        group {
          condition {
            trigger_turn: 1
            trigger_turn_end: 3
          }
          children {
            behavior {
              enemy_skill_id: 18903
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 4
          }
          children {
            behavior {
              enemy_skill_id: 18904
            }
          }
        }
      }
      children {
        group {
          children {
            behavior {
              enemy_skill_id: 18905
            }
          }
        }
      }
    }
  }
  levels {
    level: 6
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 18939
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        group {
          condition {
            trigger_turn: 1
            trigger_turn_end: 3
          }
          children {
            behavior {
              enemy_skill_id: 18903
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 4
          }
          children {
            behavior {
              enemy_skill_id: 18904
            }
          }
        }
      }
      children {
        group {
          children {
            behavior {
              enemy_skill_id: 18905
            }
          }
        }
      }
    }
  }
