  monster_id: 6415
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 18907
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        group {
          condition {
            trigger_turn: 1
          }
          children {
            behavior {
              enemy_skill_id: 18903
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 2
          }
          children {
            behavior {
              enemy_skill_id: 18910
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 3
          }
          children {
            behavior {
              enemy_skill_id: 18903
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 4
          }
          children {
            behavior {
              enemy_skill_id: 18911
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 5
          }
          children {
            behavior {
              enemy_skill_id: 18903
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 6
          }
          children {
            behavior {
              enemy_skill_id: 18912
            }
          }
        }
      }
      children {
        group {
          children {
            behavior {
              enemy_skill_id: 18903
            }
          }
        }
      }
    }
  }
  levels {
    level: 6
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 18940
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        group {
          condition {
            trigger_turn: 1
          }
          children {
            behavior {
              enemy_skill_id: 18903
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 2
          }
          children {
            behavior {
              enemy_skill_id: 18910
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 3
          }
          children {
            behavior {
              enemy_skill_id: 18903
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 4
          }
          children {
            behavior {
              enemy_skill_id: 18911
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 5
          }
          children {
            behavior {
              enemy_skill_id: 18903
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 6
          }
          children {
            behavior {
              enemy_skill_id: 18912
            }
          }
        }
      }
      children {
        group {
          children {
            behavior {
              enemy_skill_id: 18903
            }
          }
        }
      }
    }
  }
