  monster_id: 6499
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 19738
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            behavior {
              condition {
                use_chance: 20
              }
              enemy_skill_id: 19741
            }
          }
          children {
            behavior {
              condition {
                use_chance: 40
              }
              enemy_skill_id: 19740
            }
          }
          children {
            behavior {
              condition {
                use_chance: 40
              }
              enemy_skill_id: 19739
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 49
          }
          children {
            group {
              condition {
                trigger_turn: 1
              }
              children {
                behavior {
                  enemy_skill_id: 19742
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  enemy_skill_id: 19743
                }
              }
            }
          }
        }
      }
    }
  }
