  monster_id: 656
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 3321
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            group {
              condition {
                trigger_turn: 1
                always_trigger_above: 79
              }
              children {
                behavior {
                  condition {
                    trigger_monsters: 374
                    trigger_monsters: 375
                    trigger_monsters: 655
                    trigger_monsters: 1347
                  }
                  enemy_skill_id: 3329
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 60
                  }
                  enemy_skill_id: 3322
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 3
                trigger_turn: 1
              }
              children {
                behavior {
                  condition {
                    use_chance: 60
                  }
                  enemy_skill_id: 3322
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 3
                trigger_turn: 2
              }
              children {
                behavior {
                  enemy_skill_id: 3325
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 3
                trigger_turn: 3
              }
              children {
                behavior {
                  condition {
                    use_chance: 60
                  }
                  enemy_skill_id: 3322
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 79
            trigger_turn: 1
            always_trigger_above: 1
          }
          children {
            behavior {
              condition {
                trigger_monsters: 374
                trigger_monsters: 375
                trigger_monsters: 655
                trigger_monsters: 1347
              }
              enemy_skill_id: 3329
            }
          }
          children {
            behavior {
              enemy_skill_id: 3327
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 19
          }
          children {
            behavior {
              enemy_skill_id: 3326
            }
          }
        }
      }
    }
  }
