  monster_id: 6578
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 19912
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            group {
              condition {
                repeats_every: 5
                trigger_turn: 1
              }
              children {
                behavior {
                  enemy_skill_id: 19917
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 5
                trigger_turn: 2
                trigger_turn_end: 5
              }
              children {
                behavior {
                  condition {
                    use_chance: 50
                  }
                  enemy_skill_id: 19923
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 50
                  }
                  enemy_skill_id: 19926
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 49
          }
          children {
            group {
              condition {
                trigger_turn: 1
                always_trigger_above: 9
              }
              children {
                behavior {
                  enemy_skill_id: 19917
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 2
                always_trigger_above: 9
              }
              children {
                behavior {
                  enemy_skill_id: 19920
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 5
                trigger_turn: 1
                trigger_turn_end: 3
              }
              children {
                behavior {
                  condition {
                    use_chance: 50
                  }
                  enemy_skill_id: 19923
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 50
                  }
                  enemy_skill_id: 19926
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 5
                trigger_turn: 4
              }
              children {
                behavior {
                  enemy_skill_id: 19917
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 5
                trigger_turn: 5
              }
              children {
                behavior {
                  condition {
                    use_chance: 50
                  }
                  enemy_skill_id: 19923
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 50
                  }
                  enemy_skill_id: 19926
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 9
          }
          children {
            group {
              condition {
                trigger_turn: 1
              }
              children {
                behavior {
                  enemy_skill_id: 19927
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  enemy_skill_id: 19930
                }
              }
            }
          }
        }
      }
    }
  }
