  monster_id: 6619
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 24642
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        group {
          condition {
            trigger_turn: 1
          }
          children {
            behavior {
              condition {
                erased_attributes: 6
              }
              enemy_skill_id: 24654
            }
          }
          children {
            behavior {
              enemy_skill_id: 24647
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 2
          }
          children {
            behavior {
              condition {
                erased_attributes: 6
              }
              enemy_skill_id: 24656
            }
          }
          children {
            behavior {
              enemy_skill_id: 24651
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 3
          }
          children {
            behavior {
              condition {
                erased_attributes: 6
              }
              enemy_skill_id: 24658
            }
          }
          children {
            behavior {
              enemy_skill_id: 24660
            }
          }
        }
      }
      children {
        group {
          condition {
            repeats_every: 2
            trigger_turn: 1
          }
          children {
            behavior {
              enemy_skill_id: 24663
            }
          }
        }
      }
      children {
        group {
          condition {
            repeats_every: 2
            trigger_turn: 2
          }
          children {
            behavior {
              enemy_skill_id: 24664
            }
          }
        }
      }
    }
  }
