  monster_id: 6689
  levels {
    level: 4
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 20698
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        behavior {
          condition {
            erased_attributes: 0
            erased_attributes: 1
            erased_attributes: 2
            erased_attributes: 3
            erased_attributes: 4
          }
          enemy_skill_id: 20790
        }
      }
      children {
        behavior {
          enemy_skill_id: 20791
        }
      }
    }
  }
