  monster_id: 6768
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 21150
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            behavior {
              condition {
                use_chance: 50
              }
              enemy_skill_id: 21152
            }
          }
          children {
            behavior {
              enemy_skill_id: 21151
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 49
          }
          children {
            group {
              condition {
                trigger_turn: 1
              }
              children {
                behavior {
                  enemy_skill_id: 21153
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  enemy_skill_id: 21154
                }
              }
            }
          }
        }
      }
    }
  }
