  monster_id: 6789
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 21189
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            group {
              condition {
                repeats_every: 4
                trigger_turn: 1
                trigger_turn_end: 3
              }
              children {
                behavior {
                  condition {
                    use_chance: 33
                  }
                  enemy_skill_id: 21190
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 33
                  }
                  enemy_skill_id: 21195
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 34
                  }
                  enemy_skill_id: 21191
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 4
                trigger_turn: 4
              }
              children {
                behavior {
                  enemy_skill_id: 21189
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 49
          }
          children {
            group {
              condition {
                trigger_turn: 1
              }
              children {
                behavior {
                  enemy_skill_id: 21192
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 4
                trigger_turn: 1
                trigger_turn_end: 2
              }
              children {
                behavior {
                  condition {
                    use_chance: 33
                  }
                  enemy_skill_id: 21190
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 33
                  }
                  enemy_skill_id: 21195
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 34
                  }
                  enemy_skill_id: 21191
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 4
                trigger_turn: 3
              }
              children {
                behavior {
                  enemy_skill_id: 21189
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 4
                trigger_turn: 4
              }
              children {
                behavior {
                  condition {
                    use_chance: 33
                  }
                  enemy_skill_id: 21190
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 33
                  }
                  enemy_skill_id: 21195
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 34
                  }
                  enemy_skill_id: 21191
                }
              }
            }
          }
        }
      }
    }
  }
