  monster_id: 6885
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 21606
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        group {
          condition {
            trigger_turn: 1
          }
          children {
            behavior {
              condition {
                erased_attributes: 0
              }
              enemy_skill_id: 21615
            }
          }
          children {
            behavior {
              enemy_skill_id: 21620
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 2
          }
          children {
            behavior {
              condition {
                erased_attributes: 0
              }
              enemy_skill_id: 21616
            }
          }
          children {
            behavior {
              enemy_skill_id: 21621
            }
          }
        }
      }
      children {
        group {
          children {
            behavior {
              enemy_skill_id: 21623
            }
          }
        }
      }
    }
    groups {
      group_type: UNKNOWN_USE
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 21610
        }
      }
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 21611
        }
      }
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 21604
        }
      }
    }
  }
