  monster_id: 700154
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 25343
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        behavior {
          enemy_skill_id: 25342
        }
      }
    }
  }
  levels {
    level: 11
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 25341
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        behavior {
          enemy_skill_id: 25342
        }
      }
    }
  }
  levels {
    level: 12
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 25343
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        behavior {
          enemy_skill_id: 25342
        }
      }
    }
  }
