  monster_id: 7041
  levels {
    level: 1
    groups {
      group_type: PASSIVE
      children {
        behavior {
          enemy_skill_id: 23381
        }
      }
    }
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 23382
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            group {
              condition {
                trigger_turn: 1
              }
              children {
                behavior {
                  enemy_skill_id: 23386
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 2
                trigger_turn_end: 5
                always_trigger_above: 24
              }
              children {
                behavior {
                  enemy_skill_id: 23390
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 6
                always_trigger_above: 24
              }
              children {
                behavior {
                  enemy_skill_id: 23389
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  enemy_skill_id: 23390
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 24
          }
          children {
            group {
              condition {
                trigger_turn: 2
              }
              children {
                behavior {
                  enemy_skill_id: 23389
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  enemy_skill_id: 23393
                }
              }
            }
          }
        }
      }
    }
  }
