  monster_id: 704413
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 37603
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        group {
          condition {
            trigger_turn: 1
            trigger_turn_end: 9
          }
          children {
            behavior {
              condition {
                use_chance: 33
              }
              enemy_skill_id: 37609
            }
          }
          children {
            behavior {
              condition {
                use_chance: 33
              }
              enemy_skill_id: 37610
            }
          }
          children {
            behavior {
              condition {
                use_chance: 34
              }
              enemy_skill_id: 37611
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 10
          }
          children {
            behavior {
              enemy_skill_id: 37606
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 11
          }
          children {
            behavior {
              condition {
                use_chance: 33
              }
              enemy_skill_id: 37609
            }
          }
          children {
            behavior {
              condition {
                use_chance: 33
              }
              enemy_skill_id: 37610
            }
          }
          children {
            behavior {
              condition {
                use_chance: 34
              }
              enemy_skill_id: 37611
            }
          }
        }
      }
      children {
        group {
          children {
            behavior {
              enemy_skill_id: 37606
            }
          }
        }
      }
    }
  }
