  monster_id: 704648
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 37626
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        group {
          condition {
            trigger_turn: 1
            trigger_turn_end: 9
          }
          children {
            behavior {
              condition {
                use_chance: 50
              }
              enemy_skill_id: 37632
            }
          }
          children {
            behavior {
              condition {
                use_chance: 50
              }
              enemy_skill_id: 37633
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 10
          }
          children {
            behavior {
              enemy_skill_id: 37629
            }
          }
        }
      }
      children {
        group {
          children {
            behavior {
              condition {
                use_chance: 50
              }
              enemy_skill_id: 37632
            }
          }
          children {
            behavior {
              condition {
                use_chance: 50
              }
              enemy_skill_id: 37633
            }
          }
        }
      }
    }
  }
