  monster_id: 7121
  levels {
    level: 1
    groups {
      group_type: PASSIVE
      children {
        behavior {
          enemy_skill_id: 23100
        }
      }
    }
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 23101
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            group {
              condition {
                trigger_turn: 1
                always_trigger_above: 9
              }
              children {
                behavior {
                  enemy_skill_id: 23216
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 2
                trigger_turn_end: 9
                always_trigger_above: 9
              }
              children {
                behavior {
                  condition {
                    use_chance: 5
                  }
                  enemy_skill_id: 23105
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 5
                  }
                  enemy_skill_id: 23106
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 5
                  }
                  enemy_skill_id: 23107
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 5
                  }
                  enemy_skill_id: 23108
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 5
                  }
                  enemy_skill_id: 23109
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 25
                  }
                  enemy_skill_id: 23110
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 50
                  }
                  enemy_skill_id: 23111
                }
              }
              children {
                behavior {
                  enemy_skill_id: 23112
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 10
                always_trigger_above: 9
              }
              children {
                behavior {
                  enemy_skill_id: 23113
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  condition {
                    use_chance: 5
                  }
                  enemy_skill_id: 23105
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 5
                  }
                  enemy_skill_id: 23106
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 5
                  }
                  enemy_skill_id: 23107
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 5
                  }
                  enemy_skill_id: 23108
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 5
                  }
                  enemy_skill_id: 23109
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 25
                  }
                  enemy_skill_id: 23110
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 50
                  }
                  enemy_skill_id: 23111
                }
              }
              children {
                behavior {
                  enemy_skill_id: 23112
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 9
          }
          children {
            behavior {
              enemy_skill_id: 23114
            }
          }
        }
      }
    }
    groups {
      group_type: UNKNOWN_USE
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 23217
        }
      }
    }
  }
