  monster_id: 7210
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 23904
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            behavior {
              condition {
                use_chance: 33
              }
              enemy_skill_id: 23905
            }
          }
          children {
            behavior {
              condition {
                use_chance: 33
              }
              enemy_skill_id: 23906
            }
          }
          children {
            behavior {
              condition {
                use_chance: 34
              }
              enemy_skill_id: 23908
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 49
          }
          children {
            group {
              condition {
                trigger_turn: 1
                always_trigger_above: 14
              }
              children {
                behavior {
                  enemy_skill_id: 23912
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  condition {
                    use_chance: 33
                  }
                  enemy_skill_id: 23907
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 33
                  }
                  enemy_skill_id: 23909
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 34
                  }
                  enemy_skill_id: 23910
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 14
          }
          children {
            behavior {
              enemy_skill_id: 23911
            }
          }
        }
      }
    }
  }
