  monster_id: 7220
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 23820
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        behavior {
          enemy_skill_id: 23821
        }
      }
    }
    groups {
      group_type: REMAINING
      condition {
        hp_threshold: 100
        trigger_enemies_remaining: 1
      }
      children {
        behavior {
          enemy_skill_id: 23822
        }
      }
    }
  }
