  monster_id: 7233
  levels {
    level: 1
    groups {
      group_type: PASSIVE
      children {
        behavior {
          enemy_skill_id: 24011
        }
      }
    }
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 24001
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            group {
              condition {
                repeats_every: 7
                trigger_turn: 1
              }
              children {
                behavior {
                  condition {
                    use_chance: 10
                  }
                  enemy_skill_id: 23991
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 10
                  }
                  enemy_skill_id: 23992
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 10
                  }
                  enemy_skill_id: 23993
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 10
                  }
                  enemy_skill_id: 23994
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 10
                  }
                  enemy_skill_id: 23995
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 10
                  }
                  enemy_skill_id: 23996
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 10
                  }
                  enemy_skill_id: 23997
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 10
                  }
                  enemy_skill_id: 23998
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 10
                  }
                  enemy_skill_id: 23999
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 10
                  }
                  enemy_skill_id: 24000
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 7
                trigger_turn: 2
              }
              children {
                behavior {
                  enemy_skill_id: 24004
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 7
                trigger_turn: 3
              }
              children {
                behavior {
                  enemy_skill_id: 24005
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 7
                trigger_turn: 4
              }
              children {
                behavior {
                  enemy_skill_id: 24006
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 7
                trigger_turn: 5
              }
              children {
                behavior {
                  enemy_skill_id: 24007
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 7
                trigger_turn: 6
              }
              children {
                behavior {
                  enemy_skill_id: 24008
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 7
                trigger_turn: 7
              }
              children {
                behavior {
                  enemy_skill_id: 24009
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 9
          }
          children {
            behavior {
              enemy_skill_id: 24010
            }
          }
        }
      }
    }
  }
