  monster_id: 728
  levels {
    level: 5
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 74
      }
      children {
        behavior {
          enemy_skill_id: 403
        }
      }
    }
  }
