  monster_id: 7465
  levels {
    level: 1
    groups {
      group_type: PASSIVE
      children {
        behavior {
          enemy_skill_id: 25814
        }
      }
      children {
        behavior {
          enemy_skill_id: 25791
        }
      }
    }
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 25784
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            group {
              condition {
                trigger_turn: 1
                always_trigger_above: 84
              }
              children {
                behavior {
                  enemy_skill_id: 25789
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 2
                always_trigger_above: 84
              }
              children {
                behavior {
                  enemy_skill_id: 25802
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 3
                always_trigger_above: 84
              }
              children {
                behavior {
                  enemy_skill_id: 25804
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 4
                always_trigger_above: 84
              }
              children {
                behavior {
                  enemy_skill_id: 25802
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 5
                always_trigger_above: 84
              }
              children {
                behavior {
                  enemy_skill_id: 25804
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 6
                always_trigger_above: 84
              }
              children {
                behavior {
                  enemy_skill_id: 25802
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 7
                always_trigger_above: 84
              }
              children {
                behavior {
                  enemy_skill_id: 25804
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 8
                always_trigger_above: 84
              }
              children {
                behavior {
                  enemy_skill_id: 25802
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 9
                always_trigger_above: 84
              }
              children {
                behavior {
                  enemy_skill_id: 25804
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 10
                always_trigger_above: 84
              }
              children {
                behavior {
                  enemy_skill_id: 25802
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 11
                always_trigger_above: 84
              }
              children {
                behavior {
                  enemy_skill_id: 25804
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 12
                always_trigger_above: 84
              }
              children {
                behavior {
                  enemy_skill_id: 25802
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 13
                always_trigger_above: 84
              }
              children {
                behavior {
                  enemy_skill_id: 25804
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 14
                always_trigger_above: 84
              }
              children {
                behavior {
                  enemy_skill_id: 25802
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 15
                always_trigger_above: 9
              }
              children {
                behavior {
                  enemy_skill_id: 25824
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 2
                trigger_turn: 1
              }
              children {
                behavior {
                  enemy_skill_id: 25802
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 2
                trigger_turn: 2
              }
              children {
                behavior {
                  enemy_skill_id: 25804
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 84
          }
          children {
            group {
              condition {
                trigger_turn: 1
                always_trigger_above: 49
              }
              children {
                behavior {
                  enemy_skill_id: 25802
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 2
                always_trigger_above: 49
              }
              children {
                behavior {
                  enemy_skill_id: 25804
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 3
                always_trigger_above: 49
              }
              children {
                behavior {
                  enemy_skill_id: 25802
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 4
                always_trigger_above: 49
              }
              children {
                behavior {
                  enemy_skill_id: 25804
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 5
                always_trigger_above: 49
              }
              children {
                behavior {
                  enemy_skill_id: 25802
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 6
                always_trigger_above: 49
              }
              children {
                behavior {
                  enemy_skill_id: 25804
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 7
                always_trigger_above: 49
              }
              children {
                behavior {
                  enemy_skill_id: 25802
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 8
                always_trigger_above: 49
              }
              children {
                behavior {
                  enemy_skill_id: 25804
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 9
                always_trigger_above: 49
              }
              children {
                behavior {
                  enemy_skill_id: 25802
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 10
                always_trigger_above: 49
              }
              children {
                behavior {
                  enemy_skill_id: 25804
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 11
                always_trigger_above: 49
              }
              children {
                behavior {
                  enemy_skill_id: 25802
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 12
                always_trigger_above: 49
              }
              children {
                behavior {
                  enemy_skill_id: 25804
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 13
                always_trigger_above: 49
              }
              children {
                behavior {
                  enemy_skill_id: 25802
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 14
                always_trigger_above: 49
              }
              children {
                behavior {
                  enemy_skill_id: 25804
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 49
          }
          children {
            group {
              condition {
                trigger_turn: 1
                always_trigger_above: 9
              }
              children {
                behavior {
                  enemy_skill_id: 25790
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 2
                trigger_turn_end: 14
                always_trigger_above: 9
              }
              children {
                behavior {
                  condition {
                    use_chance: 33
                  }
                  enemy_skill_id: 25794
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 50
                  }
                  enemy_skill_id: 25797
                }
              }
              children {
                behavior {
                  enemy_skill_id: 25799
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  condition {
                    use_chance: 33
                  }
                  enemy_skill_id: 25794
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 50
                  }
                  enemy_skill_id: 25797
                }
              }
              children {
                behavior {
                  enemy_skill_id: 25799
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 9
            repeats_every: 7
            trigger_turn: 1
            trigger_turn_end: 7
          }
          children {
            behavior {
              enemy_skill_id: 25789
            }
          }
        }
      }
    }
  }
