  monster_id: 750
  levels {
    level: 3
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 1064
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 19
      }
      children {
        behavior {
          enemy_skill_id: 549
        }
      }
    }
  }
