  monster_id: 751
  levels {
    level: 5
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 562
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
            trigger_turn: 1
            always_trigger_above: 59
          }
          children {
            behavior {
              enemy_skill_id: 563
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 59
          }
          children {
            group {
              condition {
                trigger_turn: 1
                always_trigger_above: 19
              }
              children {
                behavior {
                  enemy_skill_id: 563
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  condition {
                    use_chance: 70
                  }
                  enemy_skill_id: 564
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 19
          }
          children {
            behavior {
              enemy_skill_id: 565
            }
          }
        }
      }
    }
  }
