  monster_id: 7797
  levels {
    level: 1
    groups {
      group_type: PASSIVE
      children {
        behavior {
          enemy_skill_id: 29242
        }
      }
      children {
        behavior {
          enemy_skill_id: 29243
        }
      }
    }
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 29191
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            group {
              condition {
                trigger_turn: 1
                trigger_turn_end: 4
                always_trigger_above: 39
              }
              children {
                behavior {
                  condition {
                    use_chance: 33
                  }
                  enemy_skill_id: 29232
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 50
                  }
                  enemy_skill_id: 29235
                }
              }
              children {
                behavior {
                  enemy_skill_id: 29239
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 5
                always_trigger_above: 39
              }
              children {
                behavior {
                  enemy_skill_id: 29216
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  condition {
                    use_chance: 33
                  }
                  enemy_skill_id: 29232
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 50
                  }
                  enemy_skill_id: 29235
                }
              }
              children {
                behavior {
                  enemy_skill_id: 29239
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 39
          }
          children {
            group {
              condition {
                trigger_turn: 1
                always_trigger_above: 1
              }
              children {
                behavior {
                  enemy_skill_id: 29203
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 2
                always_trigger_above: 1
              }
              children {
                behavior {
                  condition {
                    erased_attributes: 0
                    erased_attributes: 1
                    erased_attributes: 2
                    erased_attributes: 3
                    erased_attributes: 4
                  }
                  enemy_skill_id: 29208
                }
              }
              children {
                behavior {
                  enemy_skill_id: 29212
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 3
                trigger_turn_end: 6
                always_trigger_above: 9
              }
              children {
                behavior {
                  condition {
                    use_chance: 33
                  }
                  enemy_skill_id: 29220
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 50
                  }
                  enemy_skill_id: 29224
                }
              }
              children {
                behavior {
                  enemy_skill_id: 29228
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 7
                always_trigger_above: 9
              }
              children {
                behavior {
                  enemy_skill_id: 29216
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  condition {
                    use_chance: 33
                  }
                  enemy_skill_id: 29220
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 50
                  }
                  enemy_skill_id: 29224
                }
              }
              children {
                behavior {
                  enemy_skill_id: 29228
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 9
          }
          children {
            group {
              condition {
                trigger_turn: 3
              }
              children {
                behavior {
                  enemy_skill_id: 29195
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  enemy_skill_id: 29199
                }
              }
            }
          }
        }
      }
    }
  }
