  monster_id: 782
  levels {
    level: 5
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 469
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
            repeats_every: 3
            trigger_turn: 3
          }
          children {
            behavior {
              enemy_skill_id: 469
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 29
          }
          children {
            behavior {
              enemy_skill_id: 470
            }
          }
        }
      }
    }
  }
