  monster_id: 788
  levels {
    level: 5
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 471
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 39
          }
          children {
            behavior {
              enemy_skill_id: 467
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 9
            trigger_turn: 1
          }
          children {
            behavior {
              enemy_skill_id: 367
            }
          }
        }
      }
    }
  }
