  monster_id: 8078
  levels {
    level: 1
    groups {
      group_type: PASSIVE
      children {
        behavior {
          enemy_skill_id: 31724
        }
      }
    }
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 31717
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            behavior {
              condition {
                use_chance: 50
              }
              enemy_skill_id: 31722
            }
          }
          children {
            behavior {
              enemy_skill_id: 31723
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 49
          }
          children {
            group {
              condition {
                trigger_turn: 1
              }
              children {
                behavior {
                  enemy_skill_id: 31720
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  enemy_skill_id: 31721
                }
              }
            }
          }
        }
      }
    }
  }
