  monster_id: 811
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 16225
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        group {
          condition {
            trigger_turn: 1
          }
          children {
            behavior {
              enemy_skill_id: 16231
            }
          }
          children {
            behavior {
              enemy_skill_id: 16232
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 2
          }
          children {
            behavior {
              enemy_skill_id: 16235
            }
          }
          children {
            behavior {
              enemy_skill_id: 16236
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 3
          }
          children {
            behavior {
              enemy_skill_id: 16239
            }
          }
          children {
            behavior {
              enemy_skill_id: 16240
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 4
          }
          children {
            behavior {
              enemy_skill_id: 16243
            }
          }
          children {
            behavior {
              enemy_skill_id: 16244
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 5
          }
          children {
            behavior {
              enemy_skill_id: 16247
            }
          }
          children {
            behavior {
              enemy_skill_id: 16248
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 6
          }
          children {
            behavior {
              condition {
                trigger_combos: 10
              }
              enemy_skill_id: 16251
            }
          }
          children {
            behavior {
              enemy_skill_id: 16252
            }
          }
        }
      }
      children {
        group {
          children {
            behavior {
              enemy_skill_id: 16255
            }
          }
        }
      }
    }
  }
