  monster_id: 823
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 1619
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        group {
          condition {
            repeats_every: 5
            trigger_turn: 1
          }
          children {
            behavior {
              enemy_skill_id: 1620
            }
          }
        }
      }
      children {
        group {
          condition {
            repeats_every: 5
            trigger_turn: 2
          }
          children {
            behavior {
              enemy_skill_id: 1621
            }
          }
        }
      }
      children {
        group {
          condition {
            repeats_every: 5
            trigger_turn: 3
          }
          children {
            behavior {
              enemy_skill_id: 1622
            }
          }
        }
      }
      children {
        group {
          condition {
            repeats_every: 5
            trigger_turn: 4
          }
          children {
            behavior {
              enemy_skill_id: 1623
            }
          }
        }
      }
      children {
        group {
          condition {
            repeats_every: 5
            trigger_turn: 5
          }
          children {
            behavior {
              enemy_skill_id: 1624
            }
          }
        }
      }
    }
  }
