  monster_id: 8396
  levels {
    level: 1
    groups {
      group_type: PASSIVE
      children {
        behavior {
          enemy_skill_id: 41819
        }
      }
    }
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 41790
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            behavior {
              condition {
                use_chance: 17
              }
              enemy_skill_id: 41813
            }
          }
          children {
            behavior {
              condition {
                use_chance: 17
              }
              enemy_skill_id: 41814
            }
          }
          children {
            behavior {
              condition {
                use_chance: 17
              }
              enemy_skill_id: 41815
            }
          }
          children {
            behavior {
              condition {
                use_chance: 17
              }
              enemy_skill_id: 41816
            }
          }
          children {
            behavior {
              condition {
                use_chance: 16
              }
              enemy_skill_id: 41817
            }
          }
          children {
            behavior {
              condition {
                use_chance: 16
              }
              enemy_skill_id: 41818
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 49
            trigger_turn: 1
            always_trigger_above: 14
          }
          children {
            behavior {
              enemy_skill_id: 41797
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 14
          }
          children {
            group {
              condition {
                trigger_turn: 1
              }
              children {
                behavior {
                  enemy_skill_id: 41791
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  enemy_skill_id: 41792
                }
              }
            }
          }
        }
      }
    }
    groups {
      group_type: REMAINING
      condition {
        hp_threshold: 100
        trigger_enemies_remaining: 1
      }
      children {
        group {
          condition {
            trigger_turn: 1
            always_trigger_above: 14
          }
          children {
            behavior {
              enemy_skill_id: 41793
            }
          }
        }
      }
      children {
        group {
          children {
            behavior {
              condition {
                use_chance: 20
              }
              enemy_skill_id: 41798
            }
          }
          children {
            behavior {
              condition {
                use_chance: 20
              }
              enemy_skill_id: 41801
            }
          }
          children {
            behavior {
              condition {
                use_chance: 20
              }
              enemy_skill_id: 41804
            }
          }
          children {
            behavior {
              condition {
                use_chance: 20
              }
              enemy_skill_id: 41807
            }
          }
          children {
            behavior {
              condition {
                use_chance: 20
              }
              enemy_skill_id: 41810
            }
          }
        }
      }
    }
    groups {
      group_type: UNKNOWN_USE
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 41900
        }
      }
    }
  }
