  monster_id: 8398
  levels {
    level: 1
    groups {
      group_type: PASSIVE
      children {
        behavior {
          enemy_skill_id: 41858
        }
      }
      children {
        behavior {
          enemy_skill_id: 41859
        }
      }
    }
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 41841
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            behavior {
              condition {
                use_chance: 17
              }
              enemy_skill_id: 41852
            }
          }
          children {
            behavior {
              condition {
                use_chance: 17
              }
              enemy_skill_id: 41853
            }
          }
          children {
            behavior {
              condition {
                use_chance: 17
              }
              enemy_skill_id: 41854
            }
          }
          children {
            behavior {
              condition {
                use_chance: 17
              }
              enemy_skill_id: 41855
            }
          }
          children {
            behavior {
              condition {
                use_chance: 16
              }
              enemy_skill_id: 41856
            }
          }
          children {
            behavior {
              condition {
                use_chance: 16
              }
              enemy_skill_id: 41857
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 49
          }
          children {
            group {
              condition {
                trigger_turn: 1
              }
              children {
                behavior {
                  enemy_skill_id: 41844
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  enemy_skill_id: 41848
                }
              }
            }
          }
        }
      }
    }
  }
