  monster_id: 851
  levels {
    level: 5
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 581
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 74
          }
          children {
            behavior {
              condition {
                use_chance: 70
              }
              enemy_skill_id: 582
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 29
          }
          children {
            behavior {
              condition {
                use_chance: 70
              }
              enemy_skill_id: 583
            }
          }
          children {
            behavior {
              condition {
                use_chance: 70
              }
              enemy_skill_id: 582
            }
          }
        }
      }
    }
  }
