  monster_id: 875
  levels {
    level: 5
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 634
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 74
          }
          children {
            behavior {
              condition {
                use_chance: 70
              }
              enemy_skill_id: 624
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 24
          }
          children {
            behavior {
              condition {
                use_chance: 70
              }
              enemy_skill_id: 625
            }
          }
          children {
            behavior {
              condition {
                use_chance: 70
              }
              enemy_skill_id: 624
            }
          }
        }
      }
    }
  }
