  monster_id: 8988
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          condition {
            trigger_monsters: 8990
            trigger_monsters: 8991
          }
          enemy_skill_id: 38496
        }
      }
      children {
        behavior {
          enemy_skill_id: 38497
        }
      }
    }
  }
