  monster_id: 8993
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 27434
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        behavior {
          condition {
            erased_attributes: 3
          }
          enemy_skill_id: 27438
        }
      }
      children {
        behavior {
          enemy_skill_id: 27434
        }
      }
    }
  }
