  monster_id: 9595
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 43692
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        behavior {
          condition {
            use_chance: 33
          }
          enemy_skill_id: 43695
        }
      }
      children {
        behavior {
          condition {
            use_chance: 50
          }
          enemy_skill_id: 43696
        }
      }
      children {
        behavior {
          enemy_skill_id: 43697
        }
      }
    }
  }
