  monster_id: 9680
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 44413
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        group {
          condition {
            trigger_turn: 1
          }
          children {
            behavior {
              condition {
                trigger_combos: 6
              }
              enemy_skill_id: 44418
            }
          }
          children {
            behavior {
              enemy_skill_id: 44434
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 2
          }
          children {
            behavior {
              condition {
                trigger_combos: 7
              }
              enemy_skill_id: 44422
            }
          }
          children {
            behavior {
              enemy_skill_id: 44434
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 3
          }
          children {
            behavior {
              condition {
                trigger_combos: 8
              }
              enemy_skill_id: 44425
            }
          }
          children {
            behavior {
              enemy_skill_id: 44434
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 4
          }
          children {
            behavior {
              condition {
                trigger_combos: 9
              }
              enemy_skill_id: 44430
            }
          }
          children {
            behavior {
              enemy_skill_id: 44434
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 5
          }
          children {
            behavior {
              condition {
                trigger_combos: 10
              }
              enemy_skill_id: 44433
            }
          }
          children {
            behavior {
              enemy_skill_id: 44434
            }
          }
        }
      }
      children {
        group {
          children {
            behavior {
              condition {
                trigger_combos: 10
              }
              enemy_skill_id: 44433
            }
          }
        }
      }
    }
  }
