  monster_id: 9706
  levels {
    level: 1
    groups {
      group_type: PASSIVE
      children {
        behavior {
          enemy_skill_id: 44211
        }
      }
    }
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 44205
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        group {
          condition {
            repeats_every: 5
            trigger_turn: 1
          }
          children {
            behavior {
              enemy_skill_id: 44206
            }
          }
        }
      }
      children {
        group {
          condition {
            repeats_every: 5
            trigger_turn: 2
          }
          children {
            behavior {
              enemy_skill_id: 44207
            }
          }
        }
      }
      children {
        group {
          condition {
            repeats_every: 5
            trigger_turn: 3
          }
          children {
            behavior {
              enemy_skill_id: 44208
            }
          }
        }
      }
      children {
        group {
          condition {
            repeats_every: 5
            trigger_turn: 4
          }
          children {
            behavior {
              enemy_skill_id: 44209
            }
          }
        }
      }
      children {
        group {
          condition {
            repeats_every: 5
            trigger_turn: 5
          }
          children {
            behavior {
              enemy_skill_id: 44210
            }
          }
        }
      }
    }
  }
