  monster_id: 9722
  levels {
    level: 1
    groups {
      group_type: PASSIVE
      children {
        behavior {
          enemy_skill_id: 46138
        }
      }
    }
    groups {
      group_type: PREEMPT
      children {
        behavior {
          condition {
            trigger_monsters: 9726
          }
          enemy_skill_id: 46141
        }
      }
      children {
        behavior {
          enemy_skill_id: 46140
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            group {
              condition {
                repeats_every: 2
                trigger_turn: 1
              }
              children {
                behavior {
                  enemy_skill_id: 46143
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 2
                trigger_turn: 2
              }
              children {
                behavior {
                  enemy_skill_id: 46146
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 9
            trigger_turn: 1
          }
          children {
            behavior {
              enemy_skill_id: 46142
            }
          }
        }
      }
    }
  }
