  monster_id: 9955
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 48038
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        behavior {
          condition {
            use_chance: 33
          }
          enemy_skill_id: 48039
        }
      }
      children {
        behavior {
          condition {
            use_chance: 50
          }
          enemy_skill_id: 48040
        }
      }
      children {
        behavior {
          enemy_skill_id: 48041
        }
      }
    }
  }
